//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CROM.RecursosHumanos.DataAcces.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-PC\\SQLPRODUCCION;Initial Catalog=BD_ComercialElYasan;User ID=s" +
            "a")]
        public string BD_ComercialElYasanConnectionString {
            get {
                return ((string)(this["BD_ComercialElYasanConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MUAKS-PC\\CROMSYSTEM;Initial Catalog=BD_MagesetNew;User ID=SA;Password" +
            "=uscrom")]
        public string BD_MagesetNewConnectionString {
            get {
                return ((string)(this["BD_MagesetNewConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-HOME\\SQLEXPRESS2014;Initial Catalog=BD_GC_MAGESET_20180802;Use" +
            "r ID=sa")]
        public string BD_GC_MAGESET_20180802ConnectionString {
            get {
                return ((string)(this["BD_GC_MAGESET_20180802ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAP01-OCARRIL\\SQLEXPRESSCROM;Initial Catalog=BD_GC_MAGESET;Persist Se" +
            "curity Info=True;User ID=sa;Connect Timeout=30;TrustServerCertificate=False")]
        public string BD_GC_MAGESETConnectionString {
            get {
                return ((string)(this["BD_GC_MAGESETConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAP01-OCARRIL\\SQLEXPRESSCROM;Initial Catalog=BD_GC_MAGESET_SFS_202011" +
            "06;Persist Security Info=True;User ID=sa;Connect Timeout=30;TrustServerCertifica" +
            "te=False")]
        public string BD_GC_MAGESET_SFS_20201106ConnectionString {
            get {
                return ((string)(this["BD_GC_MAGESET_SFS_20201106ConnectionString"]));
            }
        }
    }
}
