//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CROM.Tools.Comun {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HelpMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CROM.Tools.Comun.HelpMessages", typeof(HelpMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ El servidor  no existe, por favor verifique el nombre !.
        /// </summary>
        public static string _17 {
            get {
                return ResourceManager.GetString("17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Especifique un usuario y password.
        /// </summary>
        public static string _18452 {
            get {
                return ResourceManager.GetString("18452", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario o password es incorrecto.
        /// </summary>
        public static string _18456 {
            get {
                return ResourceManager.GetString("18456", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre del objeto (tabla, procedimiento almacenado,etc.)es incorrecto..
        /// </summary>
        public static string _208 {
            get {
                return ResourceManager.GetString("208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Error con el acceso a la base de datos. - Consultar con el DBA !.
        /// </summary>
        public static string _229 {
            get {
                return ResourceManager.GetString("229", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ El dato del campo único de la tabla esta duplicado. !.
        /// </summary>
        public static string _2601 {
            get {
                return ResourceManager.GetString("2601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ No se puede duplicar registro por, llaves primarias ya existen !.
        /// </summary>
        public static string _2627 {
            get {
                return ResourceManager.GetString("2627", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ El usuario no tiene permisos para acceder a la base de datos !.
        /// </summary>
        public static string _4060 {
            get {
                return ResourceManager.GetString("4060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Verificar función que genera código del sistema en la BD. !.
        /// </summary>
        public static string _4121 {
            get {
                return ResourceManager.GetString("4121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ No se puede eliminar el registro...! Puede que este relacionado..
        /// </summary>
        public static string _547 {
            get {
                return ResourceManager.GetString("547", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ No esta habilitado el servidor SQL para uso de CLR-ASSEMBLY !.
        /// </summary>
        public static string _6263 {
            get {
                return ResourceManager.GetString("6263", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a !Registro de la caja no ha sido eliminada!.
        /// </summary>
        public static string CAJA_NoEliminada {
            get {
                return ResourceManager.GetString("CAJA_NoEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 030177191250270155141175020786080481.
        /// </summary>
        public static string CROM_Cadena {
            get {
                return ResourceManager.GetString("CROM_Cadena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OMCRGCPN.
        /// </summary>
        public static string CROM_Existe {
            get {
                return ResourceManager.GetString("CROM_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Archivo de Licencia no es válido para esta PC!, solicitar una licencia nueva para esta PC..
        /// </summary>
        public static string CROM_LicMensaje01 {
            get {
                return ResourceManager.GetString("CROM_LicMensaje01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Solicitar confirmación de licencia, enviar archivo Licencia.xml al correo: [omcr1905@gmail.com];  de la carpeta de trabajo del sistema..
        /// </summary>
        public static string CROM_LicMensaje02 {
            get {
                return ResourceManager.GetString("CROM_LicMensaje02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Archivo Licencia.xml es Incorrecto, solicitar un nuevo archivo de licencia para esta PC.! .
        /// </summary>
        public static string CROM_LicMensaje03 {
            get {
                return ResourceManager.GetString("CROM_LicMensaje03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a !Cuenta corriente no ha sido eliminada!.
        /// </summary>
        public static string CTA_CORRIENTE_NoEliminada {
            get {
                return ResourceManager.GetString("CTA_CORRIENTE_NoEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a !Cuenta corriente no ha sido registrada!.
        /// </summary>
        public static string CTA_CORRIENTE_NoRegistrada {
            get {
                return ResourceManager.GetString("CTA_CORRIENTE_NoRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Registro eliminado satisfactoriamente !.
        /// </summary>
        public static string Evento_DELETE {
            get {
                return ResourceManager.GetString("Evento_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Confirma eliminar el registro seleccionado ?.
        /// </summary>
        public static string Evento_DELETE_Confirma {
            get {
                return ResourceManager.GetString("Evento_DELETE_Confirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Registro tiene dependencia con otro nivel en la tabla !.
        /// </summary>
        public static string Evento_DEPEND {
            get {
                return ResourceManager.GetString("Evento_DEPEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Registro actualizado satisfactoriamente !.
        /// </summary>
        public static string Evento_EDIT {
            get {
                return ResourceManager.GetString("Evento_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Confirma la actualización del registro ...[ SI ]-[ NO ] ?.
        /// </summary>
        public static string Evento_EDIT_Confirma {
            get {
                return ResourceManager.GetString("Evento_EDIT_Confirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Registro insertado satisfactoriamente !.
        /// </summary>
        public static string Evento_NEW {
            get {
                return ResourceManager.GetString("Evento_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Confirma el ingreso del nuevo registro [ SI ]-[ NO ] ?.
        /// </summary>
        public static string Evento_NEW_Confirma {
            get {
                return ResourceManager.GetString("Evento_NEW_Confirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Confirma la cambiar de estado el documento ...[ SI ]-[ NO ] ?.
        /// </summary>
        public static string Evento_REVERTIR_Confirma {
            get {
                return ResourceManager.GetString("Evento_REVERTIR_Confirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Solo tiene permiso para visualizar datos del registro !.
        /// </summary>
        public static string Evento_VIEW {
            get {
                return ResourceManager.GetString("Evento_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ El documento actual aun no lo ha guardado.! ¿ Abandona el documento actual ?.
        /// </summary>
        public static string gc_DOCUM_Abandonar {
            get {
                return ResourceManager.GetString("gc_DOCUM_Abandonar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Seleccionar Almacen/Depósito de destino para los productos. !.
        /// </summary>
        public static string gc_DOCUM_AlmacenDestino {
            get {
                return ResourceManager.GetString("gc_DOCUM_AlmacenDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Seleccionar Almacen/Depósito de origen para los productos. !.
        /// </summary>
        public static string gc_DOCUM_AlmacenOrigen {
            get {
                return ResourceManager.GetString("gc_DOCUM_AlmacenOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Definir datos del documento para poder guardar.!.
        /// </summary>
        public static string gc_DOCUM_DefinirDatos {
            get {
                return ResourceManager.GetString("gc_DOCUM_DefinirDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de documento no ha siso eliminado.
        /// </summary>
        public static string gc_DOCUM_DetalleNoElimnado {
            get {
                return ResourceManager.GetString("gc_DOCUM_DetalleNoElimnado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de documento no ha siso registrado!.
        /// </summary>
        public static string gc_DOCUM_DetalleNoRegis {
            get {
                return ResourceManager.GetString("gc_DOCUM_DetalleNoRegis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ La devolución de la mercaderia se ha realizado satisfactoriamente.!.
        /// </summary>
        public static string gc_DOCUM_Devolucion_Producto {
            get {
                return ResourceManager.GetString("gc_DOCUM_Devolucion_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Documento se encuentra en estado: [ {0} ] !.
        /// </summary>
        public static string gc_DOCUM_Estado {
            get {
                return ResourceManager.GetString("gc_DOCUM_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Documento no realiza, no esta asigando para formas de pagos/cobranza.!.
        /// </summary>
        public static string gc_DOCUM_FormaDePago {
            get {
                return ResourceManager.GetString("gc_DOCUM_FormaDePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Documento se encuentra en estado: [ {0} ] !.
        /// </summary>
        public static string gc_DOCUM_LetraCambioDeDocum {
            get {
                return ResourceManager.GetString("gc_DOCUM_LetraCambioDeDocum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Confirma eliminar la letra de cambio?.
        /// </summary>
        public static string gc_DOCUM_LetraCambioEliminar {
            get {
                return ResourceManager.GetString("gc_DOCUM_LetraCambioEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Seleccionar estado para la letra de cambio.!.
        /// </summary>
        public static string gc_DOCUM_LetraCambioEstado {
            get {
                return ResourceManager.GetString("gc_DOCUM_LetraCambioEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Fecha de recepción para la letra de cambio es incorrecta.!.
        /// </summary>
        public static string gc_DOCUM_LetraCambioFechaRecep {
            get {
                return ResourceManager.GetString("gc_DOCUM_LetraCambioFechaRecep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Confirma guardar la fecha de recepción de la letra de cambio?.
        /// </summary>
        public static string gc_DOCUM_LetraCambioGuardaFechaRecep {
            get {
                return ResourceManager.GetString("gc_DOCUM_LetraCambioGuardaFechaRecep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Confirma guardar el estado seleccionado de la letra de cambio?.
        /// </summary>
        public static string gc_DOCUM_LetraCambioGuardar {
            get {
                return ResourceManager.GetString("gc_DOCUM_LetraCambioGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ No se puede anular documento esta siendo referenciado a otro {0}!.
        /// </summary>
        public static string gc_DOCUM_NO_ANULADO {
            get {
                return ResourceManager.GetString("gc_DOCUM_NO_ANULADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Número de documento no existe, o fué eliminado. !.
        /// </summary>
        public static string gc_DOCUM_NO_EXISTE_DOCUM {
            get {
                return ResourceManager.GetString("gc_DOCUM_NO_EXISTE_DOCUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Documento no ha sido anulado. !.
        /// </summary>
        public static string gc_DOCUM_NoAnulado {
            get {
                return ResourceManager.GetString("gc_DOCUM_NoAnulado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ No se han definido documentos de emisión para el sistema. !.
        /// </summary>
        public static string gc_DOCUM_NoDefinido {
            get {
                return ResourceManager.GetString("gc_DOCUM_NoDefinido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Documento no se ha desasignado su referencia.!.
        /// </summary>
        public static string gc_DOCUM_NoDesAsigRefer {
            get {
                return ResourceManager.GetString("gc_DOCUM_NoDesAsigRefer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Documento se encuentra en estado no editable, Por favor volver a seleccionar el tipo de documento. !.
        /// </summary>
        public static string gc_DOCUM_NoEditable {
            get {
                return ResourceManager.GetString("gc_DOCUM_NoEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ No existe la entidad a bucar....!.
        /// </summary>
        public static string gc_DOCUM_NoEntidad {
            get {
                return ResourceManager.GetString("gc_DOCUM_NoEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Documento no es para realizar este tipo de operaciones. !.
        /// </summary>
        public static string gc_DOCUM_NoEsFiscal {
            get {
                return ResourceManager.GetString("gc_DOCUM_NoEsFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Aún no ha guardado el documento, Por favor guardar el documento. !.
        /// </summary>
        public static string gc_DOCUM_NoGuardado {
            get {
                return ResourceManager.GetString("gc_DOCUM_NoGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Documento no esta habilitado para impresión de formato. !.
        /// </summary>
        public static string gc_DOCUM_NoImprime {
            get {
                return ResourceManager.GetString("gc_DOCUM_NoImprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Documento [ {0} ] no es para cobranza o se realiza pagos. !.
        /// </summary>
        public static string gc_DOCUM_NoPagos {
            get {
                return ResourceManager.GetString("gc_DOCUM_NoPagos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Documento [ {0} ] no realiza, no esta asigando para formas de pagos/cobranza.!.
        /// </summary>
        public static string gc_DOCUM_NoPagosEstado {
            get {
                return ResourceManager.GetString("gc_DOCUM_NoPagosEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Documento [ {0} ] no se encuentra registrado !.
        /// </summary>
        public static string gc_DOCUM_NoRegistrado {
            get {
                return ResourceManager.GetString("gc_DOCUM_NoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ El monto total de la nota de crédito no puede ser mayor a su documento de referencia. !.
        /// </summary>
        public static string gc_DOCUM_NotaCreditoMayor {
            get {
                return ResourceManager.GetString("gc_DOCUM_NotaCreditoMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ No se ha definido número de documento a emitir !.
        /// </summary>
        public static string gc_DOCUM_NroDefinido {
            get {
                return ResourceManager.GetString("gc_DOCUM_NroDefinido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Confirma anular este documento..[ SI ]-[ NO ] ?.
        /// </summary>
        public static string gc_DOCUM_SE_ANULARA {
            get {
                return ResourceManager.GetString("gc_DOCUM_SE_ANULARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Confirma cancelar este documento..[ SI ]-[ NO ] ?.
        /// </summary>
        public static string gc_DOCUM_SE_CANCELARA {
            get {
                return ResourceManager.GetString("gc_DOCUM_SE_CANCELARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Confirma eliminar este documento..[ SI ]-[ NO ] ?.
        /// </summary>
        public static string gc_DOCUM_SE_ELIMINARA {
            get {
                return ResourceManager.GetString("gc_DOCUM_SE_ELIMINARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Confirma revertir el estado del documento..[ SI ]-[ NO ] ?.
        /// </summary>
        public static string gc_DOCUM_SE_REVERTIRA {
            get {
                return ResourceManager.GetString("gc_DOCUM_SE_REVERTIRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Aún no se ha seleccionado documento para emitir. !.
        /// </summary>
        public static string gc_DOCUM_Selecciona {
            get {
                return ResourceManager.GetString("gc_DOCUM_Selecciona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Seleccionar el tipo de moneda para el documento. !.
        /// </summary>
        public static string gc_DOCUM_SeleccionaMoneda {
            get {
                return ResourceManager.GetString("gc_DOCUM_SeleccionaMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Documento a emitir no tiene valor el tipo de cambio, ubicarse en la fecha de emisión.!.
        /// </summary>
        public static string gc_DOCUM_TipoDeCambio {
            get {
                return ResourceManager.GetString("gc_DOCUM_TipoDeCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ El importe total del documento a emitir debe ser mayor que cero (0)!.
        /// </summary>
        public static string gc_DOCUM_TotalIgualCero {
            get {
                return ResourceManager.GetString("gc_DOCUM_TotalIgualCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Documento o Item ya se ha anulado satisfactoriamente. !.
        /// </summary>
        public static string gc_DOCUM_YA_ANULADO {
            get {
                return ResourceManager.GetString("gc_DOCUM_YA_ANULADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Documento ARCHIVADO satisfactoriamente. !.
        /// </summary>
        public static string gc_DOCUM_YA_ARCHIVADO {
            get {
                return ResourceManager.GetString("gc_DOCUM_YA_ARCHIVADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Pago de documento  se ha cancelado/pagado satisfactoriamente. !.
        /// </summary>
        public static string gc_DOCUM_YA_CANCELADO {
            get {
                return ResourceManager.GetString("gc_DOCUM_YA_CANCELADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Documento ya se encuentra como cancelado en el historial del Pago!. .
        /// </summary>
        public static string gc_DOCUM_YA_CANCELADOExiste {
            get {
                return ResourceManager.GetString("gc_DOCUM_YA_CANCELADOExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Documento ya ha sido declarado o contabilizado. !.
        /// </summary>
        public static string gc_DOCUM_YA_CONTABILIZADO {
            get {
                return ResourceManager.GetString("gc_DOCUM_YA_CONTABILIZADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Documento ya se ha revertido satisfactoriamente. !.
        /// </summary>
        public static string gc_DOCUM_YA_REVERTIDO {
            get {
                return ResourceManager.GetString("gc_DOCUM_YA_REVERTIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Solo se debe de archivar Cotizaciones y Guias de Remisión!.
        /// </summary>
        public static string gc_DOCUMAlertaPorArchivo {
            get {
                return ResourceManager.GetString("gc_DOCUMAlertaPorArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Confirma ARCHIVAR documento {0} con número {1} ?.
        /// </summary>
        public static string gc_DOCUMConfirmaArchivo {
            get {
                return ResourceManager.GetString("gc_DOCUMConfirmaArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Seleccionar empleado que esta emitiendo el documento.!.
        /// </summary>
        public static string gc_DOCUMENTOS_Empleado {
            get {
                return ResourceManager.GetString("gc_DOCUMENTOS_Empleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ No se ha definido rango o números de serie para documento [ {0} ] !.
        /// </summary>
        public static string gc_DOCUMENTOS_Series {
            get {
                return ResourceManager.GetString("gc_DOCUMENTOS_Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Aumentar el número correlativo de la serie del documento seleccionado. !.
        /// </summary>
        public static string gc_DOCUMENTOS_SeriesUltimo {
            get {
                return ResourceManager.GetString("gc_DOCUMENTOS_SeriesUltimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ No se encuentra definido el impuesto para la emisión de documento!.
        /// </summary>
        public static string gc_IMPUESTO_NoDefinido {
            get {
                return ResourceManager.GetString("gc_IMPUESTO_NoDefinido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Las letras de cambio se han generado satisfactoriamente.!.
        /// </summary>
        public static string gc_LETRASCreadas {
            get {
                return ResourceManager.GetString("gc_LETRASCreadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Las letras de cambio han  sido editadas satisfactoriamente.!.
        /// </summary>
        public static string gc_LETRASEditadas {
            get {
                return ResourceManager.GetString("gc_LETRASEditadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Cantidad de ítem tiene que ser mayor que cero. !.
        /// </summary>
        public static string gc_PEDD_CANTIDAD_ITEM {
            get {
                return ResourceManager.GetString("gc_PEDD_CANTIDAD_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Seleccionar código de producto para este ítem. !.
        /// </summary>
        public static string gc_PEDD_CODIGO_ITEM {
            get {
                return ResourceManager.GetString("gc_PEDD_CODIGO_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Confirma eliminar el ítem seleccionado ?.
        /// </summary>
        public static string gc_PEDD_DELETE_ITEM {
            get {
                return ResourceManager.GetString("gc_PEDD_DELETE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Número de documento ya existe, ingresar otro número. !.
        /// </summary>
        public static string gc_PEDD_EXISTE_DOCUM {
            get {
                return ResourceManager.GetString("gc_PEDD_EXISTE_DOCUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ La cantidad límite de ítems a registrar son : [ {0} ] ítems. !.
        /// </summary>
        public static string gc_PEDD_MAXIMO_ITEMS {
            get {
                return ResourceManager.GetString("gc_PEDD_MAXIMO_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ No existen ítem&apos;s para  hacer  edición en el documento. !.
        /// </summary>
        public static string gc_PEDD_NO_HAY_ITEMS {
            get {
                return ResourceManager.GetString("gc_PEDD_NO_HAY_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Precio de ítem de documento tiene que ser mayor que cero. !.
        /// </summary>
        public static string gc_PEDD_PRECIO_ITEM {
            get {
                return ResourceManager.GetString("gc_PEDD_PRECIO_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Seleccionar entidad para seguir con el proceso. !.
        /// </summary>
        public static string gc_PEDD_SELECT_ENTIDAD {
            get {
                return ResourceManager.GetString("gc_PEDD_SELECT_ENTIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Seleccionar unidad de medida para el ítem del documento. !.
        /// </summary>
        public static string gc_PEDD_UNIDAD_MEDIDA {
            get {
                return ResourceManager.GetString("gc_PEDD_UNIDAD_MEDIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Este estado solo es actualizado por emisión de GUIAS DE REMISIONES por motivo de Consignación!.
        /// </summary>
        public static string gc_PRODU_SERIADO_Consigna {
            get {
                return ResourceManager.GetString("gc_PRODU_SERIADO_Consigna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Confirma la devolución de los productos prestados por Consignación?.
        /// </summary>
        public static string gc_PRODU_SERIADO_Devolucion {
            get {
                return ResourceManager.GetString("gc_PRODU_SERIADO_Devolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Se necesita un nombre de rango definido en la hoja de excel para buscar!.
        /// </summary>
        public static string gc_PRODU_SERIADO_Importa {
            get {
                return ResourceManager.GetString("gc_PRODU_SERIADO_Importa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Solo debe de seleccionar [ {0} ] numeros de series. !.
        /// </summary>
        public static string gc_PRODU_SERIADO_Selecciona {
            get {
                return ResourceManager.GetString("gc_PRODU_SERIADO_Selecciona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Confirma actualizar registro de N° de serie de producto ?.
        /// </summary>
        public static string gc_PRODU_SERIADO_Update {
            get {
                return ResourceManager.GetString("gc_PRODU_SERIADO_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Aún no se ha definido el código del producto. !.
        /// </summary>
        public static string gc_PRODUConsultas {
            get {
                return ResourceManager.GetString("gc_PRODUConsultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Ingresar código de referencia para el grupo. !.
        /// </summary>
        public static string gc_PRODUGRUPOCodigoRef {
            get {
                return ResourceManager.GetString("gc_PRODUGRUPOCodigoRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Ingresar descripción o nombre para el grupo. !.
        /// </summary>
        public static string gc_PRODUGRUPODescrip {
            get {
                return ResourceManager.GetString("gc_PRODUGRUPODescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Seleccionar línea para el grupo. !.
        /// </summary>
        public static string gc_PRODUGRUPOLinea {
            get {
                return ResourceManager.GetString("gc_PRODUGRUPOLinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Seleccionar material para el grupo. !.
        /// </summary>
        public static string gc_PRODUGRUPOMaterial {
            get {
                return ResourceManager.GetString("gc_PRODUGRUPOMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Seleccionar unidad de medida para el grupo. !.
        /// </summary>
        public static string gc_PRODUGRUPOUnidad {
            get {
                return ResourceManager.GetString("gc_PRODUGRUPOUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Producto no se ha registrado. completar mas datos!.
        /// </summary>
        public static string gc_PRODUNoRegistrado {
            get {
                return ResourceManager.GetString("gc_PRODUNoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Ingresar el código para el nuevo registro del producto. !.
        /// </summary>
        public static string gc_PRODUValidaCodigo {
            get {
                return ResourceManager.GetString("gc_PRODUValidaCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Ingresar el código para el registro del producto. !.
        /// </summary>
        public static string gc_PRODUValidaCodigoREF {
            get {
                return ResourceManager.GetString("gc_PRODUValidaCodigoREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Ingresar la descripción para el registro. !.
        /// </summary>
        public static string gc_PRODUValidaDescrip {
            get {
                return ResourceManager.GetString("gc_PRODUValidaDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Ingresar la descripción abreviada para el registro del producto. !.
        /// </summary>
        public static string gc_PRODUValidaDescripAbr {
            get {
                return ResourceManager.GetString("gc_PRODUValidaDescripAbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Ingresar la descripción comercial para el registro del producto. !.
        /// </summary>
        public static string gc_PRODUValidaDescripCom {
            get {
                return ResourceManager.GetString("gc_PRODUValidaDescripCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de número de serie ya tiene operaciones..
        /// </summary>
        public static string gc_PRODUValidaEditNroSerie {
            get {
                return ResourceManager.GetString("gc_PRODUValidaEditNroSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Seleccionar como mínimo un atributo como parte de un producto. !.
        /// </summary>
        public static string gc_PRODUValidaMinAtrPart {
            get {
                return ResourceManager.GetString("gc_PRODUValidaMinAtrPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Seleccionar el tipo de moneda para el producto. !.
        /// </summary>
        public static string gc_PRODUValidaMoneda {
            get {
                return ResourceManager.GetString("gc_PRODUValidaMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Seleccionar el tipo de producto. !.
        /// </summary>
        public static string gc_PRODUValidaTipoProduc {
            get {
                return ResourceManager.GetString("gc_PRODUValidaTipoProduc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Seleccionar unidad de medida para el producto. !.
        /// </summary>
        public static string gc_PRODUValidaUnidad {
            get {
                return ResourceManager.GetString("gc_PRODUValidaUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Registro de tipo de cambio para hoy ya existe !.
        /// </summary>
        public static string gc_TIPO_CAMBIO_Existe {
            get {
                return ResourceManager.GetString("gc_TIPO_CAMBIO_Existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estimado usuario a ocurrido un error. Por favor contactese con el admnistrador del sistema para que verifique el LOG del sistema..
        /// </summary>
        public static string GeneralAPP_MensajeErrorUser {
            get {
                return ResourceManager.GetString("GeneralAPP_MensajeErrorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra habilitado el servicio. Error interno!.
        /// </summary>
        public static string GeneralWSERVICE_NoComunicacion {
            get {
                return ResourceManager.GetString("GeneralWSERVICE_NoComunicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Confirma realizar el cierre del Inventario del presente periodo ?.
        /// </summary>
        public static string INVENTARIO_CIERRE_Confirmar {
            get {
                return ResourceManager.GetString("INVENTARIO_CIERRE_Confirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Confirma deshacer el cierre del Inventario del presente periodo ?.
        /// </summary>
        public static string INVENTARIO_CIERRE_Deshacer {
            get {
                return ResourceManager.GetString("INVENTARIO_CIERRE_Deshacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha deshecho el cierre del Inventario del presente periodo..
        /// </summary>
        public static string INVENTARIO_CIERRE_DeshacerOK {
            get {
                return ResourceManager.GetString("INVENTARIO_CIERRE_DeshacerOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Seleccionar depósito/almacén para procesar stocks de productos. !.
        /// </summary>
        public static string INVENTARIO_ProcesoValidaAlmacen {
            get {
                return ResourceManager.GetString("INVENTARIO_ProcesoValidaAlmacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Documento a emitir no tiene configuración para controlar stocks.!.
        /// </summary>
        public static string INVENTARIO_ProcesoValidaDocumento {
            get {
                return ResourceManager.GetString("INVENTARIO_ProcesoValidaDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ No existen productos para inventarios en la lista.!.
        /// </summary>
        public static string INVENTARIO_ProcesoValidaProducto {
            get {
                return ResourceManager.GetString("INVENTARIO_ProcesoValidaProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Proceso de inventario NO se ha cerrado con Éxito....!.
        /// </summary>
        public static string InventarioCerradoNOOK {
            get {
                return ResourceManager.GetString("InventarioCerradoNOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Proceso de inventario se ha cerrado con Éxito....!.
        /// </summary>
        public static string InventarioCerradoOK {
            get {
                return ResourceManager.GetString("InventarioCerradoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Proceso de generar documentos por mermas o sobras terminado....!.
        /// </summary>
        public static string InventarioDocumentoNI_NS_OK {
            get {
                return ResourceManager.GetString("InventarioDocumentoNI_NS_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Se recomienda completar el Valor de Venta y Costo de los productos; para obtener un mejor resultado.!.
        /// </summary>
        public static string INVENTARIOValidacionCIERREPrecios {
            get {
                return ResourceManager.GetString("INVENTARIOValidacionCIERREPrecios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡No existe números de series disponibles. Validar proceso!.
        /// </summary>
        public static string InventarioVALIDACIONNENS {
            get {
                return ResourceManager.GetString("InventarioVALIDACIONNENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Números de series guardados de forma temporal.!.
        /// </summary>
        public static string InventarioVALIDACIONNSGFT {
            get {
                return ResourceManager.GetString("InventarioVALIDACIONNSGFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Aún no ha seleccionado los Números de SERIES. Validar proceso!.
        /// </summary>
        public static string InventarioVALIDACIONNSNS {
            get {
                return ResourceManager.GetString("InventarioVALIDACIONNSNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ No se ha registrado documento para registro de cierres de inventarios... !.
        /// </summary>
        public static string InventarioValidaDocum {
            get {
                return ResourceManager.GetString("InventarioValidaDocum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ No se ha registrado (NOTA DE INGRESO/NOTA DE SALIDA) o numero de series para registro de reguralización de inventarios... !.
        /// </summary>
        public static string InventarioValidaDocumentoNI_NS {
            get {
                return ResourceManager.GetString("InventarioValidaDocumentoNI_NS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Seleccionar periodo de Inventario. Vuelva a seleccionar Almacén !.
        /// </summary>
        public static string InventarioValidaPeriodo {
            get {
                return ResourceManager.GetString("InventarioValidaPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de KARDEX no ha sido registrado!..
        /// </summary>
        public static string KARDEX_NoRegistrado {
            get {
                return ResourceManager.GetString("KARDEX_NoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ El tipo de operación seleccioado no genera registro en KARDEX!..
        /// </summary>
        public static string KARDEX_ValidaCantidadES {
            get {
                return ResourceManager.GetString("KARDEX_ValidaCantidadES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a !Registro de la letra de cambio no ha sido eliminada!.
        /// </summary>
        public static string LETRACAMBIO_NoEliminada {
            get {
                return ResourceManager.GetString("LETRACAMBIO_NoEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Ingresar apellidos para la persona natural !.
        /// </summary>
        public static string MAESTROSApellidos {
            get {
                return ResourceManager.GetString("MAESTROSApellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ El atributo de la persona : [ {0} ] ya se encuentra registrado. !.
        /// </summary>
        public static string MAESTROSAtributoValida {
            get {
                return ResourceManager.GetString("MAESTROSAtributoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Persona no tiene registrado el número de documento fiscal R.U.C. !.
        /// </summary>
        public static string MAESTROSAtributoValidaDocumFiscal {
            get {
                return ResourceManager.GetString("MAESTROSAtributoValidaDocumFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Persona no tiene registrado el número de documento de D.N.I. !.
        /// </summary>
        public static string MAESTROSAtributoValidaDocumNatural {
            get {
                return ResourceManager.GetString("MAESTROSAtributoValidaDocumNatural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Persona no tiene registrado el atributo de domicilio fiscal !.
        /// </summary>
        public static string MAESTROSAtributoValidaDomicFiscal {
            get {
                return ResourceManager.GetString("MAESTROSAtributoValidaDomicFiscal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ No se puede iniciar copia de seguridad de la base de datos !.
        /// </summary>
        public static string MAESTROSBackup {
            get {
                return ResourceManager.GetString("MAESTROSBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Ingesar código para la persona !.
        /// </summary>
        public static string MAESTROSCodigoPersona {
            get {
                return ResourceManager.GetString("MAESTROSCodigoPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Ingresar nombres para la persona natural !.
        /// </summary>
        public static string MAESTROSNombres {
            get {
                return ResourceManager.GetString("MAESTROSNombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Ingresar nombre de razón social para pesona jurídica !.
        /// </summary>
        public static string MAESTROSRazonSocial {
            get {
                return ResourceManager.GetString("MAESTROSRazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ La razón social o nombre de persona ya está registrado en el sistema !.
        /// </summary>
        public static string MAESTROSRazonSocialValida {
            get {
                return ResourceManager.GetString("MAESTROSRazonSocialValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Seleccionar el tipo de entidad para la persona !.
        /// </summary>
        public static string MAESTROSTipoEntidad {
            get {
                return ResourceManager.GetString("MAESTROSTipoEntidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Se está iniciando el acceso al sistema.
        /// </summary>
        public static string MensajeInicio {
            get {
                return ResourceManager.GetString("MensajeInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ No se puede inicializar el sistema !.
        /// </summary>
        public static string MensajeInicioError {
            get {
                return ResourceManager.GetString("MensajeInicioError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ No existe la base de datos  para el sistema en :.
        /// </summary>
        public static string MensajeInicioErrorBD {
            get {
                return ResourceManager.GetString("MensajeInicioErrorBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Se hizo la apertura de la licencia del sistema ! \r ¡ Por favor volver a iniciar el sistema !.
        /// </summary>
        public static string MensajeInicioLic {
            get {
                return ResourceManager.GetString("MensajeInicioLic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Mensaje de licencia para esta PC !.
        /// </summary>
        public static string MensajeInicioLic1 {
            get {
                return ResourceManager.GetString("MensajeInicioLic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Licencia del sistema para esta PC. es INVÁLIDA! \r ¡ Contactarse con Orlando Carril al Cel:01-997405565 !.
        /// </summary>
        public static string MensajeInicioLicError {
            get {
                return ResourceManager.GetString("MensajeInicioLicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Tarjeta de Marcación de Empleado ya existe !.
        /// </summary>
        public static string PERS_TARJETA_DUPLICADA {
            get {
                return ResourceManager.GetString("PERS_TARJETA_DUPLICADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Confirma salir del sistema de Gestión Comercial ?.
        /// </summary>
        public static string SALIDA_GestionComercial {
            get {
                return ResourceManager.GetString("SALIDA_GestionComercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Confirma salir del sistema de Impresión de Fotografías?.
        /// </summary>
        public static string SALIDA_ImpresionPhoto {
            get {
                return ResourceManager.GetString("SALIDA_ImpresionPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla Detalle Actualizada satisfactoriamente..
        /// </summary>
        public static string TEDetalleActualizado {
            get {
                return ResourceManager.GetString("TEDetalleActualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el Código de Argumento del Registro..
        /// </summary>
        public static string TEDetalleCodiArgumento {
            get {
                return ResourceManager.GetString("TEDetalleCodiArgumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ El código de la tabla detalle ya se encuentra Registrado. !.
        /// </summary>
        public static string TEDetalleCodigoDetalleYaExiste {
            get {
                return ResourceManager.GetString("TEDetalleCodigoDetalleYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Ingrese el código de la tabla. !.
        /// </summary>
        public static string TEDetalleCodigoTabla {
            get {
                return ResourceManager.GetString("TEDetalleCodigoTabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Ingrese el código de la tabla maestra. !.
        /// </summary>
        public static string TEDetalleCodigoTablaMaestra {
            get {
                return ResourceManager.GetString("TEDetalleCodigoTablaMaestra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Ingrese la descripción corta.! .
        /// </summary>
        public static string TEDetalleDescripcionCorta {
            get {
                return ResourceManager.GetString("TEDetalleDescripcionCorta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ El Nombre de la tabla ya se encuentra Registrado. !.
        /// </summary>
        public static string TEDetalleDescripcionDetalleYaExiste {
            get {
                return ResourceManager.GetString("TEDetalleDescripcionDetalleYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Ingresar la descripcion larga del registro. !.
        /// </summary>
        public static string TEDetalleDescripcionLarga {
            get {
                return ResourceManager.GetString("TEDetalleDescripcionLarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Existe dependencia de registros de la tabla detalle. !.
        /// </summary>
        public static string TEDetalleExisteDependenciaDetalle {
            get {
                return ResourceManager.GetString("TEDetalleExisteDependenciaDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Ingresar el código de argumento. !.
        /// </summary>
        public static string TEDetalleIngreseCodigoArgumento {
            get {
                return ResourceManager.GetString("TEDetalleIngreseCodigoArgumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Ingresar el número de nivel del código de argumento. En caso que no tenga niveles !.
        /// </summary>
        public static string TEDetalleNivelDetalle {
            get {
                return ResourceManager.GetString("TEDetalleNivelDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ No se localizó el código de la tabla padre. !.
        /// </summary>
        public static string TEDetalleNoLocalizaTablaPadre {
            get {
                return ResourceManager.GetString("TEDetalleNoLocalizaTablaPadre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿ Confirma eliminar el registro de la tabla maestra ?.
        /// </summary>
        public static string TEDetallePreguntaElimina {
            get {
                return ResourceManager.GetString("TEDetallePreguntaElimina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Tabla detalle grabada satisfactoriamente. !.
        /// </summary>
        public static string TEDetalleRegistrado {
            get {
                return ResourceManager.GetString("TEDetalleRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ No se ha seleccionado el tipo de atributo para la persona !.
        /// </summary>
        public static string TMTipoDeAtributo {
            get {
                return ResourceManager.GetString("TMTipoDeAtributo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Ingrsar descripción del atributo seleccionado !.
        /// </summary>
        public static string TMTipoDeAtributoDescripcion {
            get {
                return ResourceManager.GetString("TMTipoDeAtributoDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Seleccionar el ubigeo para el domicilio de la persona !.
        /// </summary>
        public static string TMValidarUbigeo {
            get {
                return ResourceManager.GetString("TMValidarUbigeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tiene configurado la apertura de caja de forma automática..
        /// </summary>
        public static string VALIDACIONCajaAutomatica {
            get {
                return ResourceManager.GetString("VALIDACIONCajaAutomatica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡La validación de la DUA NO es CORRECTA, existen Números de Series sin asignar para la DUA!..
        /// </summary>
        public static string ValidacionDUAkO {
            get {
                return ResourceManager.GetString("ValidacionDUAkO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡La validación de la DUA es CORRECTA!..
        /// </summary>
        public static string ValidacionDUAok {
            get {
                return ResourceManager.GetString("ValidacionDUAok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Código de registro primario ya existe. !.
        /// </summary>
        public static string VALIDACIONDuplicadoID {
            get {
                return ResourceManager.GetString("VALIDACIONDuplicadoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Empleado asignado no existe.  Usuario [ {0} ] no pertenece a la empresa!.
        /// </summary>
        public static string VALIDACIONEmpleado {
            get {
                return ResourceManager.GetString("VALIDACIONEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Empresa no esta asignada como usuario del sistema !.
        /// </summary>
        public static string VALIDACIONEmpresaClienteCROM {
            get {
                return ResourceManager.GetString("VALIDACIONEmpresaClienteCROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ N° de documento externo ya existe, {0} - {1}. !.
        /// </summary>
        public static string VALIDACIONExisteDocumExterno {
            get {
                return ResourceManager.GetString("VALIDACIONExisteDocumExterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Registro seleccionado ya existe. {0}!.
        /// </summary>
        public static string VALIDACIONExisteRegistro {
            get {
                return ResourceManager.GetString("VALIDACIONExisteRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Completar los datos principales requeridos para el registro. !.
        /// </summary>
        public static string VALIDACIONGeneral {
            get {
                return ResourceManager.GetString("VALIDACIONGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Empresa no tiene registrado Correo electrónico.!.
        /// </summary>
        public static string VALIDACIONMail {
            get {
                return ResourceManager.GetString("VALIDACIONMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Correo electrónico registrado es incorrecto : [{0}].!.
        /// </summary>
        public static string VALIDACIONMailEnvio {
            get {
                return ResourceManager.GetString("VALIDACIONMailEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Registro seleccionado no existe.!.
        /// </summary>
        public static string VALIDACIONNoExiste {
            get {
                return ResourceManager.GetString("VALIDACIONNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Proceso seleccionado aun no esta implementado. !.
        /// </summary>
        public static string VALIDACIONProceso {
            get {
                return ResourceManager.GetString("VALIDACIONProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Producto no tiene precio registrado.!.
        /// </summary>
        public static string VALIDACIONProductoPrecio {
            get {
                return ResourceManager.GetString("VALIDACIONProductoPrecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Seleccionar punto de venta para continuar!.
        /// </summary>
        public static string VALIDACIONPuntoDeVenta {
            get {
                return ResourceManager.GetString("VALIDACIONPuntoDeVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Tipo de cambio no existe para la fecha : [{0}].!.
        /// </summary>
        public static string VALIDACIONTipoDeCambio {
            get {
                return ResourceManager.GetString("VALIDACIONTipoDeCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Contraseña de usuario es incorrecta !.
        /// </summary>
        public static string VALIDACIONUsuario {
            get {
                return ResourceManager.GetString("VALIDACIONUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡ Empleado no existe en el sistema de seguridad.!.
        /// </summary>
        public static string VALIDACIONUsuarioEmpleado {
            get {
                return ResourceManager.GetString("VALIDACIONUsuarioEmpleado", resourceCulture);
            }
        }
    }
}
