#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CROM.GestionComercial.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_GC_MAGESET_20180802")]
	public partial class _ConsultasGCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public _ConsultasGCDataContext() : 
				base(global::CROM.GestionComercial.DataAccess.Properties.Settings.Default.BD_GC_MAGESET_20180802ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public _ConsultasGCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _ConsultasGCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _ConsultasGCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _ConsultasGCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.omgc_R_DocumRegEnAniosVentasCompras")]
		public ISingleResult<omgc_R_DocumRegEnAniosVentasComprasResult> omgc_R_DocumRegEnAniosVentasCompras([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string prm_CodigoPersonaEntidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string prm_CodigoPuntoVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_AnioProceso, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_MesIni, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_MesFin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> prm_TipoCambio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string prm_CodigoArguDestinoComp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_codEmpresa, prm_CodigoPersonaEntidad, prm_CodigoPuntoVenta, prm_AnioProceso, prm_MesIni, prm_MesFin, prm_TipoCambio, prm_CodigoArguDestinoComp);
			return ((ISingleResult<omgc_R_DocumRegEnAniosVentasComprasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.omgc_R_RegistroDeVentasComprasDetallado")]
		public ISingleResult<omgc_R_RegistroDeVentasComprasDetalladoResult> omgc_R_RegistroDeVentasComprasDetallado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaInicio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaFinal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string prm_CodigoPuntoVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string prm_CodigoComprobante, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string prm_CodigoPersonaEntidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpleadoVendedor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string prm_CodigoArguDestinoComp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_codEmpresa, prm_FechaInicio, prm_FechaFinal, prm_CodigoPuntoVenta, prm_CodigoComprobante, prm_CodigoPersonaEntidad, prm_codEmpleado, prm_codEmpleadoVendedor, prm_CodigoArguDestinoComp);
			return ((ISingleResult<omgc_R_RegistroDeVentasComprasDetalladoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.omgc_R_DocumRegVentasComprasContabMensual")]
		public ISingleResult<omgc_R_DocumRegVentasComprasContabMensualResult> omgc_R_DocumRegVentasComprasContabMensual([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaInicio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaFinal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string prm_CodigoPuntoVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string prm_CodigoComprobante, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string prm_CodigoPersonaEntidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string prm_CodigoArguDestinoComp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_codEmpresa, prm_FechaInicio, prm_FechaFinal, prm_CodigoPuntoVenta, prm_CodigoComprobante, prm_CodigoPersonaEntidad, prm_codEmpleado, prm_CodigoArguDestinoComp);
			return ((ISingleResult<omgc_R_DocumRegVentasComprasContabMensualResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.omgc_R_PorEntidadesProductoVentasCompras")]
		public ISingleResult<omgc_R_PorEntidadesProductoVentasComprasResult> omgc_R_PorEntidadesProductoVentasCompras([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string prm_CodigoPersonaEntidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string prm_CodigoPuntoVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaInicio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaFinal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string prm_CodigoArgudestinoComp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string prm_CodigoComprobante)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_codEmpresa, prm_CodigoPersonaEntidad, prm_CodigoPuntoVenta, prm_FechaInicio, prm_FechaFinal, prm_CodigoArgudestinoComp, prm_CodigoComprobante);
			return ((ISingleResult<omgc_R_PorEntidadesProductoVentasComprasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.omgc_R_PorProductoEnAniosVentasCompras")]
		public ISingleResult<omgc_R_PorProductoEnAniosVentasComprasResult> omgc_R_PorProductoEnAniosVentasCompras([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string prm_CodigoPuntoVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string prm_codDeposito, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_AnioProceso, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_MesIni, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_MesFin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(8,3)")] System.Nullable<decimal> prm_TipoCambio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string prm_CodigoArguDestinoComp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_codEmpresa, prm_codProducto, prm_CodigoPuntoVenta, prm_codDeposito, prm_AnioProceso, prm_MesIni, prm_MesFin, prm_TipoCambio, prm_CodigoArguDestinoComp);
			return ((ISingleResult<omgc_R_PorProductoEnAniosVentasComprasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.omgc_R_Producto_Consignacion")]
		public ISingleResult<omgc_R_Producto_ConsignacionResult> omgc_R_Producto_Consignacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string p_fecDesde, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string p_fecHasta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string p_codPuntoDeVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string p_codPersonaMovimi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string p_codDocumento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(16)")] string p_numDocumento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(16)")] string p_numSerie)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codEmpresa, p_fecDesde, p_fecHasta, p_codProducto, p_codPuntoDeVenta, p_codPersonaMovimi, p_codDocumento, p_numDocumento, p_numSerie);
			return ((ISingleResult<omgc_R_Producto_ConsignacionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.omgc_R_ProductoInventario")]
		public ISingleResult<omgc_R_ProductoInventarioResult> omgc_R_ProductoInventario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string prm_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaDeEmisionINI, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaDeEmisionFIN, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string prm_codPuntoVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string prm_codDeposito, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(6)")] string prm_Periodo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string prm_desAgrupacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_codEmpresa, prm_FechaDeEmisionINI, prm_FechaDeEmisionFIN, prm_codPuntoVenta, prm_codDeposito, prm_Periodo, prm_desAgrupacion);
			return ((ISingleResult<omgc_R_ProductoInventarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.omgc_R_ProductoInventarioActual")]
		public ISingleResult<omgc_R_ProductoInventarioActualResult> omgc_R_ProductoInventarioActual([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string prm_codEmpresaRUC, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string prm_codPuntoVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string prm_codDeposito, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codGrupo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string prm_codRegCategoProd)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_codEmpresa, prm_codEmpresaRUC, prm_codPuntoVenta, prm_codDeposito, prm_codGrupo, prm_codRegCategoProd);
			return ((ISingleResult<omgc_R_ProductoInventarioActualResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.omgc_R_ProductoMovimientoVentasCompras")]
		public ISingleResult<omgc_R_ProductoMovimientoVentasComprasResult> omgc_R_ProductoMovimientoVentasCompras([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string prm_CodigoPuntoVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string prm_codDeposito, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string prm_CodigoArguDestinoComp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaProcesoINI, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaProcesoFIN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_codEmpresa, prm_CodigoPuntoVenta, prm_codDeposito, prm_codProducto, prm_CodigoArguDestinoComp, prm_FechaProcesoINI, prm_FechaProcesoFIN);
			return ((ISingleResult<omgc_R_ProductoMovimientoVentasComprasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.omgc_R_ProductosPorEntidadesVentasCompras")]
		public ISingleResult<omgc_R_ProductosPorEntidadesVentasComprasResult> omgc_R_ProductosPorEntidadesVentasCompras([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaDeEmisionINI, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaDeEmisionFIN, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string prm_CodigoPuntoVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string prm_CodigoPersonaEntidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string prm_CodigoArguDestinoComp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codproducto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_codEmpresa, prm_FechaDeEmisionINI, prm_FechaDeEmisionFIN, prm_CodigoPuntoVenta, prm_CodigoPersonaEntidad, prm_CodigoArguDestinoComp, prm_codproducto);
			return ((ISingleResult<omgc_R_ProductosPorEntidadesVentasComprasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.omgc_R_RecordDeVentasCompras")]
		public ISingleResult<omgc_R_RecordDeVentasComprasResult> omgc_R_RecordDeVentasCompras([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaInicio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaFinal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string prm_CodigoPuntoVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string prm_CodigoComprobante, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string prm_CodigoPersonaEntidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string prm_CodigoArguDestinoComp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_NumeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_codEmpresa, prm_FechaInicio, prm_FechaFinal, prm_CodigoPuntoVenta, prm_CodigoComprobante, prm_CodigoPersonaEntidad, prm_codEmpleado, prm_CodigoArguDestinoComp, prm_NumeroRegistros);
			return ((ISingleResult<omgc_R_RecordDeVentasComprasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.omgc_R_RegistroDeVentasCompras")]
		public ISingleResult<omgc_R_RegistroDeVentasComprasResult> omgc_R_RegistroDeVentasCompras([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaInicio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaFinal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string prm_CodigoPuntoVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string prm_CodigoComprobante, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string prm_CodigoPersonaEntidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpleadoVend, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string prm_CodigoArguDestinoComp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_codEmpresa, prm_FechaInicio, prm_FechaFinal, prm_CodigoPuntoVenta, prm_CodigoComprobante, prm_CodigoPersonaEntidad, prm_codEmpleado, prm_codEmpleadoVend, prm_CodigoArguDestinoComp);
			return ((ISingleResult<omgc_R_RegistroDeVentasComprasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="GestionComercial.omgc_R_RegistroDeVentasComprasContab")]
		public ISingleResult<omgc_R_RegistroDeVentasComprasContabResult> omgc_R_RegistroDeVentasComprasContab([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaInicio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string prm_FechaFinal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string prm_CodigoPuntoVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string prm_CodigoComprobante, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string prm_CodigoPersonaEntidad, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prm_codEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string prm_CodigoArguDestinoComp)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), prm_codEmpresa, prm_FechaInicio, prm_FechaFinal, prm_CodigoPuntoVenta, prm_CodigoComprobante, prm_CodigoPersonaEntidad, prm_codEmpleado, prm_CodigoArguDestinoComp);
			return ((ISingleResult<omgc_R_RegistroDeVentasComprasContabResult>)(result.ReturnValue));
		}
	}
	
	public partial class omgc_R_DocumRegEnAniosVentasComprasResult
	{
		
		private System.Nullable<int> _Años;
		
		private string _Meses;
		
		private System.Nullable<int> _Cantidad;
		
		private System.Nullable<decimal> _MontoNacional;
		
		private System.Nullable<decimal> _MontoExtranje;
		
		private System.Nullable<decimal> _TipoCambio;
		
		private System.Nullable<int> _ItemMes;
		
		private string _CodigoArguTipoDeOperacion;
		
		private string _CodigoArguTipoDeOperacionNombre;
		
		public omgc_R_DocumRegEnAniosVentasComprasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Años", DbType="Int")]
		public System.Nullable<int> Años
		{
			get
			{
				return this._Años;
			}
			set
			{
				if ((this._Años != value))
				{
					this._Años = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Meses", DbType="NVarChar(30)")]
		public string Meses
		{
			get
			{
				return this._Meses;
			}
			set
			{
				if ((this._Meses != value))
				{
					this._Meses = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoNacional", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoNacional
		{
			get
			{
				return this._MontoNacional;
			}
			set
			{
				if ((this._MontoNacional != value))
				{
					this._MontoNacional = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoExtranje", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoExtranje
		{
			get
			{
				return this._MontoExtranje;
			}
			set
			{
				if ((this._MontoExtranje != value))
				{
					this._MontoExtranje = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoCambio", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> TipoCambio
		{
			get
			{
				return this._TipoCambio;
			}
			set
			{
				if ((this._TipoCambio != value))
				{
					this._TipoCambio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemMes", DbType="Int")]
		public System.Nullable<int> ItemMes
		{
			get
			{
				return this._ItemMes;
			}
			set
			{
				if ((this._ItemMes != value))
				{
					this._ItemMes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguTipoDeOperacion", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CodigoArguTipoDeOperacion
		{
			get
			{
				return this._CodigoArguTipoDeOperacion;
			}
			set
			{
				if ((this._CodigoArguTipoDeOperacion != value))
				{
					this._CodigoArguTipoDeOperacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguTipoDeOperacionNombre", DbType="VarChar(100)")]
		public string CodigoArguTipoDeOperacionNombre
		{
			get
			{
				return this._CodigoArguTipoDeOperacionNombre;
			}
			set
			{
				if ((this._CodigoArguTipoDeOperacionNombre != value))
				{
					this._CodigoArguTipoDeOperacionNombre = value;
				}
			}
		}
	}
	
	public partial class omgc_R_RegistroDeVentasComprasDetalladoResult
	{
		
		private int _codEmpresa;
		
		private string _CodigoPuntoVenta;
		
		private System.Nullable<System.DateTime> _FechaDeEmision;
		
		private string _NumeroComprobante;
		
		private string _CodigoPersonaEntidad;
		
		private string _EntidadNumeroRUC;
		
		private string _EntidadRazonSocial;
		
		private string _EntidadDireccionUbigeo;
		
		private int _codProducto;
		
		private string _CodigoProducto;
		
		private string _Descripcion;
		
		private decimal _Cantidad;
		
		private decimal _UnitValorVenta;
		
		private decimal _TotItemValorVenta;
		
		private decimal _TotItemValorIGV;
		
		private System.Nullable<decimal> _TotItemValorBruto;
		
		private string _CodigoArguEstadoDocu;
		
		private string _CodigoArguEstadoDocuNombre;
		
		private string _CodigoArguMoneda;
		
		private string _CodigoArguMonedaNombre;
		
		private decimal _ValorTipoCambio;
		
		private string _auxCodigoPersonaEntidadEmpleado;
		
		private string _auxCodigoPersonaEntidadVendedor;
		
		private int _codEmpleadoVendedor;
		
		private string _nomVendedor;
		
		private string _nomUnidadMedida;
		
		public omgc_R_RegistroDeVentasComprasDetalladoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpresa", DbType="Int NOT NULL")]
		public int codEmpresa
		{
			get
			{
				return this._codEmpresa;
			}
			set
			{
				if ((this._codEmpresa != value))
				{
					this._codEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPuntoVenta", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string CodigoPuntoVenta
		{
			get
			{
				return this._CodigoPuntoVenta;
			}
			set
			{
				if ((this._CodigoPuntoVenta != value))
				{
					this._CodigoPuntoVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDeEmision", DbType="Date")]
		public System.Nullable<System.DateTime> FechaDeEmision
		{
			get
			{
				return this._FechaDeEmision;
			}
			set
			{
				if ((this._FechaDeEmision != value))
				{
					this._FechaDeEmision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroComprobante", DbType="VarChar(21)")]
		public string NumeroComprobante
		{
			get
			{
				return this._NumeroComprobante;
			}
			set
			{
				if ((this._NumeroComprobante != value))
				{
					this._NumeroComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPersonaEntidad", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string CodigoPersonaEntidad
		{
			get
			{
				return this._CodigoPersonaEntidad;
			}
			set
			{
				if ((this._CodigoPersonaEntidad != value))
				{
					this._CodigoPersonaEntidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntidadNumeroRUC", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string EntidadNumeroRUC
		{
			get
			{
				return this._EntidadNumeroRUC;
			}
			set
			{
				if ((this._EntidadNumeroRUC != value))
				{
					this._EntidadNumeroRUC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntidadRazonSocial", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string EntidadRazonSocial
		{
			get
			{
				return this._EntidadRazonSocial;
			}
			set
			{
				if ((this._EntidadRazonSocial != value))
				{
					this._EntidadRazonSocial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntidadDireccionUbigeo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EntidadDireccionUbigeo
		{
			get
			{
				return this._EntidadDireccionUbigeo;
			}
			set
			{
				if ((this._EntidadDireccionUbigeo != value))
				{
					this._EntidadDireccionUbigeo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProducto", DbType="Int NOT NULL")]
		public int codProducto
		{
			get
			{
				return this._codProducto;
			}
			set
			{
				if ((this._codProducto != value))
				{
					this._codProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoProducto", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodigoProducto
		{
			get
			{
				return this._CodigoProducto;
			}
			set
			{
				if ((this._CodigoProducto != value))
				{
					this._CodigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Decimal(16,4) NOT NULL")]
		public decimal Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitValorVenta", DbType="Decimal(16,6) NOT NULL")]
		public decimal UnitValorVenta
		{
			get
			{
				return this._UnitValorVenta;
			}
			set
			{
				if ((this._UnitValorVenta != value))
				{
					this._UnitValorVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotItemValorVenta", DbType="Decimal(14,2) NOT NULL")]
		public decimal TotItemValorVenta
		{
			get
			{
				return this._TotItemValorVenta;
			}
			set
			{
				if ((this._TotItemValorVenta != value))
				{
					this._TotItemValorVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotItemValorIGV", DbType="Decimal(14,2) NOT NULL")]
		public decimal TotItemValorIGV
		{
			get
			{
				return this._TotItemValorIGV;
			}
			set
			{
				if ((this._TotItemValorIGV != value))
				{
					this._TotItemValorIGV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotItemValorBruto", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> TotItemValorBruto
		{
			get
			{
				return this._TotItemValorBruto;
			}
			set
			{
				if ((this._TotItemValorBruto != value))
				{
					this._TotItemValorBruto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguEstadoDocu", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CodigoArguEstadoDocu
		{
			get
			{
				return this._CodigoArguEstadoDocu;
			}
			set
			{
				if ((this._CodigoArguEstadoDocu != value))
				{
					this._CodigoArguEstadoDocu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguEstadoDocuNombre", DbType="VarChar(100)")]
		public string CodigoArguEstadoDocuNombre
		{
			get
			{
				return this._CodigoArguEstadoDocuNombre;
			}
			set
			{
				if ((this._CodigoArguEstadoDocuNombre != value))
				{
					this._CodigoArguEstadoDocuNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguMoneda", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CodigoArguMoneda
		{
			get
			{
				return this._CodigoArguMoneda;
			}
			set
			{
				if ((this._CodigoArguMoneda != value))
				{
					this._CodigoArguMoneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguMonedaNombre", DbType="VarChar(100)")]
		public string CodigoArguMonedaNombre
		{
			get
			{
				return this._CodigoArguMonedaNombre;
			}
			set
			{
				if ((this._CodigoArguMonedaNombre != value))
				{
					this._CodigoArguMonedaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTipoCambio", DbType="Decimal(6,4) NOT NULL")]
		public decimal ValorTipoCambio
		{
			get
			{
				return this._ValorTipoCambio;
			}
			set
			{
				if ((this._ValorTipoCambio != value))
				{
					this._ValorTipoCambio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auxCodigoPersonaEntidadEmpleado", DbType="VarChar(100)")]
		public string auxCodigoPersonaEntidadEmpleado
		{
			get
			{
				return this._auxCodigoPersonaEntidadEmpleado;
			}
			set
			{
				if ((this._auxCodigoPersonaEntidadEmpleado != value))
				{
					this._auxCodigoPersonaEntidadEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auxCodigoPersonaEntidadVendedor", DbType="VarChar(100)")]
		public string auxCodigoPersonaEntidadVendedor
		{
			get
			{
				return this._auxCodigoPersonaEntidadVendedor;
			}
			set
			{
				if ((this._auxCodigoPersonaEntidadVendedor != value))
				{
					this._auxCodigoPersonaEntidadVendedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleadoVendedor", DbType="Int NOT NULL")]
		public int codEmpleadoVendedor
		{
			get
			{
				return this._codEmpleadoVendedor;
			}
			set
			{
				if ((this._codEmpleadoVendedor != value))
				{
					this._codEmpleadoVendedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomVendedor", DbType="VarChar(100)")]
		public string nomVendedor
		{
			get
			{
				return this._nomVendedor;
			}
			set
			{
				if ((this._nomVendedor != value))
				{
					this._nomVendedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomUnidadMedida", DbType="VarChar(100)")]
		public string nomUnidadMedida
		{
			get
			{
				return this._nomUnidadMedida;
			}
			set
			{
				if ((this._nomUnidadMedida != value))
				{
					this._nomUnidadMedida = value;
				}
			}
		}
	}
	
	public partial class omgc_R_DocumRegVentasComprasContabMensualResult
	{
		
		private System.Nullable<int> _FechaDeEmisionANIO;
		
		private System.Nullable<int> _FechaDeEmisionMES;
		
		private System.Nullable<decimal> _ValorTotalVenta;
		
		private System.Nullable<decimal> _ValorTotalImpuesto;
		
		private System.Nullable<decimal> _ValorTotalPrecioVenta;
		
		public omgc_R_DocumRegVentasComprasContabMensualResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDeEmisionANIO", DbType="Int")]
		public System.Nullable<int> FechaDeEmisionANIO
		{
			get
			{
				return this._FechaDeEmisionANIO;
			}
			set
			{
				if ((this._FechaDeEmisionANIO != value))
				{
					this._FechaDeEmisionANIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDeEmisionMES", DbType="Int")]
		public System.Nullable<int> FechaDeEmisionMES
		{
			get
			{
				return this._FechaDeEmisionMES;
			}
			set
			{
				if ((this._FechaDeEmisionMES != value))
				{
					this._FechaDeEmisionMES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTotalVenta", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> ValorTotalVenta
		{
			get
			{
				return this._ValorTotalVenta;
			}
			set
			{
				if ((this._ValorTotalVenta != value))
				{
					this._ValorTotalVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTotalImpuesto", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> ValorTotalImpuesto
		{
			get
			{
				return this._ValorTotalImpuesto;
			}
			set
			{
				if ((this._ValorTotalImpuesto != value))
				{
					this._ValorTotalImpuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTotalPrecioVenta", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> ValorTotalPrecioVenta
		{
			get
			{
				return this._ValorTotalPrecioVenta;
			}
			set
			{
				if ((this._ValorTotalPrecioVenta != value))
				{
					this._ValorTotalPrecioVenta = value;
				}
			}
		}
	}
	
	public partial class omgc_R_PorEntidadesProductoVentasComprasResult
	{
		
		private System.Nullable<System.DateTime> _FechaDeEmision;
		
		private System.Nullable<int> _codProducto;
		
		private string _CodigoProducto;
		
		private System.Nullable<decimal> _Cantidad;
		
		private System.Nullable<decimal> _UnitValorVenta;
		
		private System.Nullable<decimal> _TotItemValorVenta;
		
		private string _CodigoArguMoneda;
		
		private string _CodigoArguMonedaNombre;
		
		private System.Nullable<decimal> _MonedaExtranjera;
		
		private System.Nullable<decimal> _ValorTipoCambioVTA;
		
		private string _Descripcion;
		
		private string _NumeroComprobante;
		
		private string _SegUsuarioEdita;
		
		public omgc_R_PorEntidadesProductoVentasComprasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDeEmision", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaDeEmision
		{
			get
			{
				return this._FechaDeEmision;
			}
			set
			{
				if ((this._FechaDeEmision != value))
				{
					this._FechaDeEmision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProducto", DbType="Int")]
		public System.Nullable<int> codProducto
		{
			get
			{
				return this._codProducto;
			}
			set
			{
				if ((this._codProducto != value))
				{
					this._codProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoProducto", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodigoProducto
		{
			get
			{
				return this._CodigoProducto;
			}
			set
			{
				if ((this._CodigoProducto != value))
				{
					this._CodigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Decimal(16,4)")]
		public System.Nullable<decimal> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitValorVenta", DbType="Decimal(16,6)")]
		public System.Nullable<decimal> UnitValorVenta
		{
			get
			{
				return this._UnitValorVenta;
			}
			set
			{
				if ((this._UnitValorVenta != value))
				{
					this._UnitValorVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotItemValorVenta", DbType="Decimal(14,2)")]
		public System.Nullable<decimal> TotItemValorVenta
		{
			get
			{
				return this._TotItemValorVenta;
			}
			set
			{
				if ((this._TotItemValorVenta != value))
				{
					this._TotItemValorVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguMoneda", DbType="VarChar(17)")]
		public string CodigoArguMoneda
		{
			get
			{
				return this._CodigoArguMoneda;
			}
			set
			{
				if ((this._CodigoArguMoneda != value))
				{
					this._CodigoArguMoneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguMonedaNombre", DbType="VarChar(100)")]
		public string CodigoArguMonedaNombre
		{
			get
			{
				return this._CodigoArguMonedaNombre;
			}
			set
			{
				if ((this._CodigoArguMonedaNombre != value))
				{
					this._CodigoArguMonedaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonedaExtranjera", DbType="Decimal(25,9)")]
		public System.Nullable<decimal> MonedaExtranjera
		{
			get
			{
				return this._MonedaExtranjera;
			}
			set
			{
				if ((this._MonedaExtranjera != value))
				{
					this._MonedaExtranjera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTipoCambioVTA", DbType="Decimal(6,4)")]
		public System.Nullable<decimal> ValorTipoCambioVTA
		{
			get
			{
				return this._ValorTipoCambioVTA;
			}
			set
			{
				if ((this._ValorTipoCambioVTA != value))
				{
					this._ValorTipoCambioVTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(40)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroComprobante", DbType="VarChar(16)")]
		public string NumeroComprobante
		{
			get
			{
				return this._NumeroComprobante;
			}
			set
			{
				if ((this._NumeroComprobante != value))
				{
					this._NumeroComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegUsuarioEdita", DbType="VarChar(25)")]
		public string SegUsuarioEdita
		{
			get
			{
				return this._SegUsuarioEdita;
			}
			set
			{
				if ((this._SegUsuarioEdita != value))
				{
					this._SegUsuarioEdita = value;
				}
			}
		}
	}
	
	public partial class omgc_R_PorProductoEnAniosVentasComprasResult
	{
		
		private int _codProducto;
		
		private string _codigoProducto;
		
		private string _Descripcion;
		
		private System.Nullable<int> _Años;
		
		private string _Meses;
		
		private System.Nullable<decimal> _Cantidad;
		
		private System.Nullable<decimal> _MontoNacional;
		
		private System.Nullable<decimal> _MontoExtranje;
		
		private System.Nullable<decimal> _TipoCambio;
		
		private System.Nullable<int> _ItemMes;
		
		private string _CodigoArguTipoDeOperacion;
		
		private string _CodigoArguTipoDeOperacionNombre;
		
		public omgc_R_PorProductoEnAniosVentasComprasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProducto", DbType="Int NOT NULL")]
		public int codProducto
		{
			get
			{
				return this._codProducto;
			}
			set
			{
				if ((this._codProducto != value))
				{
					this._codProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProducto", DbType="VarChar(20)")]
		public string codigoProducto
		{
			get
			{
				return this._codigoProducto;
			}
			set
			{
				if ((this._codigoProducto != value))
				{
					this._codigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Años", DbType="Int")]
		public System.Nullable<int> Años
		{
			get
			{
				return this._Años;
			}
			set
			{
				if ((this._Años != value))
				{
					this._Años = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Meses", DbType="NVarChar(30)")]
		public string Meses
		{
			get
			{
				return this._Meses;
			}
			set
			{
				if ((this._Meses != value))
				{
					this._Meses = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Decimal(38,4)")]
		public System.Nullable<decimal> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoNacional", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> MontoNacional
		{
			get
			{
				return this._MontoNacional;
			}
			set
			{
				if ((this._MontoNacional != value))
				{
					this._MontoNacional = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoExtranje", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> MontoExtranje
		{
			get
			{
				return this._MontoExtranje;
			}
			set
			{
				if ((this._MontoExtranje != value))
				{
					this._MontoExtranje = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoCambio", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> TipoCambio
		{
			get
			{
				return this._TipoCambio;
			}
			set
			{
				if ((this._TipoCambio != value))
				{
					this._TipoCambio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemMes", DbType="Int")]
		public System.Nullable<int> ItemMes
		{
			get
			{
				return this._ItemMes;
			}
			set
			{
				if ((this._ItemMes != value))
				{
					this._ItemMes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguTipoDeOperacion", DbType="VarChar(17)")]
		public string CodigoArguTipoDeOperacion
		{
			get
			{
				return this._CodigoArguTipoDeOperacion;
			}
			set
			{
				if ((this._CodigoArguTipoDeOperacion != value))
				{
					this._CodigoArguTipoDeOperacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguTipoDeOperacionNombre", DbType="VarChar(100)")]
		public string CodigoArguTipoDeOperacionNombre
		{
			get
			{
				return this._CodigoArguTipoDeOperacionNombre;
			}
			set
			{
				if ((this._CodigoArguTipoDeOperacionNombre != value))
				{
					this._CodigoArguTipoDeOperacionNombre = value;
				}
			}
		}
	}
	
	public partial class omgc_R_Producto_ConsignacionResult
	{
		
		private int _codDocumReg;
		
		private string _codCliente;
		
		private string _nomRazonSocial;
		
		private System.DateTime _fecConsignacion;
		
		private string _numGuiaRemision;
		
		private string _CodigoProducto;
		
		private int _codProducto;
		
		private string _nomDescripcion;
		
		private decimal _cntStockMovimi;
		
		private string _numSerie;
		
		private string _numLote;
		
		private string _SegUsuarioCrea;
		
		private string _SegUsuarioEdita;
		
		public omgc_R_Producto_ConsignacionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDocumReg", DbType="Int NOT NULL")]
		public int codDocumReg
		{
			get
			{
				return this._codDocumReg;
			}
			set
			{
				if ((this._codDocumReg != value))
				{
					this._codDocumReg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCliente", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string codCliente
		{
			get
			{
				return this._codCliente;
			}
			set
			{
				if ((this._codCliente != value))
				{
					this._codCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomRazonSocial", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string nomRazonSocial
		{
			get
			{
				return this._nomRazonSocial;
			}
			set
			{
				if ((this._nomRazonSocial != value))
				{
					this._nomRazonSocial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecConsignacion", DbType="DateTime NOT NULL")]
		public System.DateTime fecConsignacion
		{
			get
			{
				return this._fecConsignacion;
			}
			set
			{
				if ((this._fecConsignacion != value))
				{
					this._fecConsignacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numGuiaRemision", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string numGuiaRemision
		{
			get
			{
				return this._numGuiaRemision;
			}
			set
			{
				if ((this._numGuiaRemision != value))
				{
					this._numGuiaRemision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoProducto", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodigoProducto
		{
			get
			{
				return this._CodigoProducto;
			}
			set
			{
				if ((this._CodigoProducto != value))
				{
					this._CodigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProducto", DbType="Int NOT NULL")]
		public int codProducto
		{
			get
			{
				return this._codProducto;
			}
			set
			{
				if ((this._codProducto != value))
				{
					this._codProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomDescripcion", DbType="VarChar(350) NOT NULL", CanBeNull=false)]
		public string nomDescripcion
		{
			get
			{
				return this._nomDescripcion;
			}
			set
			{
				if ((this._nomDescripcion != value))
				{
					this._nomDescripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntStockMovimi", DbType="Decimal(16,4) NOT NULL")]
		public decimal cntStockMovimi
		{
			get
			{
				return this._cntStockMovimi;
			}
			set
			{
				if ((this._cntStockMovimi != value))
				{
					this._cntStockMovimi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numSerie", DbType="VarChar(40)")]
		public string numSerie
		{
			get
			{
				return this._numSerie;
			}
			set
			{
				if ((this._numSerie != value))
				{
					this._numSerie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numLote", DbType="VarChar(50)")]
		public string numLote
		{
			get
			{
				return this._numLote;
			}
			set
			{
				if ((this._numLote != value))
				{
					this._numLote = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegUsuarioCrea", DbType="VarChar(30)")]
		public string SegUsuarioCrea
		{
			get
			{
				return this._SegUsuarioCrea;
			}
			set
			{
				if ((this._SegUsuarioCrea != value))
				{
					this._SegUsuarioCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegUsuarioEdita", DbType="VarChar(25)")]
		public string SegUsuarioEdita
		{
			get
			{
				return this._SegUsuarioEdita;
			}
			set
			{
				if ((this._SegUsuarioEdita != value))
				{
					this._SegUsuarioEdita = value;
				}
			}
		}
	}
	
	public partial class omgc_R_ProductoInventarioResult
	{
		
		private string _Periodo;
		
		private string _CodigoPersonaEmpre;
		
		private string _CodigoPuntoVenta;
		
		private string _codDeposito;
		
		private string _codDepositoNombre;
		
		private int _codProducto;
		
		private string _CodigoProducto;
		
		private string _CodigoProductoNombre;
		
		private System.Nullable<decimal> _StockMinimo;
		
		private System.Nullable<decimal> _StockMaximo;
		
		private decimal _StockInicial;
		
		private decimal _StockFisico;
		
		private decimal _StoskComprometido;
		
		private decimal _Conteo01;
		
		private decimal _Conteo02;
		
		private decimal _Conteo03;
		
		private decimal _Conteo04;
		
		private System.Nullable<System.DateTime> _SegFechaEdita;
		
		private string _SegUsuarioEdita;
		
		private string _desAgrupacion;
		
		public omgc_R_ProductoInventarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Periodo", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string Periodo
		{
			get
			{
				return this._Periodo;
			}
			set
			{
				if ((this._Periodo != value))
				{
					this._Periodo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPersonaEmpre", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string CodigoPersonaEmpre
		{
			get
			{
				return this._CodigoPersonaEmpre;
			}
			set
			{
				if ((this._CodigoPersonaEmpre != value))
				{
					this._CodigoPersonaEmpre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPuntoVenta", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string CodigoPuntoVenta
		{
			get
			{
				return this._CodigoPuntoVenta;
			}
			set
			{
				if ((this._CodigoPuntoVenta != value))
				{
					this._CodigoPuntoVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDeposito", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string codDeposito
		{
			get
			{
				return this._codDeposito;
			}
			set
			{
				if ((this._codDeposito != value))
				{
					this._codDeposito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDepositoNombre", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string codDepositoNombre
		{
			get
			{
				return this._codDepositoNombre;
			}
			set
			{
				if ((this._codDepositoNombre != value))
				{
					this._codDepositoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProducto", DbType="Int NOT NULL")]
		public int codProducto
		{
			get
			{
				return this._codProducto;
			}
			set
			{
				if ((this._codProducto != value))
				{
					this._codProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoProducto", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodigoProducto
		{
			get
			{
				return this._CodigoProducto;
			}
			set
			{
				if ((this._CodigoProducto != value))
				{
					this._CodigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoProductoNombre", DbType="VarChar(106)")]
		public string CodigoProductoNombre
		{
			get
			{
				return this._CodigoProductoNombre;
			}
			set
			{
				if ((this._CodigoProductoNombre != value))
				{
					this._CodigoProductoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockMinimo", DbType="Decimal(15,3)")]
		public System.Nullable<decimal> StockMinimo
		{
			get
			{
				return this._StockMinimo;
			}
			set
			{
				if ((this._StockMinimo != value))
				{
					this._StockMinimo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockMaximo", DbType="Decimal(15,3)")]
		public System.Nullable<decimal> StockMaximo
		{
			get
			{
				return this._StockMaximo;
			}
			set
			{
				if ((this._StockMaximo != value))
				{
					this._StockMaximo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockInicial", DbType="Decimal(16,4) NOT NULL")]
		public decimal StockInicial
		{
			get
			{
				return this._StockInicial;
			}
			set
			{
				if ((this._StockInicial != value))
				{
					this._StockInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockFisico", DbType="Decimal(16,4) NOT NULL")]
		public decimal StockFisico
		{
			get
			{
				return this._StockFisico;
			}
			set
			{
				if ((this._StockFisico != value))
				{
					this._StockFisico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoskComprometido", DbType="Decimal(10,3) NOT NULL")]
		public decimal StoskComprometido
		{
			get
			{
				return this._StoskComprometido;
			}
			set
			{
				if ((this._StoskComprometido != value))
				{
					this._StoskComprometido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Conteo01", DbType="Decimal(10,3) NOT NULL")]
		public decimal Conteo01
		{
			get
			{
				return this._Conteo01;
			}
			set
			{
				if ((this._Conteo01 != value))
				{
					this._Conteo01 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Conteo02", DbType="Decimal(10,3) NOT NULL")]
		public decimal Conteo02
		{
			get
			{
				return this._Conteo02;
			}
			set
			{
				if ((this._Conteo02 != value))
				{
					this._Conteo02 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Conteo03", DbType="Decimal(10,3) NOT NULL")]
		public decimal Conteo03
		{
			get
			{
				return this._Conteo03;
			}
			set
			{
				if ((this._Conteo03 != value))
				{
					this._Conteo03 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Conteo04", DbType="Decimal(10,3) NOT NULL")]
		public decimal Conteo04
		{
			get
			{
				return this._Conteo04;
			}
			set
			{
				if ((this._Conteo04 != value))
				{
					this._Conteo04 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegFechaEdita", DbType="DateTime")]
		public System.Nullable<System.DateTime> SegFechaEdita
		{
			get
			{
				return this._SegFechaEdita;
			}
			set
			{
				if ((this._SegFechaEdita != value))
				{
					this._SegFechaEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegUsuarioEdita", DbType="VarChar(25)")]
		public string SegUsuarioEdita
		{
			get
			{
				return this._SegUsuarioEdita;
			}
			set
			{
				if ((this._SegUsuarioEdita != value))
				{
					this._SegUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desAgrupacion", DbType="VarChar(5)")]
		public string desAgrupacion
		{
			get
			{
				return this._desAgrupacion;
			}
			set
			{
				if ((this._desAgrupacion != value))
				{
					this._desAgrupacion = value;
				}
			}
		}
	}
	
	public partial class omgc_R_ProductoInventarioActualResult
	{
		
		private string _CodigoPersonaEmpre;
		
		private string _CodigoPuntoVenta;
		
		private string _codDeposito;
		
		private string _codDepositoNombre;
		
		private int _codProducto;
		
		private string _CodigoProducto;
		
		private string _CodigoProductoNombre;
		
		private bool _EsConNumeroSeriado;
		
		private decimal _StockInicial;
		
		private decimal _StockFisico;
		
		private decimal _ValorCosto;
		
		private System.Nullable<decimal> _Total_Costo;
		
		private System.Nullable<decimal> _StockMinimo;
		
		private decimal _StoskComprometido;
		
		private System.Nullable<System.DateTime> _SegFechaEdita;
		
		private string _SegUsuarioEdita;
		
		private System.Nullable<int> _codProductoPrecio;
		
		private string _numOIDUA;
		
		private string _numOrdenImportacion;
		
		private string _codGrupoNombre;
		
		private string _codRegCategoriaNombre;
		
		public omgc_R_ProductoInventarioActualResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPersonaEmpre", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string CodigoPersonaEmpre
		{
			get
			{
				return this._CodigoPersonaEmpre;
			}
			set
			{
				if ((this._CodigoPersonaEmpre != value))
				{
					this._CodigoPersonaEmpre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPuntoVenta", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string CodigoPuntoVenta
		{
			get
			{
				return this._CodigoPuntoVenta;
			}
			set
			{
				if ((this._CodigoPuntoVenta != value))
				{
					this._CodigoPuntoVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDeposito", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string codDeposito
		{
			get
			{
				return this._codDeposito;
			}
			set
			{
				if ((this._codDeposito != value))
				{
					this._codDeposito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDepositoNombre", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string codDepositoNombre
		{
			get
			{
				return this._codDepositoNombre;
			}
			set
			{
				if ((this._codDepositoNombre != value))
				{
					this._codDepositoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProducto", DbType="Int NOT NULL")]
		public int codProducto
		{
			get
			{
				return this._codProducto;
			}
			set
			{
				if ((this._codProducto != value))
				{
					this._codProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoProducto", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodigoProducto
		{
			get
			{
				return this._CodigoProducto;
			}
			set
			{
				if ((this._CodigoProducto != value))
				{
					this._CodigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoProductoNombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string CodigoProductoNombre
		{
			get
			{
				return this._CodigoProductoNombre;
			}
			set
			{
				if ((this._CodigoProductoNombre != value))
				{
					this._CodigoProductoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EsConNumeroSeriado", DbType="Bit NOT NULL")]
		public bool EsConNumeroSeriado
		{
			get
			{
				return this._EsConNumeroSeriado;
			}
			set
			{
				if ((this._EsConNumeroSeriado != value))
				{
					this._EsConNumeroSeriado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockInicial", DbType="Decimal(16,4) NOT NULL")]
		public decimal StockInicial
		{
			get
			{
				return this._StockInicial;
			}
			set
			{
				if ((this._StockInicial != value))
				{
					this._StockInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockFisico", DbType="Decimal(16,4) NOT NULL")]
		public decimal StockFisico
		{
			get
			{
				return this._StockFisico;
			}
			set
			{
				if ((this._StockFisico != value))
				{
					this._StockFisico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorCosto", DbType="Decimal(18,5) NOT NULL")]
		public decimal ValorCosto
		{
			get
			{
				return this._ValorCosto;
			}
			set
			{
				if ((this._ValorCosto != value))
				{
					this._ValorCosto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Costo", DbType="Decimal(35,9)")]
		public System.Nullable<decimal> Total_Costo
		{
			get
			{
				return this._Total_Costo;
			}
			set
			{
				if ((this._Total_Costo != value))
				{
					this._Total_Costo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StockMinimo", DbType="Decimal(15,3)")]
		public System.Nullable<decimal> StockMinimo
		{
			get
			{
				return this._StockMinimo;
			}
			set
			{
				if ((this._StockMinimo != value))
				{
					this._StockMinimo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoskComprometido", DbType="Decimal(10,3) NOT NULL")]
		public decimal StoskComprometido
		{
			get
			{
				return this._StoskComprometido;
			}
			set
			{
				if ((this._StoskComprometido != value))
				{
					this._StoskComprometido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegFechaEdita", DbType="DateTime")]
		public System.Nullable<System.DateTime> SegFechaEdita
		{
			get
			{
				return this._SegFechaEdita;
			}
			set
			{
				if ((this._SegFechaEdita != value))
				{
					this._SegFechaEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegUsuarioEdita", DbType="VarChar(30)")]
		public string SegUsuarioEdita
		{
			get
			{
				return this._SegUsuarioEdita;
			}
			set
			{
				if ((this._SegUsuarioEdita != value))
				{
					this._SegUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProductoPrecio", DbType="Int")]
		public System.Nullable<int> codProductoPrecio
		{
			get
			{
				return this._codProductoPrecio;
			}
			set
			{
				if ((this._codProductoPrecio != value))
				{
					this._codProductoPrecio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numOIDUA", DbType="VarChar(30)")]
		public string numOIDUA
		{
			get
			{
				return this._numOIDUA;
			}
			set
			{
				if ((this._numOIDUA != value))
				{
					this._numOIDUA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numOrdenImportacion", DbType="VarChar(10)")]
		public string numOrdenImportacion
		{
			get
			{
				return this._numOrdenImportacion;
			}
			set
			{
				if ((this._numOrdenImportacion != value))
				{
					this._numOrdenImportacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codGrupoNombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string codGrupoNombre
		{
			get
			{
				return this._codGrupoNombre;
			}
			set
			{
				if ((this._codGrupoNombre != value))
				{
					this._codGrupoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegCategoriaNombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string codRegCategoriaNombre
		{
			get
			{
				return this._codRegCategoriaNombre;
			}
			set
			{
				if ((this._codRegCategoriaNombre != value))
				{
					this._codRegCategoriaNombre = value;
				}
			}
		}
	}
	
	public partial class omgc_R_ProductoMovimientoVentasComprasResult
	{
		
		private string _CodigoArguTipoDeOperacion;
		
		private string _CodigoArguTipoDeOperacionNombre;
		
		private int _codProducto;
		
		private string _codigoProducto;
		
		private System.Nullable<System.DateTime> _FechaDeEmision;
		
		private System.Nullable<decimal> _Cantidad;
		
		private decimal _UnitPrecioSinIGV;
		
		private decimal _UnitValorDscto;
		
		private decimal _UnitValorVenta;
		
		private decimal _UnitValorIGV;
		
		private decimal _TotItemValorVenta;
		
		private decimal _TotItemValorIGV;
		
		private System.Nullable<decimal> _UnitValorVentaMnInt;
		
		private System.Nullable<decimal> _UnitValorIGVMnInt;
		
		private System.Nullable<decimal> _TotItemValorVentaMnInt;
		
		private System.Nullable<decimal> _TotItemValorIGVMnInt;
		
		private System.Nullable<decimal> _TotItemValorVenta1;
		
		private string _CodigoArguMoneda;
		
		private string _CodigoArguMonedaNombre;
		
		private System.Nullable<decimal> _ValorTipoCambioVTA;
		
		private System.Nullable<decimal> _ValorTipoCambioCMP;
		
		private string _CodigoComprobante;
		
		private string _CodigoComprobanteNombre;
		
		private string _NumeroComprobante;
		
		private string _EntidadRazonSocial;
		
		private string _CodigoProductoNombre;
		
		public omgc_R_ProductoMovimientoVentasComprasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguTipoDeOperacion", DbType="VarChar(17)")]
		public string CodigoArguTipoDeOperacion
		{
			get
			{
				return this._CodigoArguTipoDeOperacion;
			}
			set
			{
				if ((this._CodigoArguTipoDeOperacion != value))
				{
					this._CodigoArguTipoDeOperacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguTipoDeOperacionNombre", DbType="VarChar(100)")]
		public string CodigoArguTipoDeOperacionNombre
		{
			get
			{
				return this._CodigoArguTipoDeOperacionNombre;
			}
			set
			{
				if ((this._CodigoArguTipoDeOperacionNombre != value))
				{
					this._CodigoArguTipoDeOperacionNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProducto", DbType="Int NOT NULL")]
		public int codProducto
		{
			get
			{
				return this._codProducto;
			}
			set
			{
				if ((this._codProducto != value))
				{
					this._codProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProducto", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string codigoProducto
		{
			get
			{
				return this._codigoProducto;
			}
			set
			{
				if ((this._codigoProducto != value))
				{
					this._codigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDeEmision", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaDeEmision
		{
			get
			{
				return this._FechaDeEmision;
			}
			set
			{
				if ((this._FechaDeEmision != value))
				{
					this._FechaDeEmision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Decimal(18,4)")]
		public System.Nullable<decimal> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitPrecioSinIGV", DbType="Decimal(16,6) NOT NULL")]
		public decimal UnitPrecioSinIGV
		{
			get
			{
				return this._UnitPrecioSinIGV;
			}
			set
			{
				if ((this._UnitPrecioSinIGV != value))
				{
					this._UnitPrecioSinIGV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitValorDscto", DbType="Decimal(16,6) NOT NULL")]
		public decimal UnitValorDscto
		{
			get
			{
				return this._UnitValorDscto;
			}
			set
			{
				if ((this._UnitValorDscto != value))
				{
					this._UnitValorDscto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitValorVenta", DbType="Decimal(16,6) NOT NULL")]
		public decimal UnitValorVenta
		{
			get
			{
				return this._UnitValorVenta;
			}
			set
			{
				if ((this._UnitValorVenta != value))
				{
					this._UnitValorVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitValorIGV", DbType="Decimal(16,6) NOT NULL")]
		public decimal UnitValorIGV
		{
			get
			{
				return this._UnitValorIGV;
			}
			set
			{
				if ((this._UnitValorIGV != value))
				{
					this._UnitValorIGV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotItemValorVenta", DbType="Decimal(14,2) NOT NULL")]
		public decimal TotItemValorVenta
		{
			get
			{
				return this._TotItemValorVenta;
			}
			set
			{
				if ((this._TotItemValorVenta != value))
				{
					this._TotItemValorVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotItemValorIGV", DbType="Decimal(14,2) NOT NULL")]
		public decimal TotItemValorIGV
		{
			get
			{
				return this._TotItemValorIGV;
			}
			set
			{
				if ((this._TotItemValorIGV != value))
				{
					this._TotItemValorIGV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitValorVentaMnInt", DbType="Decimal(27,13)")]
		public System.Nullable<decimal> UnitValorVentaMnInt
		{
			get
			{
				return this._UnitValorVentaMnInt;
			}
			set
			{
				if ((this._UnitValorVentaMnInt != value))
				{
					this._UnitValorVentaMnInt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitValorIGVMnInt", DbType="Decimal(27,13)")]
		public System.Nullable<decimal> UnitValorIGVMnInt
		{
			get
			{
				return this._UnitValorIGVMnInt;
			}
			set
			{
				if ((this._UnitValorIGVMnInt != value))
				{
					this._UnitValorIGVMnInt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotItemValorVentaMnInt", DbType="Decimal(25,9)")]
		public System.Nullable<decimal> TotItemValorVentaMnInt
		{
			get
			{
				return this._TotItemValorVentaMnInt;
			}
			set
			{
				if ((this._TotItemValorVentaMnInt != value))
				{
					this._TotItemValorVentaMnInt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotItemValorIGVMnInt", DbType="Decimal(25,9)")]
		public System.Nullable<decimal> TotItemValorIGVMnInt
		{
			get
			{
				return this._TotItemValorIGVMnInt;
			}
			set
			{
				if ((this._TotItemValorIGVMnInt != value))
				{
					this._TotItemValorIGVMnInt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotItemValorVenta1", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> TotItemValorVenta1
		{
			get
			{
				return this._TotItemValorVenta1;
			}
			set
			{
				if ((this._TotItemValorVenta1 != value))
				{
					this._TotItemValorVenta1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguMoneda", DbType="VarChar(17)")]
		public string CodigoArguMoneda
		{
			get
			{
				return this._CodigoArguMoneda;
			}
			set
			{
				if ((this._CodigoArguMoneda != value))
				{
					this._CodigoArguMoneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguMonedaNombre", DbType="VarChar(100)")]
		public string CodigoArguMonedaNombre
		{
			get
			{
				return this._CodigoArguMonedaNombre;
			}
			set
			{
				if ((this._CodigoArguMonedaNombre != value))
				{
					this._CodigoArguMonedaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTipoCambioVTA", DbType="Decimal(6,4)")]
		public System.Nullable<decimal> ValorTipoCambioVTA
		{
			get
			{
				return this._ValorTipoCambioVTA;
			}
			set
			{
				if ((this._ValorTipoCambioVTA != value))
				{
					this._ValorTipoCambioVTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTipoCambioCMP", DbType="Decimal(6,4)")]
		public System.Nullable<decimal> ValorTipoCambioCMP
		{
			get
			{
				return this._ValorTipoCambioCMP;
			}
			set
			{
				if ((this._ValorTipoCambioCMP != value))
				{
					this._ValorTipoCambioCMP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoComprobante", DbType="VarChar(3)")]
		public string CodigoComprobante
		{
			get
			{
				return this._CodigoComprobante;
			}
			set
			{
				if ((this._CodigoComprobante != value))
				{
					this._CodigoComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoComprobanteNombre", DbType="VarChar(50)")]
		public string CodigoComprobanteNombre
		{
			get
			{
				return this._CodigoComprobanteNombre;
			}
			set
			{
				if ((this._CodigoComprobanteNombre != value))
				{
					this._CodigoComprobanteNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroComprobante", DbType="VarChar(16)")]
		public string NumeroComprobante
		{
			get
			{
				return this._NumeroComprobante;
			}
			set
			{
				if ((this._NumeroComprobante != value))
				{
					this._NumeroComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntidadRazonSocial", DbType="VarChar(60)")]
		public string EntidadRazonSocial
		{
			get
			{
				return this._EntidadRazonSocial;
			}
			set
			{
				if ((this._EntidadRazonSocial != value))
				{
					this._EntidadRazonSocial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoProductoNombre", DbType="VarChar(40)")]
		public string CodigoProductoNombre
		{
			get
			{
				return this._CodigoProductoNombre;
			}
			set
			{
				if ((this._CodigoProductoNombre != value))
				{
					this._CodigoProductoNombre = value;
				}
			}
		}
	}
	
	public partial class omgc_R_ProductosPorEntidadesVentasComprasResult
	{
		
		private string _CodigoArguTipoDeOperacion;
		
		private string _CodigoArguTipoDeOperacionNombre;
		
		private System.Nullable<System.DateTime> _FechaDeEmision;
		
		private int _codProducto;
		
		private string _CodigoProducto;
		
		private decimal _Cantidad;
		
		private decimal _UnitValorVenta;
		
		private decimal _TotItemValorVenta;
		
		private System.Nullable<decimal> _TotItemValorVentaExtran;
		
		private string _CodigoArguMoneda;
		
		private string _CodigoArguMonedaNombre;
		
		private string _CodigoArguGarantiaProd;
		
		private string _CodigoArguGarantiaProdNombre;
		
		private System.Nullable<decimal> _ValorTipoCambio;
		
		private string _Descripción;
		
		private string _NumeroComprobante;
		
		private string _ref_CodigoPersonaEntidad;
		
		private string _ref_CodigoPersonaEntidadNombre;
		
		private bool _EsVerificarStock;
		
		private string _SegUsuarioCrea;
		
		private string _SegUsuarioEdita;
		
		private System.DateTime _SegFechaCrea;
		
		private System.Nullable<System.DateTime> _SegFechaEdita;
		
		private string _SegMaquina;
		
		private System.Nullable<decimal> _ValorTipoCambioVTA;
		
		private System.Nullable<decimal> _ValorTipoCambioCMP;
		
		public omgc_R_ProductosPorEntidadesVentasComprasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguTipoDeOperacion", DbType="VarChar(17)")]
		public string CodigoArguTipoDeOperacion
		{
			get
			{
				return this._CodigoArguTipoDeOperacion;
			}
			set
			{
				if ((this._CodigoArguTipoDeOperacion != value))
				{
					this._CodigoArguTipoDeOperacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguTipoDeOperacionNombre", DbType="VarChar(100)")]
		public string CodigoArguTipoDeOperacionNombre
		{
			get
			{
				return this._CodigoArguTipoDeOperacionNombre;
			}
			set
			{
				if ((this._CodigoArguTipoDeOperacionNombre != value))
				{
					this._CodigoArguTipoDeOperacionNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDeEmision", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaDeEmision
		{
			get
			{
				return this._FechaDeEmision;
			}
			set
			{
				if ((this._FechaDeEmision != value))
				{
					this._FechaDeEmision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProducto", DbType="Int NOT NULL")]
		public int codProducto
		{
			get
			{
				return this._codProducto;
			}
			set
			{
				if ((this._codProducto != value))
				{
					this._codProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoProducto", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CodigoProducto
		{
			get
			{
				return this._CodigoProducto;
			}
			set
			{
				if ((this._CodigoProducto != value))
				{
					this._CodigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Decimal(16,4) NOT NULL")]
		public decimal Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitValorVenta", DbType="Decimal(16,6) NOT NULL")]
		public decimal UnitValorVenta
		{
			get
			{
				return this._UnitValorVenta;
			}
			set
			{
				if ((this._UnitValorVenta != value))
				{
					this._UnitValorVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotItemValorVenta", DbType="Decimal(14,2) NOT NULL")]
		public decimal TotItemValorVenta
		{
			get
			{
				return this._TotItemValorVenta;
			}
			set
			{
				if ((this._TotItemValorVenta != value))
				{
					this._TotItemValorVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotItemValorVentaExtran", DbType="Decimal(30,12)")]
		public System.Nullable<decimal> TotItemValorVentaExtran
		{
			get
			{
				return this._TotItemValorVentaExtran;
			}
			set
			{
				if ((this._TotItemValorVentaExtran != value))
				{
					this._TotItemValorVentaExtran = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguMoneda", DbType="VarChar(17)")]
		public string CodigoArguMoneda
		{
			get
			{
				return this._CodigoArguMoneda;
			}
			set
			{
				if ((this._CodigoArguMoneda != value))
				{
					this._CodigoArguMoneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguMonedaNombre", DbType="VarChar(100)")]
		public string CodigoArguMonedaNombre
		{
			get
			{
				return this._CodigoArguMonedaNombre;
			}
			set
			{
				if ((this._CodigoArguMonedaNombre != value))
				{
					this._CodigoArguMonedaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguGarantiaProd", DbType="VarChar(17)")]
		public string CodigoArguGarantiaProd
		{
			get
			{
				return this._CodigoArguGarantiaProd;
			}
			set
			{
				if ((this._CodigoArguGarantiaProd != value))
				{
					this._CodigoArguGarantiaProd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguGarantiaProdNombre", DbType="VarChar(100)")]
		public string CodigoArguGarantiaProdNombre
		{
			get
			{
				return this._CodigoArguGarantiaProdNombre;
			}
			set
			{
				if ((this._CodigoArguGarantiaProdNombre != value))
				{
					this._CodigoArguGarantiaProdNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTipoCambio", DbType="Decimal(9,6)")]
		public System.Nullable<decimal> ValorTipoCambio
		{
			get
			{
				return this._ValorTipoCambio;
			}
			set
			{
				if ((this._ValorTipoCambio != value))
				{
					this._ValorTipoCambio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripción", DbType="VarChar(40)")]
		public string Descripción
		{
			get
			{
				return this._Descripción;
			}
			set
			{
				if ((this._Descripción != value))
				{
					this._Descripción = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroComprobante", DbType="VarChar(16)")]
		public string NumeroComprobante
		{
			get
			{
				return this._NumeroComprobante;
			}
			set
			{
				if ((this._NumeroComprobante != value))
				{
					this._NumeroComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ref_CodigoPersonaEntidad", DbType="VarChar(15)")]
		public string ref_CodigoPersonaEntidad
		{
			get
			{
				return this._ref_CodigoPersonaEntidad;
			}
			set
			{
				if ((this._ref_CodigoPersonaEntidad != value))
				{
					this._ref_CodigoPersonaEntidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ref_CodigoPersonaEntidadNombre", DbType="VarChar(60)")]
		public string ref_CodigoPersonaEntidadNombre
		{
			get
			{
				return this._ref_CodigoPersonaEntidadNombre;
			}
			set
			{
				if ((this._ref_CodigoPersonaEntidadNombre != value))
				{
					this._ref_CodigoPersonaEntidadNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EsVerificarStock", DbType="Bit NOT NULL")]
		public bool EsVerificarStock
		{
			get
			{
				return this._EsVerificarStock;
			}
			set
			{
				if ((this._EsVerificarStock != value))
				{
					this._EsVerificarStock = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegUsuarioCrea", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string SegUsuarioCrea
		{
			get
			{
				return this._SegUsuarioCrea;
			}
			set
			{
				if ((this._SegUsuarioCrea != value))
				{
					this._SegUsuarioCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegUsuarioEdita", DbType="VarChar(25)")]
		public string SegUsuarioEdita
		{
			get
			{
				return this._SegUsuarioEdita;
			}
			set
			{
				if ((this._SegUsuarioEdita != value))
				{
					this._SegUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegFechaCrea", DbType="DateTime NOT NULL")]
		public System.DateTime SegFechaCrea
		{
			get
			{
				return this._SegFechaCrea;
			}
			set
			{
				if ((this._SegFechaCrea != value))
				{
					this._SegFechaCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegFechaEdita", DbType="DateTime")]
		public System.Nullable<System.DateTime> SegFechaEdita
		{
			get
			{
				return this._SegFechaEdita;
			}
			set
			{
				if ((this._SegFechaEdita != value))
				{
					this._SegFechaEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegMaquina", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string SegMaquina
		{
			get
			{
				return this._SegMaquina;
			}
			set
			{
				if ((this._SegMaquina != value))
				{
					this._SegMaquina = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTipoCambioVTA", DbType="Decimal(6,4)")]
		public System.Nullable<decimal> ValorTipoCambioVTA
		{
			get
			{
				return this._ValorTipoCambioVTA;
			}
			set
			{
				if ((this._ValorTipoCambioVTA != value))
				{
					this._ValorTipoCambioVTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTipoCambioCMP", DbType="Decimal(6,4)")]
		public System.Nullable<decimal> ValorTipoCambioCMP
		{
			get
			{
				return this._ValorTipoCambioCMP;
			}
			set
			{
				if ((this._ValorTipoCambioCMP != value))
				{
					this._ValorTipoCambioCMP = value;
				}
			}
		}
	}
	
	public partial class omgc_R_RecordDeVentasComprasResult
	{
		
		private string _CodigoPersonaEntidad;
		
		private string _EntidadRazonSocial;
		
		private System.Nullable<decimal> _ValorTotalPrecioExtran;
		
		private System.Nullable<decimal> _ValorTotalVenta;
		
		private System.Nullable<decimal> _ValorTotalImpuesto;
		
		private System.Nullable<decimal> _ValorTotalPrecioVenta;
		
		private decimal _ValorIGV;
		
		public omgc_R_RecordDeVentasComprasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPersonaEntidad", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string CodigoPersonaEntidad
		{
			get
			{
				return this._CodigoPersonaEntidad;
			}
			set
			{
				if ((this._CodigoPersonaEntidad != value))
				{
					this._CodigoPersonaEntidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntidadRazonSocial", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string EntidadRazonSocial
		{
			get
			{
				return this._EntidadRazonSocial;
			}
			set
			{
				if ((this._EntidadRazonSocial != value))
				{
					this._EntidadRazonSocial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTotalPrecioExtran", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> ValorTotalPrecioExtran
		{
			get
			{
				return this._ValorTotalPrecioExtran;
			}
			set
			{
				if ((this._ValorTotalPrecioExtran != value))
				{
					this._ValorTotalPrecioExtran = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTotalVenta", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> ValorTotalVenta
		{
			get
			{
				return this._ValorTotalVenta;
			}
			set
			{
				if ((this._ValorTotalVenta != value))
				{
					this._ValorTotalVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTotalImpuesto", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> ValorTotalImpuesto
		{
			get
			{
				return this._ValorTotalImpuesto;
			}
			set
			{
				if ((this._ValorTotalImpuesto != value))
				{
					this._ValorTotalImpuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTotalPrecioVenta", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> ValorTotalPrecioVenta
		{
			get
			{
				return this._ValorTotalPrecioVenta;
			}
			set
			{
				if ((this._ValorTotalPrecioVenta != value))
				{
					this._ValorTotalPrecioVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorIGV", DbType="Decimal(6,4) NOT NULL")]
		public decimal ValorIGV
		{
			get
			{
				return this._ValorIGV;
			}
			set
			{
				if ((this._ValorIGV != value))
				{
					this._ValorIGV = value;
				}
			}
		}
	}
	
	public partial class omgc_R_RegistroDeVentasComprasResult
	{
		
		private System.DateTime _FechaDeEmision;
		
		private string _NumeroComprobante;
		
		private string _CodigoPersonaEntidad;
		
		private string _EntidadNumeroRUC;
		
		private string _EntidadRazonSocial;
		
		private string _CodigoArguEstadoDocu;
		
		private string _CodigoArguEstadoDocuNombre;
		
		private string _CodigoArguMoneda;
		
		private string _CodigoArguMonedaNombre;
		
		private decimal _ValorTotalPrecioExtran;
		
		private System.Nullable<decimal> _ValorTotalVenta;
		
		private System.Nullable<decimal> _ValorTotalImpuesto;
		
		private System.Nullable<decimal> _ValorTotalPrecioVenta;
		
		private bool _DocEsGravado;
		
		private System.Nullable<decimal> _ValorDeImpuesto;
		
		private System.Nullable<decimal> _ValorTipoCambio;
		
		private System.Nullable<int> _codEmpleadoVendedor;
		
		private string _nomEmpleadoVendedor;
		
		public omgc_R_RegistroDeVentasComprasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDeEmision", DbType="DateTime NOT NULL")]
		public System.DateTime FechaDeEmision
		{
			get
			{
				return this._FechaDeEmision;
			}
			set
			{
				if ((this._FechaDeEmision != value))
				{
					this._FechaDeEmision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroComprobante", DbType="VarChar(16)")]
		public string NumeroComprobante
		{
			get
			{
				return this._NumeroComprobante;
			}
			set
			{
				if ((this._NumeroComprobante != value))
				{
					this._NumeroComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPersonaEntidad", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string CodigoPersonaEntidad
		{
			get
			{
				return this._CodigoPersonaEntidad;
			}
			set
			{
				if ((this._CodigoPersonaEntidad != value))
				{
					this._CodigoPersonaEntidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntidadNumeroRUC", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string EntidadNumeroRUC
		{
			get
			{
				return this._EntidadNumeroRUC;
			}
			set
			{
				if ((this._EntidadNumeroRUC != value))
				{
					this._EntidadNumeroRUC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntidadRazonSocial", DbType="VarChar(35)")]
		public string EntidadRazonSocial
		{
			get
			{
				return this._EntidadRazonSocial;
			}
			set
			{
				if ((this._EntidadRazonSocial != value))
				{
					this._EntidadRazonSocial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguEstadoDocu", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CodigoArguEstadoDocu
		{
			get
			{
				return this._CodigoArguEstadoDocu;
			}
			set
			{
				if ((this._CodigoArguEstadoDocu != value))
				{
					this._CodigoArguEstadoDocu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguEstadoDocuNombre", DbType="VarChar(100)")]
		public string CodigoArguEstadoDocuNombre
		{
			get
			{
				return this._CodigoArguEstadoDocuNombre;
			}
			set
			{
				if ((this._CodigoArguEstadoDocuNombre != value))
				{
					this._CodigoArguEstadoDocuNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguMoneda", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CodigoArguMoneda
		{
			get
			{
				return this._CodigoArguMoneda;
			}
			set
			{
				if ((this._CodigoArguMoneda != value))
				{
					this._CodigoArguMoneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguMonedaNombre", DbType="VarChar(100)")]
		public string CodigoArguMonedaNombre
		{
			get
			{
				return this._CodigoArguMonedaNombre;
			}
			set
			{
				if ((this._CodigoArguMonedaNombre != value))
				{
					this._CodigoArguMonedaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTotalPrecioExtran", DbType="Decimal(12,2) NOT NULL")]
		public decimal ValorTotalPrecioExtran
		{
			get
			{
				return this._ValorTotalPrecioExtran;
			}
			set
			{
				if ((this._ValorTotalPrecioExtran != value))
				{
					this._ValorTotalPrecioExtran = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTotalVenta", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ValorTotalVenta
		{
			get
			{
				return this._ValorTotalVenta;
			}
			set
			{
				if ((this._ValorTotalVenta != value))
				{
					this._ValorTotalVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTotalImpuesto", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ValorTotalImpuesto
		{
			get
			{
				return this._ValorTotalImpuesto;
			}
			set
			{
				if ((this._ValorTotalImpuesto != value))
				{
					this._ValorTotalImpuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTotalPrecioVenta", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ValorTotalPrecioVenta
		{
			get
			{
				return this._ValorTotalPrecioVenta;
			}
			set
			{
				if ((this._ValorTotalPrecioVenta != value))
				{
					this._ValorTotalPrecioVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocEsGravado", DbType="Bit NOT NULL")]
		public bool DocEsGravado
		{
			get
			{
				return this._DocEsGravado;
			}
			set
			{
				if ((this._DocEsGravado != value))
				{
					this._DocEsGravado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorDeImpuesto", DbType="Decimal(6,4)")]
		public System.Nullable<decimal> ValorDeImpuesto
		{
			get
			{
				return this._ValorDeImpuesto;
			}
			set
			{
				if ((this._ValorDeImpuesto != value))
				{
					this._ValorDeImpuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTipoCambio", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> ValorTipoCambio
		{
			get
			{
				return this._ValorTipoCambio;
			}
			set
			{
				if ((this._ValorTipoCambio != value))
				{
					this._ValorTipoCambio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleadoVendedor", DbType="Int")]
		public System.Nullable<int> codEmpleadoVendedor
		{
			get
			{
				return this._codEmpleadoVendedor;
			}
			set
			{
				if ((this._codEmpleadoVendedor != value))
				{
					this._codEmpleadoVendedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomEmpleadoVendedor", DbType="VarChar(100)")]
		public string nomEmpleadoVendedor
		{
			get
			{
				return this._nomEmpleadoVendedor;
			}
			set
			{
				if ((this._nomEmpleadoVendedor != value))
				{
					this._nomEmpleadoVendedor = value;
				}
			}
		}
	}
	
	public partial class omgc_R_RegistroDeVentasComprasContabResult
	{
		
		private System.DateTime _FechaDeEmision;
		
		private string _NumeroComprobante;
		
		private string _CodigoPersonaEntidad;
		
		private string _EntidadNumeroRUC;
		
		private string _EntidadRazonSocial;
		
		private string _CodigoArguEstadoDocu;
		
		private string _CodigoArguEstadoDocuNombre;
		
		private string _CodigoArguMoneda;
		
		private string _CodigoArguMonedaNombre;
		
		private decimal _ValorTotalPrecioExtran;
		
		private System.Nullable<decimal> _ValorTotalVenta;
		
		private System.Nullable<decimal> _ValorTotalImpuesto;
		
		private System.Nullable<decimal> _ValorTotalPrecioVenta;
		
		private bool _DocEsGravado;
		
		private System.Nullable<decimal> _ValorDeImpuesto;
		
		private System.Nullable<decimal> _ValorTipoCambio;
		
		public omgc_R_RegistroDeVentasComprasContabResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaDeEmision", DbType="DateTime NOT NULL")]
		public System.DateTime FechaDeEmision
		{
			get
			{
				return this._FechaDeEmision;
			}
			set
			{
				if ((this._FechaDeEmision != value))
				{
					this._FechaDeEmision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroComprobante", DbType="VarChar(16)")]
		public string NumeroComprobante
		{
			get
			{
				return this._NumeroComprobante;
			}
			set
			{
				if ((this._NumeroComprobante != value))
				{
					this._NumeroComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPersonaEntidad", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string CodigoPersonaEntidad
		{
			get
			{
				return this._CodigoPersonaEntidad;
			}
			set
			{
				if ((this._CodigoPersonaEntidad != value))
				{
					this._CodigoPersonaEntidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntidadNumeroRUC", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string EntidadNumeroRUC
		{
			get
			{
				return this._EntidadNumeroRUC;
			}
			set
			{
				if ((this._EntidadNumeroRUC != value))
				{
					this._EntidadNumeroRUC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntidadRazonSocial", DbType="VarChar(35)")]
		public string EntidadRazonSocial
		{
			get
			{
				return this._EntidadRazonSocial;
			}
			set
			{
				if ((this._EntidadRazonSocial != value))
				{
					this._EntidadRazonSocial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguEstadoDocu", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CodigoArguEstadoDocu
		{
			get
			{
				return this._CodigoArguEstadoDocu;
			}
			set
			{
				if ((this._CodigoArguEstadoDocu != value))
				{
					this._CodigoArguEstadoDocu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguEstadoDocuNombre", DbType="VarChar(100)")]
		public string CodigoArguEstadoDocuNombre
		{
			get
			{
				return this._CodigoArguEstadoDocuNombre;
			}
			set
			{
				if ((this._CodigoArguEstadoDocuNombre != value))
				{
					this._CodigoArguEstadoDocuNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguMoneda", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string CodigoArguMoneda
		{
			get
			{
				return this._CodigoArguMoneda;
			}
			set
			{
				if ((this._CodigoArguMoneda != value))
				{
					this._CodigoArguMoneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguMonedaNombre", DbType="VarChar(100)")]
		public string CodigoArguMonedaNombre
		{
			get
			{
				return this._CodigoArguMonedaNombre;
			}
			set
			{
				if ((this._CodigoArguMonedaNombre != value))
				{
					this._CodigoArguMonedaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTotalPrecioExtran", DbType="Decimal(12,2) NOT NULL")]
		public decimal ValorTotalPrecioExtran
		{
			get
			{
				return this._ValorTotalPrecioExtran;
			}
			set
			{
				if ((this._ValorTotalPrecioExtran != value))
				{
					this._ValorTotalPrecioExtran = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTotalVenta", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ValorTotalVenta
		{
			get
			{
				return this._ValorTotalVenta;
			}
			set
			{
				if ((this._ValorTotalVenta != value))
				{
					this._ValorTotalVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTotalImpuesto", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ValorTotalImpuesto
		{
			get
			{
				return this._ValorTotalImpuesto;
			}
			set
			{
				if ((this._ValorTotalImpuesto != value))
				{
					this._ValorTotalImpuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTotalPrecioVenta", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ValorTotalPrecioVenta
		{
			get
			{
				return this._ValorTotalPrecioVenta;
			}
			set
			{
				if ((this._ValorTotalPrecioVenta != value))
				{
					this._ValorTotalPrecioVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocEsGravado", DbType="Bit NOT NULL")]
		public bool DocEsGravado
		{
			get
			{
				return this._DocEsGravado;
			}
			set
			{
				if ((this._DocEsGravado != value))
				{
					this._DocEsGravado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorDeImpuesto", DbType="Decimal(6,4)")]
		public System.Nullable<decimal> ValorDeImpuesto
		{
			get
			{
				return this._ValorDeImpuesto;
			}
			set
			{
				if ((this._ValorDeImpuesto != value))
				{
					this._ValorDeImpuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTipoCambio", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> ValorTipoCambio
		{
			get
			{
				return this._ValorTipoCambio;
			}
			set
			{
				if ((this._ValorTipoCambio != value))
				{
					this._ValorTipoCambio = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
