#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CROM.GestionAlmacen.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_GC_MAGESET_SFS_20201106")]
	public partial class _ProduccionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public _ProduccionDataContext() : 
				base(global::CROM.GestionAlmacen.DataAccess.Properties.Settings.Default.BD_GC_MAGESET_SFS_20201106ConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public _ProduccionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _ProduccionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _ProduccionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public _ProduccionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Produccion.omgc_D_ProductoKardex")]
		public int omgc_D_ProductoKardex([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codDocumReg, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string p_codDeposito)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codEmpresa, p_codDocumReg, p_codDeposito);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Produccion.omgc_U_ProductoKardex_DeshacerCierre")]
		public int omgc_U_ProductoKardex_DeshacerCierre([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string p_codPuntoDeVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string p_codDeposito, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segUsuarioEdita, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(6)")] string p_perInventario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codEmpresa, p_codPuntoDeVenta, p_codDeposito, p_codProducto, p_segUsuarioEdita, p_perInventario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Produccion.omgc_I_ProductoKardex")]
		public int omgc_I_ProductoKardex(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> p_codProductoKardex, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codEmpresa, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codProducto, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codDocumRegDetalle, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> p_fecMovimiento, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string p_codRegistroTipoMovimi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string p_codPersonaMovimi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,3)")] System.Nullable<decimal> p_cntSalida, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,3)")] System.Nullable<decimal> p_cntEntrada, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,3)")] System.Nullable<decimal> p_cntDevolucion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,3)")] System.Nullable<decimal> p_cntSaldo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,5)")] System.Nullable<decimal> p_monCostoUnitSalida, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,5)")] System.Nullable<decimal> p_monCostoUnitEntrada, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,5)")] System.Nullable<decimal> p_monCostoUnitDevolucion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,5)")] System.Nullable<decimal> p_monCostoUnitSaldo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_perKardexAnio, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string p_codDeposito, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string p_codRegistroTipoMotivo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> p_indActivo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segUsuarioCrea)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codProductoKardex, p_codEmpresa, p_codProducto, p_codDocumRegDetalle, p_fecMovimiento, p_codRegistroTipoMovimi, p_codPersonaMovimi, p_cntSalida, p_cntEntrada, p_cntDevolucion, p_cntSaldo, p_monCostoUnitSalida, p_monCostoUnitEntrada, p_monCostoUnitDevolucion, p_monCostoUnitSaldo, p_perKardexAnio, p_codDeposito, p_codRegistroTipoMotivo, p_indActivo, p_segUsuarioCrea);
			p_codProductoKardex = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Produccion.omgc_S_ProductoKardex_codDocumReg")]
		public ISingleResult<omgc_S_ProductoKardex_codDocumRegResult> omgc_S_ProductoKardex_codDocumReg([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codDocumReg)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codEmpresa, p_codDocumReg);
			return ((ISingleResult<omgc_S_ProductoKardex_codDocumRegResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Produccion.omgc_S_ProductoKardex_Inventario")]
		public ISingleResult<omgc_S_ProductoKardex_InventarioResult> omgc_S_ProductoKardex_Inventario([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string p_codPuntoDeVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string p_codDeposito, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string p_codDocumento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string p_codRegistroTipoMovimi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codEmpresa, p_codPuntoDeVenta, p_codDeposito, p_codDocumento, p_codRegistroTipoMovimi);
			return ((ISingleResult<omgc_S_ProductoKardex_InventarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Produccion.omgc_U_ProductoKardex_Cierre")]
		public int omgc_U_ProductoKardex_Cierre([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string p_codPuntoDeVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string p_codDeposito, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segUsuarioEdita, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(6)")] string p_perInventario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> p_fecInventarioCierre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codEmpleado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codEmpresa, p_codPuntoDeVenta, p_codDeposito, p_codProducto, p_segUsuarioEdita, p_perInventario, p_fecInventarioCierre, p_codEmpleado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Produccion.omgc_S_ProductoKardex")]
		public ISingleResult<omgc_S_ProductoKardexResult> omgc_S_ProductoKardex([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string p_fecMovimiento_Desde, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(8)")] string p_fecMovimiento_Hasta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string p_codDeposito, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string p_codPuntoDeVenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string p_codPersonaMovimi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string p_codDocumento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(16)")] string p_numDocumento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string p_codRegistroTipoMovimi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string p_codRegistroTipoMotivo1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(17)")] string p_codRegistroTipoMotivo2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> p_indActivo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(6)")] string p_perInventario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codEmpresa, p_fecMovimiento_Desde, p_fecMovimiento_Hasta, p_codDeposito, p_codPuntoDeVenta, p_codPersonaMovimi, p_codProducto, p_codDocumento, p_numDocumento, p_codRegistroTipoMovimi, p_codRegistroTipoMotivo1, p_codRegistroTipoMotivo2, p_indActivo, p_perInventario);
			return ((ISingleResult<omgc_S_ProductoKardexResult>)(result.ReturnValue));
		}
	}
	
	public partial class omgc_S_ProductoKardex_codDocumRegResult
	{
		
		private int _codProductoKardex;
		
		private int _codDocumRegDetalle;
		
		private System.Nullable<int> _codDocumReg;
		
		private System.DateTime _fecMovimiento;
		
		private int _codProducto;
		
		private string _codigoProducto;
		
		private System.Nullable<decimal> _cntStockFisico;
		
		private System.Nullable<decimal> _cntStockComprometido;
		
		private System.Nullable<decimal> _cntStockInicial;
		
		private System.Nullable<decimal> _cntStockConsignacion;
		
		private string _codProductoNombre;
		
		private string _codProductoRefer;
		
		private string _codRegistroCategProducto;
		
		private string _codRegistroCategProductoNombre;
		
		private string _codRegistroUnidadMedida;
		
		private string _codRegistroUnidadMedidaNombre;
		
		private System.Nullable<int> _codEmpresa;
		
		private string _codEmpresaNombre;
		
		private string _codPuntoDeVenta;
		
		private string _codPuntoDeVentaNombre;
		
		private string _codRegistroTipoMovimi;
		
		private string _codRegistroTipoMovimiNombre;
		
		private string _codRegistroTipoMotivo;
		
		private string _codRegistroTipoMotivoNombre;
		
		private string _codPersonaMovimi;
		
		private string _codPersonaMovimiNombre;
		
		private string _codDocumento;
		
		private string _codDocumentoNombre;
		
		private string _numDocumento;
		
		private string _codItemDetalle;
		
		private string _CodigoArguMoneda;
		
		private System.Nullable<decimal> _cntEntrada;
		
		private System.Nullable<decimal> _monCostoUnitEntrada;
		
		private System.Nullable<decimal> _cntSalida;
		
		private System.Nullable<decimal> _monCostoUnitSalida;
		
		private System.Nullable<decimal> _cntDevolucion;
		
		private System.Nullable<decimal> _monCostoUnitDevoluc;
		
		private System.Nullable<decimal> _cntSaldo;
		
		private System.Nullable<decimal> _monCostoUnitSaldo;
		
		private string _desRazonSocial;
		
		private short _perKardexAnio;
		
		private string _codRegistroDeposito;
		
		private string _codRegistroDepositoNombre;
		
		private bool _indActivo;
		
		private string _segUsuarioCrea;
		
		private string _segUsuarioEdita;
		
		private System.DateTime _segFechaCrea;
		
		private System.Nullable<System.DateTime> _segFechaEdita;
		
		private string _segMaquina;
		
		private string _codRegistroTipoMotivo1;
		
		private string _codRegistroTipoMotivoNombre1;
		
		private string _perInventario;
		
		private System.Nullable<System.DateTime> _fecInventarioCierre;
		
		private System.Nullable<int> _codEmpleado;
		
		private string _codEmpleadoNombre;
		
		public omgc_S_ProductoKardex_codDocumRegResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProductoKardex", DbType="Int NOT NULL")]
		public int codProductoKardex
		{
			get
			{
				return this._codProductoKardex;
			}
			set
			{
				if ((this._codProductoKardex != value))
				{
					this._codProductoKardex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDocumRegDetalle", DbType="Int NOT NULL")]
		public int codDocumRegDetalle
		{
			get
			{
				return this._codDocumRegDetalle;
			}
			set
			{
				if ((this._codDocumRegDetalle != value))
				{
					this._codDocumRegDetalle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDocumReg", DbType="Int")]
		public System.Nullable<int> codDocumReg
		{
			get
			{
				return this._codDocumReg;
			}
			set
			{
				if ((this._codDocumReg != value))
				{
					this._codDocumReg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecMovimiento", DbType="DateTime NOT NULL")]
		public System.DateTime fecMovimiento
		{
			get
			{
				return this._fecMovimiento;
			}
			set
			{
				if ((this._fecMovimiento != value))
				{
					this._fecMovimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProducto", DbType="Int NOT NULL")]
		public int codProducto
		{
			get
			{
				return this._codProducto;
			}
			set
			{
				if ((this._codProducto != value))
				{
					this._codProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProducto", DbType="VarChar(20)")]
		public string codigoProducto
		{
			get
			{
				return this._codigoProducto;
			}
			set
			{
				if ((this._codigoProducto != value))
				{
					this._codigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntStockFisico", DbType="Decimal(16,4)")]
		public System.Nullable<decimal> cntStockFisico
		{
			get
			{
				return this._cntStockFisico;
			}
			set
			{
				if ((this._cntStockFisico != value))
				{
					this._cntStockFisico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntStockComprometido", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> cntStockComprometido
		{
			get
			{
				return this._cntStockComprometido;
			}
			set
			{
				if ((this._cntStockComprometido != value))
				{
					this._cntStockComprometido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntStockInicial", DbType="Decimal(22,4)")]
		public System.Nullable<decimal> cntStockInicial
		{
			get
			{
				return this._cntStockInicial;
			}
			set
			{
				if ((this._cntStockInicial != value))
				{
					this._cntStockInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntStockConsignacion", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> cntStockConsignacion
		{
			get
			{
				return this._cntStockConsignacion;
			}
			set
			{
				if ((this._cntStockConsignacion != value))
				{
					this._cntStockConsignacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProductoNombre", DbType="VarChar(100)")]
		public string codProductoNombre
		{
			get
			{
				return this._codProductoNombre;
			}
			set
			{
				if ((this._codProductoNombre != value))
				{
					this._codProductoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProductoRefer", DbType="VarChar(20)")]
		public string codProductoRefer
		{
			get
			{
				return this._codProductoRefer;
			}
			set
			{
				if ((this._codProductoRefer != value))
				{
					this._codProductoRefer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroCategProducto", DbType="VarChar(17)")]
		public string codRegistroCategProducto
		{
			get
			{
				return this._codRegistroCategProducto;
			}
			set
			{
				if ((this._codRegistroCategProducto != value))
				{
					this._codRegistroCategProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroCategProductoNombre", DbType="VarChar(100)")]
		public string codRegistroCategProductoNombre
		{
			get
			{
				return this._codRegistroCategProductoNombre;
			}
			set
			{
				if ((this._codRegistroCategProductoNombre != value))
				{
					this._codRegistroCategProductoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroUnidadMedida", DbType="VarChar(17)")]
		public string codRegistroUnidadMedida
		{
			get
			{
				return this._codRegistroUnidadMedida;
			}
			set
			{
				if ((this._codRegistroUnidadMedida != value))
				{
					this._codRegistroUnidadMedida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroUnidadMedidaNombre", DbType="VarChar(100)")]
		public string codRegistroUnidadMedidaNombre
		{
			get
			{
				return this._codRegistroUnidadMedidaNombre;
			}
			set
			{
				if ((this._codRegistroUnidadMedidaNombre != value))
				{
					this._codRegistroUnidadMedidaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpresa", DbType="Int")]
		public System.Nullable<int> codEmpresa
		{
			get
			{
				return this._codEmpresa;
			}
			set
			{
				if ((this._codEmpresa != value))
				{
					this._codEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpresaNombre", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string codEmpresaNombre
		{
			get
			{
				return this._codEmpresaNombre;
			}
			set
			{
				if ((this._codEmpresaNombre != value))
				{
					this._codEmpresaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPuntoDeVenta", DbType="VarChar(4)")]
		public string codPuntoDeVenta
		{
			get
			{
				return this._codPuntoDeVenta;
			}
			set
			{
				if ((this._codPuntoDeVenta != value))
				{
					this._codPuntoDeVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPuntoDeVentaNombre", DbType="VarChar(50)")]
		public string codPuntoDeVentaNombre
		{
			get
			{
				return this._codPuntoDeVentaNombre;
			}
			set
			{
				if ((this._codPuntoDeVentaNombre != value))
				{
					this._codPuntoDeVentaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroTipoMovimi", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string codRegistroTipoMovimi
		{
			get
			{
				return this._codRegistroTipoMovimi;
			}
			set
			{
				if ((this._codRegistroTipoMovimi != value))
				{
					this._codRegistroTipoMovimi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroTipoMovimiNombre", DbType="VarChar(109)")]
		public string codRegistroTipoMovimiNombre
		{
			get
			{
				return this._codRegistroTipoMovimiNombre;
			}
			set
			{
				if ((this._codRegistroTipoMovimiNombre != value))
				{
					this._codRegistroTipoMovimiNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroTipoMotivo", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string codRegistroTipoMotivo
		{
			get
			{
				return this._codRegistroTipoMotivo;
			}
			set
			{
				if ((this._codRegistroTipoMotivo != value))
				{
					this._codRegistroTipoMotivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroTipoMotivoNombre", DbType="VarChar(100)")]
		public string codRegistroTipoMotivoNombre
		{
			get
			{
				return this._codRegistroTipoMotivoNombre;
			}
			set
			{
				if ((this._codRegistroTipoMotivoNombre != value))
				{
					this._codRegistroTipoMotivoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPersonaMovimi", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string codPersonaMovimi
		{
			get
			{
				return this._codPersonaMovimi;
			}
			set
			{
				if ((this._codPersonaMovimi != value))
				{
					this._codPersonaMovimi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPersonaMovimiNombre", DbType="VarChar(100)")]
		public string codPersonaMovimiNombre
		{
			get
			{
				return this._codPersonaMovimiNombre;
			}
			set
			{
				if ((this._codPersonaMovimiNombre != value))
				{
					this._codPersonaMovimiNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDocumento", DbType="VarChar(3)")]
		public string codDocumento
		{
			get
			{
				return this._codDocumento;
			}
			set
			{
				if ((this._codDocumento != value))
				{
					this._codDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDocumentoNombre", DbType="VarChar(50)")]
		public string codDocumentoNombre
		{
			get
			{
				return this._codDocumentoNombre;
			}
			set
			{
				if ((this._codDocumentoNombre != value))
				{
					this._codDocumentoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numDocumento", DbType="VarChar(16)")]
		public string numDocumento
		{
			get
			{
				return this._numDocumento;
			}
			set
			{
				if ((this._numDocumento != value))
				{
					this._numDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codItemDetalle", DbType="VarChar(3)")]
		public string codItemDetalle
		{
			get
			{
				return this._codItemDetalle;
			}
			set
			{
				if ((this._codItemDetalle != value))
				{
					this._codItemDetalle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguMoneda", DbType="VarChar(17)")]
		public string CodigoArguMoneda
		{
			get
			{
				return this._CodigoArguMoneda;
			}
			set
			{
				if ((this._CodigoArguMoneda != value))
				{
					this._CodigoArguMoneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntEntrada", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> cntEntrada
		{
			get
			{
				return this._cntEntrada;
			}
			set
			{
				if ((this._cntEntrada != value))
				{
					this._cntEntrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monCostoUnitEntrada", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> monCostoUnitEntrada
		{
			get
			{
				return this._monCostoUnitEntrada;
			}
			set
			{
				if ((this._monCostoUnitEntrada != value))
				{
					this._monCostoUnitEntrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntSalida", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> cntSalida
		{
			get
			{
				return this._cntSalida;
			}
			set
			{
				if ((this._cntSalida != value))
				{
					this._cntSalida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monCostoUnitSalida", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> monCostoUnitSalida
		{
			get
			{
				return this._monCostoUnitSalida;
			}
			set
			{
				if ((this._monCostoUnitSalida != value))
				{
					this._monCostoUnitSalida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntDevolucion", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> cntDevolucion
		{
			get
			{
				return this._cntDevolucion;
			}
			set
			{
				if ((this._cntDevolucion != value))
				{
					this._cntDevolucion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monCostoUnitDevoluc", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> monCostoUnitDevoluc
		{
			get
			{
				return this._monCostoUnitDevoluc;
			}
			set
			{
				if ((this._monCostoUnitDevoluc != value))
				{
					this._monCostoUnitDevoluc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntSaldo", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> cntSaldo
		{
			get
			{
				return this._cntSaldo;
			}
			set
			{
				if ((this._cntSaldo != value))
				{
					this._cntSaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monCostoUnitSaldo", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> monCostoUnitSaldo
		{
			get
			{
				return this._monCostoUnitSaldo;
			}
			set
			{
				if ((this._monCostoUnitSaldo != value))
				{
					this._monCostoUnitSaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desRazonSocial", DbType="VarChar(90)")]
		public string desRazonSocial
		{
			get
			{
				return this._desRazonSocial;
			}
			set
			{
				if ((this._desRazonSocial != value))
				{
					this._desRazonSocial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perKardexAnio", DbType="SmallInt NOT NULL")]
		public short perKardexAnio
		{
			get
			{
				return this._perKardexAnio;
			}
			set
			{
				if ((this._perKardexAnio != value))
				{
					this._perKardexAnio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroDeposito", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string codRegistroDeposito
		{
			get
			{
				return this._codRegistroDeposito;
			}
			set
			{
				if ((this._codRegistroDeposito != value))
				{
					this._codRegistroDeposito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroDepositoNombre", DbType="VarChar(60)")]
		public string codRegistroDepositoNombre
		{
			get
			{
				return this._codRegistroDepositoNombre;
			}
			set
			{
				if ((this._codRegistroDepositoNombre != value))
				{
					this._codRegistroDepositoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indActivo", DbType="Bit NOT NULL")]
		public bool indActivo
		{
			get
			{
				return this._indActivo;
			}
			set
			{
				if ((this._indActivo != value))
				{
					this._indActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioCrea", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string segUsuarioCrea
		{
			get
			{
				return this._segUsuarioCrea;
			}
			set
			{
				if ((this._segUsuarioCrea != value))
				{
					this._segUsuarioCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioEdita", DbType="VarChar(50)")]
		public string segUsuarioEdita
		{
			get
			{
				return this._segUsuarioEdita;
			}
			set
			{
				if ((this._segUsuarioEdita != value))
				{
					this._segUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaCrea", DbType="DateTime NOT NULL")]
		public System.DateTime segFechaCrea
		{
			get
			{
				return this._segFechaCrea;
			}
			set
			{
				if ((this._segFechaCrea != value))
				{
					this._segFechaCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaEdita", DbType="DateTime")]
		public System.Nullable<System.DateTime> segFechaEdita
		{
			get
			{
				return this._segFechaEdita;
			}
			set
			{
				if ((this._segFechaEdita != value))
				{
					this._segFechaEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segMaquina", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string segMaquina
		{
			get
			{
				return this._segMaquina;
			}
			set
			{
				if ((this._segMaquina != value))
				{
					this._segMaquina = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroTipoMotivo1", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string codRegistroTipoMotivo1
		{
			get
			{
				return this._codRegistroTipoMotivo1;
			}
			set
			{
				if ((this._codRegistroTipoMotivo1 != value))
				{
					this._codRegistroTipoMotivo1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroTipoMotivoNombre1", DbType="VarChar(100)")]
		public string codRegistroTipoMotivoNombre1
		{
			get
			{
				return this._codRegistroTipoMotivoNombre1;
			}
			set
			{
				if ((this._codRegistroTipoMotivoNombre1 != value))
				{
					this._codRegistroTipoMotivoNombre1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perInventario", DbType="VarChar(6)")]
		public string perInventario
		{
			get
			{
				return this._perInventario;
			}
			set
			{
				if ((this._perInventario != value))
				{
					this._perInventario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecInventarioCierre", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecInventarioCierre
		{
			get
			{
				return this._fecInventarioCierre;
			}
			set
			{
				if ((this._fecInventarioCierre != value))
				{
					this._fecInventarioCierre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleado", DbType="Int")]
		public System.Nullable<int> codEmpleado
		{
			get
			{
				return this._codEmpleado;
			}
			set
			{
				if ((this._codEmpleado != value))
				{
					this._codEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleadoNombre", DbType="VarChar(100)")]
		public string codEmpleadoNombre
		{
			get
			{
				return this._codEmpleadoNombre;
			}
			set
			{
				if ((this._codEmpleadoNombre != value))
				{
					this._codEmpleadoNombre = value;
				}
			}
		}
	}
	
	public partial class omgc_S_ProductoKardex_InventarioResult
	{
		
		private int _codProductoKardex;
		
		private int _codDocumRegDetalle;
		
		private System.Nullable<int> _codDocumReg;
		
		private System.DateTime _fecMovimiento;
		
		private int _codProducto;
		
		private System.Nullable<decimal> _cntStockFisico;
		
		private System.Nullable<decimal> _cntStockComprometido;
		
		private System.Nullable<decimal> _cntStockInicial;
		
		private System.Nullable<decimal> _cntStockConsignacion;
		
		private string _codProductoNombre;
		
		private string _codProductoRefer;
		
		private string _codRegistroCategProducto;
		
		private string _codRegistroCategProductoNombre;
		
		private string _codRegistroUnidadMedida;
		
		private string _codRegistroUnidadMedidaNombre;
		
		private System.Nullable<int> _codEmpresa;
		
		private string _codEmpresaNombre;
		
		private string _codPuntoDeVenta;
		
		private string _codPuntoDeVentaNombre;
		
		private string _codRegistroTipoMovimi;
		
		private string _codRegistroTipoMovimiNombre;
		
		private string _codRegistroTipoMotivo;
		
		private string _codRegistroTipoMotivoNombre;
		
		private string _codPersonaMovimi;
		
		private string _codPersonaMovimiNombre;
		
		private string _codDocumento;
		
		private string _codDocumentoNombre;
		
		private string _numDocumento;
		
		private string _codigoItemDetalle;
		
		private System.Nullable<decimal> _cntEntrada;
		
		private System.Nullable<decimal> _monCostoUnitEntrada;
		
		private System.Nullable<decimal> _cntSalida;
		
		private System.Nullable<decimal> _monCostoUnitSalida;
		
		private System.Nullable<decimal> _cntDevolucion;
		
		private System.Nullable<decimal> _monCostoUnitDevoluc;
		
		private System.Nullable<decimal> _cntSaldo;
		
		private System.Nullable<decimal> _monCostoUnitSaldo;
		
		private string _desRazonSocial;
		
		private short _perKardexAnio;
		
		private string _codRegistroDeposito;
		
		private string _codRegistroDepositoNombre;
		
		private bool _indActivo;
		
		private string _segUsuarioCrea;
		
		private string _segUsuarioEdita;
		
		private System.DateTime _segFechaCrea;
		
		private System.Nullable<System.DateTime> _segFechaEdita;
		
		private string _segMaquina;
		
		private string _codRegistroTipoMotivo1;
		
		private string _codRegistroTipoMotivoNombre1;
		
		private string _perInventario;
		
		private System.Nullable<System.DateTime> _fecInventarioCierre;
		
		private System.Nullable<int> _codEmpleado;
		
		private string _codEmpleadoNombre;
		
		public omgc_S_ProductoKardex_InventarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProductoKardex", DbType="Int NOT NULL")]
		public int codProductoKardex
		{
			get
			{
				return this._codProductoKardex;
			}
			set
			{
				if ((this._codProductoKardex != value))
				{
					this._codProductoKardex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDocumRegDetalle", DbType="Int NOT NULL")]
		public int codDocumRegDetalle
		{
			get
			{
				return this._codDocumRegDetalle;
			}
			set
			{
				if ((this._codDocumRegDetalle != value))
				{
					this._codDocumRegDetalle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDocumReg", DbType="Int")]
		public System.Nullable<int> codDocumReg
		{
			get
			{
				return this._codDocumReg;
			}
			set
			{
				if ((this._codDocumReg != value))
				{
					this._codDocumReg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecMovimiento", DbType="DateTime NOT NULL")]
		public System.DateTime fecMovimiento
		{
			get
			{
				return this._fecMovimiento;
			}
			set
			{
				if ((this._fecMovimiento != value))
				{
					this._fecMovimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProducto", DbType="Int NOT NULL")]
		public int codProducto
		{
			get
			{
				return this._codProducto;
			}
			set
			{
				if ((this._codProducto != value))
				{
					this._codProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntStockFisico", DbType="Decimal(16,4)")]
		public System.Nullable<decimal> cntStockFisico
		{
			get
			{
				return this._cntStockFisico;
			}
			set
			{
				if ((this._cntStockFisico != value))
				{
					this._cntStockFisico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntStockComprometido", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> cntStockComprometido
		{
			get
			{
				return this._cntStockComprometido;
			}
			set
			{
				if ((this._cntStockComprometido != value))
				{
					this._cntStockComprometido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntStockInicial", DbType="Decimal(22,4)")]
		public System.Nullable<decimal> cntStockInicial
		{
			get
			{
				return this._cntStockInicial;
			}
			set
			{
				if ((this._cntStockInicial != value))
				{
					this._cntStockInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntStockConsignacion", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> cntStockConsignacion
		{
			get
			{
				return this._cntStockConsignacion;
			}
			set
			{
				if ((this._cntStockConsignacion != value))
				{
					this._cntStockConsignacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProductoNombre", DbType="VarChar(100)")]
		public string codProductoNombre
		{
			get
			{
				return this._codProductoNombre;
			}
			set
			{
				if ((this._codProductoNombre != value))
				{
					this._codProductoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProductoRefer", DbType="VarChar(20)")]
		public string codProductoRefer
		{
			get
			{
				return this._codProductoRefer;
			}
			set
			{
				if ((this._codProductoRefer != value))
				{
					this._codProductoRefer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroCategProducto", DbType="VarChar(17)")]
		public string codRegistroCategProducto
		{
			get
			{
				return this._codRegistroCategProducto;
			}
			set
			{
				if ((this._codRegistroCategProducto != value))
				{
					this._codRegistroCategProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroCategProductoNombre", DbType="VarChar(100)")]
		public string codRegistroCategProductoNombre
		{
			get
			{
				return this._codRegistroCategProductoNombre;
			}
			set
			{
				if ((this._codRegistroCategProductoNombre != value))
				{
					this._codRegistroCategProductoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroUnidadMedida", DbType="VarChar(17)")]
		public string codRegistroUnidadMedida
		{
			get
			{
				return this._codRegistroUnidadMedida;
			}
			set
			{
				if ((this._codRegistroUnidadMedida != value))
				{
					this._codRegistroUnidadMedida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroUnidadMedidaNombre", DbType="VarChar(100)")]
		public string codRegistroUnidadMedidaNombre
		{
			get
			{
				return this._codRegistroUnidadMedidaNombre;
			}
			set
			{
				if ((this._codRegistroUnidadMedidaNombre != value))
				{
					this._codRegistroUnidadMedidaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpresa", DbType="Int")]
		public System.Nullable<int> codEmpresa
		{
			get
			{
				return this._codEmpresa;
			}
			set
			{
				if ((this._codEmpresa != value))
				{
					this._codEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpresaNombre", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string codEmpresaNombre
		{
			get
			{
				return this._codEmpresaNombre;
			}
			set
			{
				if ((this._codEmpresaNombre != value))
				{
					this._codEmpresaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPuntoDeVenta", DbType="VarChar(4)")]
		public string codPuntoDeVenta
		{
			get
			{
				return this._codPuntoDeVenta;
			}
			set
			{
				if ((this._codPuntoDeVenta != value))
				{
					this._codPuntoDeVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPuntoDeVentaNombre", DbType="VarChar(50)")]
		public string codPuntoDeVentaNombre
		{
			get
			{
				return this._codPuntoDeVentaNombre;
			}
			set
			{
				if ((this._codPuntoDeVentaNombre != value))
				{
					this._codPuntoDeVentaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroTipoMovimi", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string codRegistroTipoMovimi
		{
			get
			{
				return this._codRegistroTipoMovimi;
			}
			set
			{
				if ((this._codRegistroTipoMovimi != value))
				{
					this._codRegistroTipoMovimi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroTipoMovimiNombre", DbType="VarChar(100)")]
		public string codRegistroTipoMovimiNombre
		{
			get
			{
				return this._codRegistroTipoMovimiNombre;
			}
			set
			{
				if ((this._codRegistroTipoMovimiNombre != value))
				{
					this._codRegistroTipoMovimiNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroTipoMotivo", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string codRegistroTipoMotivo
		{
			get
			{
				return this._codRegistroTipoMotivo;
			}
			set
			{
				if ((this._codRegistroTipoMotivo != value))
				{
					this._codRegistroTipoMotivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroTipoMotivoNombre", DbType="VarChar(100)")]
		public string codRegistroTipoMotivoNombre
		{
			get
			{
				return this._codRegistroTipoMotivoNombre;
			}
			set
			{
				if ((this._codRegistroTipoMotivoNombre != value))
				{
					this._codRegistroTipoMotivoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPersonaMovimi", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string codPersonaMovimi
		{
			get
			{
				return this._codPersonaMovimi;
			}
			set
			{
				if ((this._codPersonaMovimi != value))
				{
					this._codPersonaMovimi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPersonaMovimiNombre", DbType="VarChar(100)")]
		public string codPersonaMovimiNombre
		{
			get
			{
				return this._codPersonaMovimiNombre;
			}
			set
			{
				if ((this._codPersonaMovimiNombre != value))
				{
					this._codPersonaMovimiNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDocumento", DbType="VarChar(3)")]
		public string codDocumento
		{
			get
			{
				return this._codDocumento;
			}
			set
			{
				if ((this._codDocumento != value))
				{
					this._codDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDocumentoNombre", DbType="VarChar(50)")]
		public string codDocumentoNombre
		{
			get
			{
				return this._codDocumentoNombre;
			}
			set
			{
				if ((this._codDocumentoNombre != value))
				{
					this._codDocumentoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numDocumento", DbType="VarChar(16)")]
		public string numDocumento
		{
			get
			{
				return this._numDocumento;
			}
			set
			{
				if ((this._numDocumento != value))
				{
					this._numDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoItemDetalle", DbType="VarChar(3)")]
		public string codigoItemDetalle
		{
			get
			{
				return this._codigoItemDetalle;
			}
			set
			{
				if ((this._codigoItemDetalle != value))
				{
					this._codigoItemDetalle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntEntrada", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> cntEntrada
		{
			get
			{
				return this._cntEntrada;
			}
			set
			{
				if ((this._cntEntrada != value))
				{
					this._cntEntrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monCostoUnitEntrada", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> monCostoUnitEntrada
		{
			get
			{
				return this._monCostoUnitEntrada;
			}
			set
			{
				if ((this._monCostoUnitEntrada != value))
				{
					this._monCostoUnitEntrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntSalida", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> cntSalida
		{
			get
			{
				return this._cntSalida;
			}
			set
			{
				if ((this._cntSalida != value))
				{
					this._cntSalida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monCostoUnitSalida", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> monCostoUnitSalida
		{
			get
			{
				return this._monCostoUnitSalida;
			}
			set
			{
				if ((this._monCostoUnitSalida != value))
				{
					this._monCostoUnitSalida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntDevolucion", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> cntDevolucion
		{
			get
			{
				return this._cntDevolucion;
			}
			set
			{
				if ((this._cntDevolucion != value))
				{
					this._cntDevolucion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monCostoUnitDevoluc", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> monCostoUnitDevoluc
		{
			get
			{
				return this._monCostoUnitDevoluc;
			}
			set
			{
				if ((this._monCostoUnitDevoluc != value))
				{
					this._monCostoUnitDevoluc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntSaldo", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> cntSaldo
		{
			get
			{
				return this._cntSaldo;
			}
			set
			{
				if ((this._cntSaldo != value))
				{
					this._cntSaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monCostoUnitSaldo", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> monCostoUnitSaldo
		{
			get
			{
				return this._monCostoUnitSaldo;
			}
			set
			{
				if ((this._monCostoUnitSaldo != value))
				{
					this._monCostoUnitSaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desRazonSocial", DbType="VarChar(90)")]
		public string desRazonSocial
		{
			get
			{
				return this._desRazonSocial;
			}
			set
			{
				if ((this._desRazonSocial != value))
				{
					this._desRazonSocial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perKardexAnio", DbType="SmallInt NOT NULL")]
		public short perKardexAnio
		{
			get
			{
				return this._perKardexAnio;
			}
			set
			{
				if ((this._perKardexAnio != value))
				{
					this._perKardexAnio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroDeposito", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string codRegistroDeposito
		{
			get
			{
				return this._codRegistroDeposito;
			}
			set
			{
				if ((this._codRegistroDeposito != value))
				{
					this._codRegistroDeposito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroDepositoNombre", DbType="VarChar(60)")]
		public string codRegistroDepositoNombre
		{
			get
			{
				return this._codRegistroDepositoNombre;
			}
			set
			{
				if ((this._codRegistroDepositoNombre != value))
				{
					this._codRegistroDepositoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indActivo", DbType="Bit NOT NULL")]
		public bool indActivo
		{
			get
			{
				return this._indActivo;
			}
			set
			{
				if ((this._indActivo != value))
				{
					this._indActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioCrea", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string segUsuarioCrea
		{
			get
			{
				return this._segUsuarioCrea;
			}
			set
			{
				if ((this._segUsuarioCrea != value))
				{
					this._segUsuarioCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioEdita", DbType="VarChar(50)")]
		public string segUsuarioEdita
		{
			get
			{
				return this._segUsuarioEdita;
			}
			set
			{
				if ((this._segUsuarioEdita != value))
				{
					this._segUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaCrea", DbType="DateTime NOT NULL")]
		public System.DateTime segFechaCrea
		{
			get
			{
				return this._segFechaCrea;
			}
			set
			{
				if ((this._segFechaCrea != value))
				{
					this._segFechaCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaEdita", DbType="DateTime")]
		public System.Nullable<System.DateTime> segFechaEdita
		{
			get
			{
				return this._segFechaEdita;
			}
			set
			{
				if ((this._segFechaEdita != value))
				{
					this._segFechaEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segMaquina", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string segMaquina
		{
			get
			{
				return this._segMaquina;
			}
			set
			{
				if ((this._segMaquina != value))
				{
					this._segMaquina = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroTipoMotivo1", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string codRegistroTipoMotivo1
		{
			get
			{
				return this._codRegistroTipoMotivo1;
			}
			set
			{
				if ((this._codRegistroTipoMotivo1 != value))
				{
					this._codRegistroTipoMotivo1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroTipoMotivoNombre1", DbType="VarChar(100)")]
		public string codRegistroTipoMotivoNombre1
		{
			get
			{
				return this._codRegistroTipoMotivoNombre1;
			}
			set
			{
				if ((this._codRegistroTipoMotivoNombre1 != value))
				{
					this._codRegistroTipoMotivoNombre1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perInventario", DbType="VarChar(6)")]
		public string perInventario
		{
			get
			{
				return this._perInventario;
			}
			set
			{
				if ((this._perInventario != value))
				{
					this._perInventario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecInventarioCierre", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecInventarioCierre
		{
			get
			{
				return this._fecInventarioCierre;
			}
			set
			{
				if ((this._fecInventarioCierre != value))
				{
					this._fecInventarioCierre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleado", DbType="Int")]
		public System.Nullable<int> codEmpleado
		{
			get
			{
				return this._codEmpleado;
			}
			set
			{
				if ((this._codEmpleado != value))
				{
					this._codEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleadoNombre", DbType="VarChar(100)")]
		public string codEmpleadoNombre
		{
			get
			{
				return this._codEmpleadoNombre;
			}
			set
			{
				if ((this._codEmpleadoNombre != value))
				{
					this._codEmpleadoNombre = value;
				}
			}
		}
	}
	
	public partial class omgc_S_ProductoKardexResult
	{
		
		private int _codProductoKardex;
		
		private int _codDocumRegDetalle;
		
		private System.Nullable<int> _codDocumReg;
		
		private System.DateTime _fecMovimiento;
		
		private int _codProducto;
		
		private string _codigoProducto;
		
		private System.Nullable<decimal> _cntStockFisico;
		
		private System.Nullable<decimal> _cntStockComprometido;
		
		private System.Nullable<decimal> _cntStockInicial;
		
		private System.Nullable<decimal> _cntStockConsignacion;
		
		private string _codProductoNombre;
		
		private string _codProductoRefer;
		
		private System.Nullable<int> _codRegistroCategProducto;
		
		private string _codRegistroCategProductoNombre;
		
		private string _codRegistroUnidadMedida;
		
		private string _codRegistroUnidadMedidaNombre;
		
		private System.Nullable<int> _codEmpresa;
		
		private string _codEmpresaNombre;
		
		private string _codPuntoDeVenta;
		
		private string _codPuntoDeVentaNombre;
		
		private string _codRegistroTipoMovimi;
		
		private string _codRegistroTipoMovimiNombre;
		
		private string _codRegistroTipoMotivo;
		
		private string _codRegistroTipoMotivoNombre;
		
		private string _codPersonaMovimi;
		
		private string _codPersonaMovimiNombre;
		
		private string _codDocumento;
		
		private string _codDocumentoNombre;
		
		private string _numDocumento;
		
		private string _codItemDetalle;
		
		private string _CodigoArguMoneda;
		
		private System.Nullable<decimal> _cntEntrada;
		
		private System.Nullable<decimal> _monCostoUnitEntrada;
		
		private System.Nullable<decimal> _cntSalida;
		
		private System.Nullable<decimal> _monCostoUnitSalida;
		
		private System.Nullable<decimal> _cntDevolucion;
		
		private System.Nullable<decimal> _monCostoUnitDevoluc;
		
		private System.Nullable<decimal> _cntSaldo;
		
		private System.Nullable<decimal> _monCostoUnitSaldo;
		
		private string _desRazonSocial;
		
		private short _perKardexAnio;
		
		private string _codRegistroDeposito;
		
		private string _codRegistroDepositoNombre;
		
		private bool _indActivo;
		
		private string _segUsuarioCrea;
		
		private string _segUsuarioEdita;
		
		private System.DateTime _segFechaCrea;
		
		private System.Nullable<System.DateTime> _segFechaEdita;
		
		private string _segMaquina;
		
		private string _codRegistroTipoMotivo1;
		
		private string _codRegistroTipoMotivoNombre1;
		
		private string _perInventario;
		
		private System.Nullable<System.DateTime> _fecInventarioCierre;
		
		private System.Nullable<int> _codEmpleado;
		
		private string _codEmpleadoNombre;
		
		public omgc_S_ProductoKardexResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProductoKardex", DbType="Int NOT NULL")]
		public int codProductoKardex
		{
			get
			{
				return this._codProductoKardex;
			}
			set
			{
				if ((this._codProductoKardex != value))
				{
					this._codProductoKardex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDocumRegDetalle", DbType="Int NOT NULL")]
		public int codDocumRegDetalle
		{
			get
			{
				return this._codDocumRegDetalle;
			}
			set
			{
				if ((this._codDocumRegDetalle != value))
				{
					this._codDocumRegDetalle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDocumReg", DbType="Int")]
		public System.Nullable<int> codDocumReg
		{
			get
			{
				return this._codDocumReg;
			}
			set
			{
				if ((this._codDocumReg != value))
				{
					this._codDocumReg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecMovimiento", DbType="DateTime NOT NULL")]
		public System.DateTime fecMovimiento
		{
			get
			{
				return this._fecMovimiento;
			}
			set
			{
				if ((this._fecMovimiento != value))
				{
					this._fecMovimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProducto", DbType="Int NOT NULL")]
		public int codProducto
		{
			get
			{
				return this._codProducto;
			}
			set
			{
				if ((this._codProducto != value))
				{
					this._codProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoProducto", DbType="VarChar(20)")]
		public string codigoProducto
		{
			get
			{
				return this._codigoProducto;
			}
			set
			{
				if ((this._codigoProducto != value))
				{
					this._codigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntStockFisico", DbType="Decimal(16,4)")]
		public System.Nullable<decimal> cntStockFisico
		{
			get
			{
				return this._cntStockFisico;
			}
			set
			{
				if ((this._cntStockFisico != value))
				{
					this._cntStockFisico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntStockComprometido", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> cntStockComprometido
		{
			get
			{
				return this._cntStockComprometido;
			}
			set
			{
				if ((this._cntStockComprometido != value))
				{
					this._cntStockComprometido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntStockInicial", DbType="Decimal(22,4)")]
		public System.Nullable<decimal> cntStockInicial
		{
			get
			{
				return this._cntStockInicial;
			}
			set
			{
				if ((this._cntStockInicial != value))
				{
					this._cntStockInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntStockConsignacion", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> cntStockConsignacion
		{
			get
			{
				return this._cntStockConsignacion;
			}
			set
			{
				if ((this._cntStockConsignacion != value))
				{
					this._cntStockConsignacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProductoNombre", DbType="VarChar(100)")]
		public string codProductoNombre
		{
			get
			{
				return this._codProductoNombre;
			}
			set
			{
				if ((this._codProductoNombre != value))
				{
					this._codProductoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProductoRefer", DbType="VarChar(20)")]
		public string codProductoRefer
		{
			get
			{
				return this._codProductoRefer;
			}
			set
			{
				if ((this._codProductoRefer != value))
				{
					this._codProductoRefer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroCategProducto", DbType="Int")]
		public System.Nullable<int> codRegistroCategProducto
		{
			get
			{
				return this._codRegistroCategProducto;
			}
			set
			{
				if ((this._codRegistroCategProducto != value))
				{
					this._codRegistroCategProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroCategProductoNombre", DbType="VarChar(50)")]
		public string codRegistroCategProductoNombre
		{
			get
			{
				return this._codRegistroCategProductoNombre;
			}
			set
			{
				if ((this._codRegistroCategProductoNombre != value))
				{
					this._codRegistroCategProductoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroUnidadMedida", DbType="VarChar(17)")]
		public string codRegistroUnidadMedida
		{
			get
			{
				return this._codRegistroUnidadMedida;
			}
			set
			{
				if ((this._codRegistroUnidadMedida != value))
				{
					this._codRegistroUnidadMedida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroUnidadMedidaNombre", DbType="VarChar(100)")]
		public string codRegistroUnidadMedidaNombre
		{
			get
			{
				return this._codRegistroUnidadMedidaNombre;
			}
			set
			{
				if ((this._codRegistroUnidadMedidaNombre != value))
				{
					this._codRegistroUnidadMedidaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpresa", DbType="Int")]
		public System.Nullable<int> codEmpresa
		{
			get
			{
				return this._codEmpresa;
			}
			set
			{
				if ((this._codEmpresa != value))
				{
					this._codEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpresaNombre", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string codEmpresaNombre
		{
			get
			{
				return this._codEmpresaNombre;
			}
			set
			{
				if ((this._codEmpresaNombre != value))
				{
					this._codEmpresaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPuntoDeVenta", DbType="VarChar(4)")]
		public string codPuntoDeVenta
		{
			get
			{
				return this._codPuntoDeVenta;
			}
			set
			{
				if ((this._codPuntoDeVenta != value))
				{
					this._codPuntoDeVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPuntoDeVentaNombre", DbType="VarChar(50)")]
		public string codPuntoDeVentaNombre
		{
			get
			{
				return this._codPuntoDeVentaNombre;
			}
			set
			{
				if ((this._codPuntoDeVentaNombre != value))
				{
					this._codPuntoDeVentaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroTipoMovimi", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string codRegistroTipoMovimi
		{
			get
			{
				return this._codRegistroTipoMovimi;
			}
			set
			{
				if ((this._codRegistroTipoMovimi != value))
				{
					this._codRegistroTipoMovimi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroTipoMovimiNombre", DbType="VarChar(111)")]
		public string codRegistroTipoMovimiNombre
		{
			get
			{
				return this._codRegistroTipoMovimiNombre;
			}
			set
			{
				if ((this._codRegistroTipoMovimiNombre != value))
				{
					this._codRegistroTipoMovimiNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroTipoMotivo", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string codRegistroTipoMotivo
		{
			get
			{
				return this._codRegistroTipoMotivo;
			}
			set
			{
				if ((this._codRegistroTipoMotivo != value))
				{
					this._codRegistroTipoMotivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroTipoMotivoNombre", DbType="VarChar(100)")]
		public string codRegistroTipoMotivoNombre
		{
			get
			{
				return this._codRegistroTipoMotivoNombre;
			}
			set
			{
				if ((this._codRegistroTipoMotivoNombre != value))
				{
					this._codRegistroTipoMotivoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPersonaMovimi", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string codPersonaMovimi
		{
			get
			{
				return this._codPersonaMovimi;
			}
			set
			{
				if ((this._codPersonaMovimi != value))
				{
					this._codPersonaMovimi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPersonaMovimiNombre", DbType="VarChar(100)")]
		public string codPersonaMovimiNombre
		{
			get
			{
				return this._codPersonaMovimiNombre;
			}
			set
			{
				if ((this._codPersonaMovimiNombre != value))
				{
					this._codPersonaMovimiNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDocumento", DbType="VarChar(3)")]
		public string codDocumento
		{
			get
			{
				return this._codDocumento;
			}
			set
			{
				if ((this._codDocumento != value))
				{
					this._codDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codDocumentoNombre", DbType="VarChar(50)")]
		public string codDocumentoNombre
		{
			get
			{
				return this._codDocumentoNombre;
			}
			set
			{
				if ((this._codDocumentoNombre != value))
				{
					this._codDocumentoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numDocumento", DbType="VarChar(16)")]
		public string numDocumento
		{
			get
			{
				return this._numDocumento;
			}
			set
			{
				if ((this._numDocumento != value))
				{
					this._numDocumento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codItemDetalle", DbType="VarChar(3)")]
		public string codItemDetalle
		{
			get
			{
				return this._codItemDetalle;
			}
			set
			{
				if ((this._codItemDetalle != value))
				{
					this._codItemDetalle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoArguMoneda", DbType="VarChar(17)")]
		public string CodigoArguMoneda
		{
			get
			{
				return this._CodigoArguMoneda;
			}
			set
			{
				if ((this._CodigoArguMoneda != value))
				{
					this._CodigoArguMoneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntEntrada", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> cntEntrada
		{
			get
			{
				return this._cntEntrada;
			}
			set
			{
				if ((this._cntEntrada != value))
				{
					this._cntEntrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monCostoUnitEntrada", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> monCostoUnitEntrada
		{
			get
			{
				return this._monCostoUnitEntrada;
			}
			set
			{
				if ((this._monCostoUnitEntrada != value))
				{
					this._monCostoUnitEntrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntSalida", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> cntSalida
		{
			get
			{
				return this._cntSalida;
			}
			set
			{
				if ((this._cntSalida != value))
				{
					this._cntSalida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monCostoUnitSalida", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> monCostoUnitSalida
		{
			get
			{
				return this._monCostoUnitSalida;
			}
			set
			{
				if ((this._monCostoUnitSalida != value))
				{
					this._monCostoUnitSalida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntDevolucion", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> cntDevolucion
		{
			get
			{
				return this._cntDevolucion;
			}
			set
			{
				if ((this._cntDevolucion != value))
				{
					this._cntDevolucion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monCostoUnitDevoluc", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> monCostoUnitDevoluc
		{
			get
			{
				return this._monCostoUnitDevoluc;
			}
			set
			{
				if ((this._monCostoUnitDevoluc != value))
				{
					this._monCostoUnitDevoluc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cntSaldo", DbType="Decimal(10,3)")]
		public System.Nullable<decimal> cntSaldo
		{
			get
			{
				return this._cntSaldo;
			}
			set
			{
				if ((this._cntSaldo != value))
				{
					this._cntSaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monCostoUnitSaldo", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> monCostoUnitSaldo
		{
			get
			{
				return this._monCostoUnitSaldo;
			}
			set
			{
				if ((this._monCostoUnitSaldo != value))
				{
					this._monCostoUnitSaldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desRazonSocial", DbType="VarChar(100)")]
		public string desRazonSocial
		{
			get
			{
				return this._desRazonSocial;
			}
			set
			{
				if ((this._desRazonSocial != value))
				{
					this._desRazonSocial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perKardexAnio", DbType="SmallInt NOT NULL")]
		public short perKardexAnio
		{
			get
			{
				return this._perKardexAnio;
			}
			set
			{
				if ((this._perKardexAnio != value))
				{
					this._perKardexAnio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroDeposito", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string codRegistroDeposito
		{
			get
			{
				return this._codRegistroDeposito;
			}
			set
			{
				if ((this._codRegistroDeposito != value))
				{
					this._codRegistroDeposito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroDepositoNombre", DbType="VarChar(60)")]
		public string codRegistroDepositoNombre
		{
			get
			{
				return this._codRegistroDepositoNombre;
			}
			set
			{
				if ((this._codRegistroDepositoNombre != value))
				{
					this._codRegistroDepositoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indActivo", DbType="Bit NOT NULL")]
		public bool indActivo
		{
			get
			{
				return this._indActivo;
			}
			set
			{
				if ((this._indActivo != value))
				{
					this._indActivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioCrea", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string segUsuarioCrea
		{
			get
			{
				return this._segUsuarioCrea;
			}
			set
			{
				if ((this._segUsuarioCrea != value))
				{
					this._segUsuarioCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioEdita", DbType="VarChar(50)")]
		public string segUsuarioEdita
		{
			get
			{
				return this._segUsuarioEdita;
			}
			set
			{
				if ((this._segUsuarioEdita != value))
				{
					this._segUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaCrea", DbType="DateTime NOT NULL")]
		public System.DateTime segFechaCrea
		{
			get
			{
				return this._segFechaCrea;
			}
			set
			{
				if ((this._segFechaCrea != value))
				{
					this._segFechaCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaEdita", DbType="DateTime")]
		public System.Nullable<System.DateTime> segFechaEdita
		{
			get
			{
				return this._segFechaEdita;
			}
			set
			{
				if ((this._segFechaEdita != value))
				{
					this._segFechaEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segMaquina", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string segMaquina
		{
			get
			{
				return this._segMaquina;
			}
			set
			{
				if ((this._segMaquina != value))
				{
					this._segMaquina = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroTipoMotivo1", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string codRegistroTipoMotivo1
		{
			get
			{
				return this._codRegistroTipoMotivo1;
			}
			set
			{
				if ((this._codRegistroTipoMotivo1 != value))
				{
					this._codRegistroTipoMotivo1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRegistroTipoMotivoNombre1", DbType="VarChar(100)")]
		public string codRegistroTipoMotivoNombre1
		{
			get
			{
				return this._codRegistroTipoMotivoNombre1;
			}
			set
			{
				if ((this._codRegistroTipoMotivoNombre1 != value))
				{
					this._codRegistroTipoMotivoNombre1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perInventario", DbType="VarChar(6)")]
		public string perInventario
		{
			get
			{
				return this._perInventario;
			}
			set
			{
				if ((this._perInventario != value))
				{
					this._perInventario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecInventarioCierre", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecInventarioCierre
		{
			get
			{
				return this._fecInventarioCierre;
			}
			set
			{
				if ((this._fecInventarioCierre != value))
				{
					this._fecInventarioCierre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleado", DbType="Int")]
		public System.Nullable<int> codEmpleado
		{
			get
			{
				return this._codEmpleado;
			}
			set
			{
				if ((this._codEmpleado != value))
				{
					this._codEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleadoNombre", DbType="VarChar(100)")]
		public string codEmpleadoNombre
		{
			get
			{
				return this._codEmpleadoNombre;
			}
			set
			{
				if ((this._codEmpleadoNombre != value))
				{
					this._codEmpleadoNombre = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
