//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CROM.Seguridad.DataAcces.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;Initial Catalog=BD_CROM_Sistemas;Integrated Security=Tru" +
            "e")]
        public string BD_CROM_SistemasConnectionString {
            get {
                return ((string)(this["BD_CROM_SistemasConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CROM-001\\SQLEXPRESS;Initial Catalog=BD_CROMSeguridad;User ID=sa")]
        public string BD_CROMSeguridadConnectionString {
            get {
                return ((string)(this["BD_CROMSeguridadConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CROM-ANGELA\\SQLEXPRESS;Initial Catalog=BD_CROMSeguridad;User ID=sa")]
        public string BD_CROMSeguridadConnectionString1 {
            get {
                return ((string)(this["BD_CROMSeguridadConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=W2K3-SRV1\\SQLEXPRESS;Initial Catalog=BD_CROMSeguridad;User ID=sa")]
        public string BD_CROMSeguridadConnectionString2 {
            get {
                return ((string)(this["BD_CROMSeguridadConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=BD_CROMSeguridad;User ID=sa")]
        public string BD_CROMSeguridadConnectionString3 {
            get {
                return ((string)(this["BD_CROMSeguridadConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-HOME\\SQLEXPRESS2014;Initial Catalog=BD_SIS;User ID=sa")]
        public string BD_SISConnectionString {
            get {
                return ((string)(this["BD_SISConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAP01-OCARRIL\\SQLEXPRESSCROM;Initial Catalog=BD_SIS;User ID=sa")]
        public string BD_SISConnectionString1 {
            get {
                return ((string)(this["BD_SISConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-HOME\\SQLEXPRESS2014;Initial Catalog=BD_SIS;User ID=sa;Password" +
            "=uscrom")]
        public string BD_SISConnectionString2 {
            get {
                return ((string)(this["BD_SISConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ocarril.database.windows.net;Initial Catalog=BD_SIS;User ID=adminocar" +
            "ril")]
        public string BD_SISConnectionString3 {
            get {
                return ((string)(this["BD_SISConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ocarril.database.windows.net;Initial Catalog=BD_SIS;Persist Security " +
            "Info=True;User ID=adminocarril")]
        public string BD_SISConnectionString4 {
            get {
                return ((string)(this["BD_SISConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-HOME\\SQLEXPRESS2014;Initial Catalog=BD_SIS;Persist Security In" +
            "fo=True;User ID=sa")]
        public string BD_SISConnectionString5 {
            get {
                return ((string)(this["BD_SISConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-9DE23JC\\SQLEXPRESSCROM15;Initial Catalog=BD_SIS;User ID=sa")]
        public string BD_SISConnectionString6 {
            get {
                return ((string)(this["BD_SISConnectionString6"]));
            }
        }
    }
}
