<?xml version="1.0" encoding="utf-8"?><Database Name="BD_GC_MAGESET" Class="_DBMLMaestrosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAP01-OCARRIL\SQLEXPRESSCROM;Initial Catalog=BD_GC_MAGESET;Persist Security Info=True;User ID=sa;Connect Timeout=30;TrustServerCertificate=False" SettingsObjectName="CROM.TablasMaestras.DataAcces.Properties.Settings" SettingsPropertyName="BD_GC_MAGESETConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="Maestros.TablasMaestrasRegistros" Member="TablasMaestrasRegistros">
    <Type Name="TablasMaestrasRegistro">
      <Column Name="CodigoTabla" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoArgumento" Type="System.String" DbType="VarChar(17) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Nivel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ValorDecimal" Type="System.Decimal" DbType="Decimal(15,5)" CanBeNull="true" />
      <Column Name="ValorCadena" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ValorBoolean" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ValorEntero" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValorFecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Dependencia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SegUsuarioCrea" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="SegUsuarioEdita" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SegFechaHoraCrea" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SegFechaHoraEdita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SegMaquinaOrigen" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="Maestros.omgc_I_Registro" Method="omgc_I_Registro">
    <Parameter Name="prm_codTabla" Type="System.String" DbType="Char(5)" />
    <Parameter Name="prm_codRegistro" Type="System.String" DbType="VarChar(17)" />
    <Parameter Name="prm_numNivel" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_desNombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="prm_gloDescripcion" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="prm_desValorDecimal" Type="System.Decimal" DbType="Decimal(15,5)" />
    <Parameter Name="prm_desValorCadena" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="prm_desValorLogico" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="prm_desValorEntero" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_desValorFecha" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="prm_indActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="prm_segUsuarioCrea" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="prm_segMaquinaOrigen" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Maestros.omgc_I_Tabla" Method="omgc_I_Tabla">
    <Parameter Name="prm_codTabla" Type="System.String" DbType="Char(5)" />
    <Parameter Name="prm_desNombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="prm_gloDescripcion" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="prm_indNivel" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="prm_numLongitudNivel" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_indActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="prm_segUsuarioCrea" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="prm_segMaquinaOrigen" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Maestros.omgc_S_Registro" Method="omgc_S_Registro">
    <Parameter Name="prm_codTabla" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="prm_codRegistro" Type="System.String" DbType="VarChar(17)" />
    <Parameter Name="prm_desNombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="prm_numNivel" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_indActivo" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="omgc_S_RegistroResult">
      <Column Name="codTabla" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="codRegistro" Type="System.String" DbType="VarChar(17) NOT NULL" CanBeNull="false" />
      <Column Name="numNivel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="desNombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="gloDescripcion" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="desValorDecimal" Type="System.Decimal" DbType="Decimal(15,5)" CanBeNull="true" />
      <Column Name="desValorCadena" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="desValorLogico" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="desValorEntero" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="desValorFecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="indActivo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="segUsuCrea" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuEdita" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="segFechaCrea" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="segFechaEdita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="segMaquinaOrigen" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Maestros.omgc_S_Registro_Combo" Method="omgc_S_Registro_Combo">
    <Parameter Name="prm_codTabla" Type="System.String" DbType="Char(5)" />
    <Parameter Name="prm_codRegistro" Type="System.String" DbType="VarChar(17)" />
    <Parameter Name="prm_numNivel" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_indActivo" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="omgc_S_Registro_ComboResult">
      <Column Name="codTabla" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="codRegistro" Type="System.String" DbType="VarChar(17) NOT NULL" CanBeNull="false" />
      <Column Name="numNivel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="desNombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="gloDescripcion" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="desValorDecimal" Type="System.Decimal" DbType="Decimal(15,5)" CanBeNull="true" />
      <Column Name="desValorCadena" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="desValorLogico" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="desValorEntero" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="desValorFecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="indActivo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Maestros.omgc_S_Registro_Paged" Method="omgc_S_Registro_Paged">
    <Parameter Name="prm_NumPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_TamPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_OrdenPor" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="prm_OrdenTipo" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="prm_codTabla" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="prm_codReg" Type="System.String" DbType="VarChar(17)" />
    <Parameter Name="prm_desNombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="prm_numNivel" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_indActivo" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="omgc_S_Registro_PagedResult">
      <Column Name="TOTALROWS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ROWNUM" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="codTabla" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="codRegistro" Type="System.String" DbType="VarChar(17) NOT NULL" CanBeNull="false" />
      <Column Name="numNivel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="desNombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="gloDescripcion" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="desValorDecimal" Type="System.Decimal" DbType="Decimal(15,5)" CanBeNull="true" />
      <Column Name="desValorCadena" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="desValorLogico" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="desValorEntero" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="desValorFecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="indActivo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="segUsuCrea" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuEdita" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="segFechaCrea" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="segFechaEdita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="segMaquinaOrigen" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Maestros.omgc_S_Tabla" Method="omgc_S_Tabla">
    <Parameter Name="prm_codTabla" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="prm_desNombre" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="prm_indActivo" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="omgc_S_TablaResult">
      <Column Name="codTabla" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="desNombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="gloDescripcion" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="numLongitudNivel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="indNivel" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TipoArgumento" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="TipoGeneracion" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="indActivo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="segUsuCrea" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuEdita" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="segFechaCrea" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="segFechaEdita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="segMaquinaOrigen" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Maestros.omgc_S_Tabla_Paged" Method="omgc_S_Tabla_Paged">
    <Parameter Name="prm_NumPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_TamPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_OrdenPor" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="prm_OrdenTipo" Type="System.String" DbType="VarChar(4)" />
    <Parameter Name="prm_codTabla" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="prm_desNombre" Type="System.String" DbType="VarChar(40)" />
    <Parameter Name="prm_indActivo" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="omgc_S_Tabla_PagedResult">
      <Column Name="TOTALROWS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ROWNUM" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="codTabla" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="desNombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="gloDescripcion" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="numLongitudNivel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="indNivel" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="indActivo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="segUsuCrea" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="segUsuEdita" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="segFechaCrea" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="segFechaEdita" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="segMaquinaOrigen" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Maestros.omgc_U_Tabla" Method="omgc_U_Tabla">
    <Parameter Name="prm_codTabla" Type="System.String" DbType="Char(5)" />
    <Parameter Name="prm_desNombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="prm_gloDescripcion" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="prm_indNivel" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="prm_numLongitudNivel" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_indActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="prm_segUsuarioEdita" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="prm_segMaquinaOrigen" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Maestros.omgc_U_Registro" Method="omgc_U_Registro">
    <Parameter Name="prm_codRegistro" Type="System.String" DbType="VarChar(17)" />
    <Parameter Name="prm_numNivel" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_desNombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="prm_gloDescripcion" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="prm_desValorDecimal" Type="System.Decimal" DbType="Decimal(15,5)" />
    <Parameter Name="prm_desValorCadena" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="prm_desValorLogico" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="prm_desValorEntero" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_desValorFecha" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="prm_indActivo" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="prm_segUsuarioEdita" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="prm_segMaquinaOrigen" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Maestros.omgc_D_Tabla" Method="omgc_D_Tabla">
    <Parameter Name="prm_codTabla" Type="System.String" DbType="Char(5)" />
    <Parameter Name="prm_segUsuarioCrea" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="prm_segMaquinaOrigen" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Maestros.omgc_D_Registro" Method="omgc_D_Registro">
    <Parameter Name="prm_codRegistro" Type="System.String" DbType="VarChar(17)" />
    <Parameter Name="prm_segUsuarioEdita" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="prm_segMaquinaOrigen" Type="System.String" DbType="VarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Maestros.omgc_P_Registro_GenerarCodigo" Method="omgc_P_Registro_GenerarCodigo">
    <Parameter Name="prm_codTabla" Type="System.String" DbType="Char(5)" />
    <Parameter Name="prm_numNivel" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_numLongitudNivel" Type="System.Int32" DbType="Int" />
    <Parameter Name="prm_codRegistroPadre" Type="System.String" DbType="VarChar(17)" />
    <Parameter Name="prm_codRegistro" Type="System.String" DbType="VarChar(17)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Maestros.omgc_P_Registro_Ubigeo" Method="omgc_P_Registro_Ubigeo">
    <Parameter Name="prm_codRegistro" Type="System.String" DbType="VarChar(17)" />
    <Parameter Name="prm_desNombreUbigeos" Type="System.String" DbType="VarChar(400)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="Maestros.omgc_P_Tabla_Sys" Method="omgc_P_Tabla_Sys" IsComposable="true">
    <Return Type="object" />
  </Function>
</Database>