//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CROM.GestionAlmacen.DataAccess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;Initial Catalog=BD_GyC;Integrated Security=True")]
        public string BD_GyCConnectionString {
            get {
                return ((string)(this["BD_GyCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-HOME\\SQLEXPRESS2014;Initial Catalog=BD_GC_Yasan;User ID=sa")]
        public string BD_GC_YasanConnectionString {
            get {
                return ((string)(this["BD_GC_YasanConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;Initial Catalog=BD_GC_ELYASAN;Integrated Security=Tru" +
            "e")]
        public string BD_GC_ELYASANConnectionString {
            get {
                return ((string)(this["BD_GC_ELYASANConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-HOME\\SQLEXPRESS2014;Initial Catalog=BD_GC_Yasan;User ID=sa;Pas" +
            "sword=uscrom")]
        public string BD_GC_YasanConnectionString1 {
            get {
                return ((string)(this["BD_GC_YasanConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-HOME\\SQLEXPRESS2014;Initial Catalog=BD_GC_MAGESET;User ID=sa")]
        public string BD_GC_MAGESETConnectionString {
            get {
                return ((string)(this["BD_GC_MAGESETConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-HOME\\SQLEXPRESS2014;Initial Catalog=BD_GC_MAGESET_20180802;Use" +
            "r ID=sa")]
        public string BD_GC_MAGESET_20180802ConnectionString {
            get {
                return ((string)(this["BD_GC_MAGESET_20180802ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAP01-OCARRIL\\SQLEXPRESSCROM;Initial Catalog=BD_GC_MAGESET;Persist Se" +
            "curity Info=True;User ID=sa;Connect Timeout=30;TrustServerCertificate=False")]
        public string BD_GC_MAGESETConnectionString1 {
            get {
                return ((string)(this["BD_GC_MAGESETConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAP01-OCARRIL\\SQLEXPRESSCROM;Initial Catalog=BD_GC_MAGESET_SFS_202011" +
            "06;Persist Security Info=True;User ID=sa;Connect Timeout=30;TrustServerCertifica" +
            "te=False")]
        public string BD_GC_MAGESET_SFS_20201106ConnectionString {
            get {
                return ((string)(this["BD_GC_MAGESET_SFS_20201106ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAP01-OCARRIL\\SQLEXPRESSCROM;Initial Catalog=BD_GC_MAGESET_SFS_202011" +
            "06;User ID=sa")]
        public string BD_GC_MAGESET_SFS_20201106ConnectionString1 {
            get {
                return ((string)(this["BD_GC_MAGESET_SFS_20201106ConnectionString1"]));
            }
        }
    }
}
