//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CROM.GestionComercial.DataAccess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;Initial Catalog=BD_CROM_Sistemas;Integrated Security=Tru" +
            "e")]
        public string BD_CROM_SistemasConnectionString {
            get {
                return ((string)(this["BD_CROM_SistemasConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CROM-001\\SQLEXPRESS;Initial Catalog=BD_CROMSistema;Integrated Securit" +
            "y=True")]
        public string BD_CROMSistemaConnectionString {
            get {
                return ((string)(this["BD_CROMSistemaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XNTWS27\\SQL2008XNTWS27;Initial Catalog=BD_CROMSistema;Integrated Secu" +
            "rity=True")]
        public string BD_CROMSistemaConnectionString1 {
            get {
                return ((string)(this["BD_CROMSistemaConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CROM-001\\SQLEXPRESS;Initial Catalog=BD_CROM_SistemasV2;Integrated Sec" +
            "urity=True")]
        public string BD_CROM_SistemasV2ConnectionString {
            get {
                return ((string)(this["BD_CROM_SistemasV2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CROM-001\\SQLEXPRESS;Initial Catalog=BD_Sistema_V2a;User ID=sa")]
        public string BD_Sistema_V2aConnectionString {
            get {
                return ((string)(this["BD_Sistema_V2aConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CROM-001\\SQLEXPRESS;Initial Catalog=BD_Sistema_V2a;User ID=sa;Passwor" +
            "d=uscrom")]
        public string BD_Sistema_V2aConnectionString1 {
            get {
                return ((string)(this["BD_Sistema_V2aConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\sqlexpress;Initial Catalog=BD_Sistema_V2a;User ID=sa")]
        public string BD_Sistema_V2aConnectionString2 {
            get {
                return ((string)(this["BD_Sistema_V2aConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=BD_Sistema_V2a;User ID=sa")]
        public string BD_Sistema_V2aConnectionString3 {
            get {
                return ((string)(this["BD_Sistema_V2aConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CROM-ANGELA\\SQLEXPRESS;Initial Catalog=BD_Sistema_V2a;User ID=sa")]
        public string BD_Sistema_V2aConnectionString4 {
            get {
                return ((string)(this["BD_Sistema_V2aConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CROM-ANGELA\\MSSQLSERVER2008;Initial Catalog=BD_GestComerCROMv2;Integr" +
            "ated Security=True")]
        public string BD_GestComerCROMv2ConnectionString {
            get {
                return ((string)(this["BD_GestComerCROMv2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=BD_GestComerCROMv2;User ID=sa")]
        public string BD_GestComerCROMv2ConnectionString1 {
            get {
                return ((string)(this["BD_GestComerCROMv2ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=BD_GestComerCROMv2Pruebas;User ID=sa")]
        public string BD_GestComerCROMv2PruebasConnectionString {
            get {
                return ((string)(this["BD_GestComerCROMv2PruebasConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=W2K3-SRV1\\SQLEXPRESS;Initial Catalog=BD_GestComerCROMv2Pruebas;User I" +
            "D=sa")]
        public string BD_GestComerCROMv2PruebasConnectionString1 {
            get {
                return ((string)(this["BD_GestComerCROMv2PruebasConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=W2K3-SRV1\\SQLEXPRESS;Initial Catalog=BD_GestComerCROMv2Pruebasz;User " +
            "ID=sa")]
        public string BD_GestComerCROMv2PruebaszConnectionString {
            get {
                return ((string)(this["BD_GestComerCROMv2PruebaszConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=W2K3-SRV1\\SQLEXPRESS;Initial Catalog=BD_GestComerCROMv2crom;User ID=s" +
            "a")]
        public string BD_GestComerCROMv2cromConnectionString {
            get {
                return ((string)(this["BD_GestComerCROMv2cromConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=W2K3-SRV1\\SQLEXPRESS;Initial Catalog=BD_GestComerCROMv2om;User ID=sa")]
        public string BD_GestComerCROMv2omConnectionString {
            get {
                return ((string)(this["BD_GestComerCROMv2omConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=W2K3-SRV1\\SQLEXPRESS;Initial Catalog=BD_GestComerCROMv2;User ID=sa")]
        public string BD_GestComerCROMv2ConnectionString2 {
            get {
                return ((string)(this["BD_GestComerCROMv2ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=W2K3-SRV1\\SQLEXPRESS;Initial Catalog=BD_GestComerCROMv2om;Integrated " +
            "Security=True")]
        public string BD_GestComerCROMv2omConnectionString1 {
            get {
                return ((string)(this["BD_GestComerCROMv2omConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=W2K3-SRV1\\SQLEXPRESS;Initial Catalog=BD_GestComerCROMv2a;User ID=sa")]
        public string BD_GestComerCROMv2aConnectionString {
            get {
                return ((string)(this["BD_GestComerCROMv2aConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XNTWS27;Initial Catalog=BD_CROMGestionComercial;User ID=sa")]
        public string BD_CROMGestionComercialConnectionString {
            get {
                return ((string)(this["BD_CROMGestionComercialConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XNTWS27;Initial Catalog=BD_CROMGestionParqueo;User ID=sa")]
        public string BD_CROMGestionParqueoConnectionString {
            get {
                return ((string)(this["BD_CROMGestionParqueoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=W2K3-SRV1\\SQLEXPRESS;Initial Catalog=BD_CROMGestionParqueo;User ID=SA" +
            "")]
        public string BD_CROMGestionParqueoConnectionString1 {
            get {
                return ((string)(this["BD_CROMGestionParqueoConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=W2K3-SRV1\\SQLEXPRESS;Initial Catalog=BD_GestComerCROMv2b;User ID=sa")]
        public string BD_GestComerCROMv2bConnectionString {
            get {
                return ((string)(this["BD_GestComerCROMv2bConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XNTWS27;Initial Catalog=BD_CROMGestionComercia;User ID=sa")]
        public string BD_CROMGestionComerciaConnectionString {
            get {
                return ((string)(this["BD_CROMGestionComerciaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=W2K3-SRV1\\SQLEXPRESS;Initial Catalog=BD_CROMComercial;Integrated Secu" +
            "rity=True")]
        public string BD_CROMComercialConnectionString {
            get {
                return ((string)(this["BD_CROMComercialConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=BD_CROMComercial;User ID=sa")]
        public string BD_CROMComercialConnectionString1 {
            get {
                return ((string)(this["BD_CROMComercialConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=W2K3-SRV1\\SQLEXPRESS;Initial Catalog=BD_CROM_SistemasV2;User ID=sa")]
        public string BD_CROM_SistemasV2ConnectionString1 {
            get {
                return ((string)(this["BD_CROM_SistemasV2ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XNTWS27;Initial Catalog=BD_CROM_SistemasV2yasan;Integrated Security=T" +
            "rue")]
        public string BD_CROM_SistemasV2yasanConnectionString {
            get {
                return ((string)(this["BD_CROM_SistemasV2yasanConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=W2K3-SRV1\\SQLEXPRESS;Initial Catalog=BD_CROM_SistemasV2yasan;User ID=" +
            "sa")]
        public string BD_CROM_SistemasV2yasanConnectionString1 {
            get {
                return ((string)(this["BD_CROM_SistemasV2yasanConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=W2K3-SRV1\\SQLEXPRESS;Initial Catalog=BD_CROM_SistemasV2yasan;User ID=" +
            "sa;Password=pass@word1")]
        public string BD_CROM_SistemasV2yasanConnectionString2 {
            get {
                return ((string)(this["BD_CROM_SistemasV2yasanConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=W2K3-SRV1\\SQLEXPRESS;Initial Catalog=BD_CROM_SistemasV2mechatro;User " +
            "ID=sa")]
        public string BD_CROM_SistemasV2mechatroConnectionString {
            get {
                return ((string)(this["BD_CROM_SistemasV2mechatroConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=W2K3-SRV1\\SQLEXPRESS;Initial Catalog=BD_CROM_SistemasV2mechatro;User " +
            "ID=sa;Password=pass@word1")]
        public string BD_CROM_SistemasV2mechatroConnectionString1 {
            get {
                return ((string)(this["BD_CROM_SistemasV2mechatroConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XNTWS27;Initial Catalog=BD_CROM_SistemasV2oxinet;User ID=sa")]
        public string BD_CROM_SistemasV2oxinetConnectionString {
            get {
                return ((string)(this["BD_CROM_SistemasV2oxinetConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XNTWS27;Initial Catalog=BD_CROM_SistemasV2mechatro;User ID=sa")]
        public string BD_CROM_SistemasV2mechatroConnectionString2 {
            get {
                return ((string)(this["BD_CROM_SistemasV2mechatroConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=W2K3-SRV1\\SQLEXPRESS;Initial Catalog=BD_CROM_SistemasV2crom;User ID=S" +
            "A")]
        public string BD_CROM_SistemasV2cromConnectionString {
            get {
                return ((string)(this["BD_CROM_SistemasV2cromConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=W2K3-SRV1\\SQLEXPRESS;Initial Catalog=BD_CROM_SistemasV2crom;User ID=S" +
            "A;Password=pass@word1")]
        public string BD_CROM_SistemasV2cromConnectionString1 {
            get {
                return ((string)(this["BD_CROM_SistemasV2cromConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XNTWS27;Initial Catalog=BD_CROM_SistemasV2yasan;User ID=sa")]
        public string BD_CROM_SistemasV2yasanConnectionString3 {
            get {
                return ((string)(this["BD_CROM_SistemasV2yasanConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-CROM\\SQL08r2crom;Initial Catalog=BD_CROMComercial_DEV;User ID=" +
            "sa")]
        public string BD_CROMComercial_DEVConnectionString {
            get {
                return ((string)(this["BD_CROMComercial_DEVConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-CROM\\SQL08R2CROM;Initial Catalog=BD_GestionComercial_ElYasan;U" +
            "ser ID=sa")]
        public string BD_GestionComercial_ElYasanConnectionString {
            get {
                return ((string)(this["BD_GestionComercial_ElYasanConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-CROM\\SQL08R2CROM;Initial Catalog=BD_GestionComercial_ElYasan;U" +
            "ser ID=sa;Password=uscrom77")]
        public string BD_GestionComercial_ElYasanConnectionString1 {
            get {
                return ((string)(this["BD_GestionComercial_ElYasanConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-PC\\SQLPRODUCCION;Initial Catalog=BD_ComercialMechatronics;User" +
            " ID=sa")]
        public string BD_ComercialMechatronicsConnectionString {
            get {
                return ((string)(this["BD_ComercialMechatronicsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-PC\\SQLPRODUCCION;Initial Catalog=BD_ComercialMechatronics;Pers" +
            "ist Security Info=True;User ID=sa")]
        public string BD_ComercialMechatronicsConnectionString1 {
            get {
                return ((string)(this["BD_ComercialMechatronicsConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-PC\\SQLPRODUCCION;Initial Catalog=BD_ComercialMechatronics;Pers" +
            "ist Security Info=True;User ID=sa;Password=uscrom")]
        public string BD_ComercialMechatronicsConnectionString2 {
            get {
                return ((string)(this["BD_ComercialMechatronicsConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-PC\\SQLPRODUCCION;Initial Catalog=BD_ComercialMageset;Persist S" +
            "ecurity Info=True;User ID=sa")]
        public string BD_ComercialMagesetConnectionString {
            get {
                return ((string)(this["BD_ComercialMagesetConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-PC\\SQLPRODUCCION;Initial Catalog=BD_ComercialMechatronics12121" +
            "2;Integrated Security=True")]
        public string BD_ComercialMechatronics121212ConnectionString {
            get {
                return ((string)(this["BD_ComercialMechatronics121212ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-PC\\SQLPRODUCCION;Initial Catalog=BD_ComercialMechatronics13022" +
            "0b;User ID=SA")]
        public string BD_ComercialMechatronics130220bConnectionString {
            get {
                return ((string)(this["BD_ComercialMechatronics130220bConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-PC\\SQLPRODUCCION;Initial Catalog=BD_ComercialMechatronics13022" +
            "0b;User ID=SA;Password=uscrom")]
        public string BD_ComercialMechatronics130220bConnectionString1 {
            get {
                return ((string)(this["BD_ComercialMechatronics130220bConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-PC\\SQLPRODUCCION;Initial Catalog=BD_CROMComercialB;User ID=sa")]
        public string BD_CROMComercialBConnectionString {
            get {
                return ((string)(this["BD_CROMComercialBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-PC\\SQLPRODUCCION;Initial Catalog=BD_CROMComercialC;User ID=sa")]
        public string BD_CROMComercialCConnectionString {
            get {
                return ((string)(this["BD_CROMComercialCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-PC\\SQLPRODUCCION;Initial Catalog=BD_ComercialMechatronicsC;Use" +
            "r ID=SA")]
        public string BD_ComercialMechatronicsCConnectionString {
            get {
                return ((string)(this["BD_ComercialMechatronicsCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-PC\\SQLPRODUCCION;Initial Catalog=BD_ComercialMaestranzaUlt;Use" +
            "r ID=SA")]
        public string BD_ComercialMaestranzaUltConnectionString {
            get {
                return ((string)(this["BD_ComercialMaestranzaUltConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-PC\\SQLPRODUCCION;Initial Catalog=BD_ComercialMaestranza;User I" +
            "D=SA")]
        public string BD_ComercialMaestranzaConnectionString {
            get {
                return ((string)(this["BD_ComercialMaestranzaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-PC\\SQLPRODUCCION;Initial Catalog=BD_ComercialMaestranza;User I" +
            "D=SA;Password=uscrom")]
        public string BD_ComercialMaestranzaConnectionString1 {
            get {
                return ((string)(this["BD_ComercialMaestranzaConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-PC\\SQLPRODUCCION;Initial Catalog=BD_ComercialMechatronic;User " +
            "ID=sa")]
        public string BD_ComercialMechatronicConnectionString {
            get {
                return ((string)(this["BD_ComercialMechatronicConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-PC\\SQLPRODUCCION;Initial Catalog=BD_ComercialElYasan;User ID=s" +
            "a")]
        public string BD_ComercialElYasanConnectionString {
            get {
                return ((string)(this["BD_ComercialElYasanConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-PC\\SQLPRODUCCION;Initial Catalog=BD_ComercialElYasan;User ID=s" +
            "a;Password=uscrom")]
        public string BD_ComercialElYasanConnectionString1 {
            get {
                return ((string)(this["BD_ComercialElYasanConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-PC\\SQLPRODUCCION;Initial Catalog=BD_ComercialMechatronics;User" +
            " ID=sa;Password=uscrom")]
        public string BD_ComercialMechatronicsConnectionString3 {
            get {
                return ((string)(this["BD_ComercialMechatronicsConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-PC\\SQLPRODUCCION;Initial Catalog=BD_ComercialMechatronics13112" +
            "7;User ID=sa")]
        public string BD_ComercialMechatronics131127ConnectionString {
            get {
                return ((string)(this["BD_ComercialMechatronics131127ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANGELA-PC\\SQLPRODUCCION;Initial Catalog=BD_ComercialMechatronics13112" +
            "7;User ID=sa;Password=uscrom")]
        public string BD_ComercialMechatronics131127ConnectionString1 {
            get {
                return ((string)(this["BD_ComercialMechatronics131127ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MUAKS-PC\\CROMSYSTEM;Initial Catalog=BD_ComercialMechatronics;User ID=" +
            "sa")]
        public string BD_ComercialMechatronicsConnectionString4 {
            get {
                return ((string)(this["BD_ComercialMechatronicsConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MUAKS-PC\\CROMSYSTEM;Initial Catalog=BD_ComercialMechatronics;User ID=" +
            "sa;Password=uscrom")]
        public string BD_ComercialMechatronicsConnectionString5 {
            get {
                return ((string)(this["BD_ComercialMechatronicsConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MUAKS-PC\\CROMSYSTEM;Initial Catalog=BD_MagesetNew;User ID=SA")]
        public string BD_MagesetNewConnectionString {
            get {
                return ((string)(this["BD_MagesetNewConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MUAKS-PC\\CROMSYSTEM;Initial Catalog=BD_MagesetNew;User ID=SA;Password" +
            "=uscrom")]
        public string BD_MagesetNewConnectionString1 {
            get {
                return ((string)(this["BD_MagesetNewConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MUAKS-PC\\CROMSYSTEM;Initial Catalog=BD_ComercialMaestranza150822;User" +
            " ID=sa")]
        public string BD_ComercialMaestranza150822ConnectionString {
            get {
                return ((string)(this["BD_ComercialMaestranza150822ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;Initial Catalog=BD_GyC;Integrated Security=True")]
        public string BD_GyCConnectionString {
            get {
                return ((string)(this["BD_GyCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-P542EDPJ\\SQLEXPRESS2014;Initial Catalog=BD_GC_Yasan;Integrated" +
            " Security=True")]
        public string BD_GC_YasanConnectionString {
            get {
                return ((string)(this["BD_GC_YasanConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;Initial Catalog=BD_GC_ELYASAN;Integrated Security=Tru" +
            "e")]
        public string BD_GC_ELYASANConnectionString {
            get {
                return ((string)(this["BD_GC_ELYASANConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-HOME\\SQLEXPRESS2014;Initial Catalog=BD_GC_Yasan;User ID=sa")]
        public string BD_GC_YasanConnectionString1 {
            get {
                return ((string)(this["BD_GC_YasanConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-HOME\\SQLEXPRESS2014;Initial Catalog=BD_GC_Yasan;User ID=SA")]
        public string BD_GC_YasanConnectionString2 {
            get {
                return ((string)(this["BD_GC_YasanConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-HOME\\SQLEXPRESS2014;Initial Catalog=BD_GC_MAGESET;User ID=sa")]
        public string BD_GC_MAGESETConnectionString {
            get {
                return ((string)(this["BD_GC_MAGESETConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAP01-OCARRIL\\SQLEXPRESSCROM;Initial Catalog=BD_GC_MAGESET;User ID=sa" +
            "")]
        public string BD_GC_MAGESETConnectionString1 {
            get {
                return ((string)(this["BD_GC_MAGESETConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAP01-OCARRIL\\SQLEXPRESSCROM;Initial Catalog=BD_GC_MAGESET;User ID=sa" +
            ";Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string BD_GC_MAGESETConnectionString2 {
            get {
                return ((string)(this["BD_GC_MAGESETConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-HOME\\SQLEXPRESS2014;Initial Catalog=BD_GC_MAGESET_20180802;Use" +
            "r ID=sa")]
        public string BD_GC_MAGESET_20180802ConnectionString {
            get {
                return ((string)(this["BD_GC_MAGESET_20180802ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAP01-OCARRIL\\SQLEXPRESSCROM;Initial Catalog=BD_GC_MAGESET;User ID=sa" +
            ";Connect Timeout=30;TrustServerCertificate=False")]
        public string BD_GC_MAGESETConnectionString3 {
            get {
                return ((string)(this["BD_GC_MAGESETConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAP01-OCARRIL\\SQLEXPRESSCROM;Initial Catalog=BD_GC_MAGESET;Persist Se" +
            "curity Info=True;User ID=sa;Connect Timeout=30;TrustServerCertificate=False")]
        public string BD_GC_MAGESETConnectionString4 {
            get {
                return ((string)(this["BD_GC_MAGESETConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAP01-OCARRIL\\SQLEXPRESSCROM;Initial Catalog=BD_GC_MAGESET;Persist Se" +
            "curity Info=True;User ID=sa;Password=uscrom77;Connect Timeout=30;TrustServerCert" +
            "ificate=False")]
        public string BD_GC_MAGESETConnectionString5 {
            get {
                return ((string)(this["BD_GC_MAGESETConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-HOME\\SQLEXPRESS2014;Initial Catalog=BD_GC_MAGESET_FE;User ID=s" +
            "a")]
        public string BD_GC_MAGESET_FEConnectionString {
            get {
                return ((string)(this["BD_GC_MAGESET_FEConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAP01-OCARRIL\\SQLEXPRESSCROM;Initial Catalog=BD_GC_MAGESET_FE;Persist" +
            " Security Info=True;User ID=sa;Connect Timeout=30;TrustServerCertificate=False")]
        public string BD_GC_MAGESET_FEConnectionString1 {
            get {
                return ((string)(this["BD_GC_MAGESET_FEConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAP01-OCARRIL\\SQLEXPRESSCROM;Initial Catalog=BD_GC_MAGESET_SFS_202011" +
            "06;Persist Security Info=True;User ID=sa;Connect Timeout=30;TrustServerCertifica" +
            "te=False")]
        public string BD_GC_MAGESET_SFS_20201106ConnectionString {
            get {
                return ((string)(this["BD_GC_MAGESET_SFS_20201106ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAP01-OCARRIL\\SQLEXPRESSCROM;Initial Catalog=BD_GC_MAGESET_SFS_202011" +
            "06;User ID=sa")]
        public string BD_GC_MAGESET_SFS_20201106ConnectionString1 {
            get {
                return ((string)(this["BD_GC_MAGESET_SFS_20201106ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAP01-OCARRIL\\SQLEXPRESSCROM;Initial Catalog=BD_GC_MAGESET_SFS_202011" +
            "06;Persist Security Info=True;User ID=sa")]
        public string BD_GC_MAGESET_SFS_20201106ConnectionString2 {
            get {
                return ((string)(this["BD_GC_MAGESET_SFS_20201106ConnectionString2"]));
            }
        }
    }
}
