#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CROM.Seguridad.DataAcces.acceso
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_SIS")]
	public partial class DBML_AccesoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DBML_AccesoDataContext() : 
				base(global::CROM.Seguridad.DataAcces.Properties.Settings.Default.BD_SISConnectionString5, mappingSource)
		{
			OnCreated();
		}
		
		public DBML_AccesoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBML_AccesoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBML_AccesoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBML_AccesoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Seguridad.omgc_pro_SII_Auditoria")]
		public int omgc_pro_SII_Auditoria([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_codSistema, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string p_codRol, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_desLogin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string p_desMensaje, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string p_desTipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> p_fecRegistroApp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string p_nomMaquinaIP, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> p_numVeces)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codSistema, p_codRol, p_codUsuario, p_desLogin, p_desMensaje, p_desTipo, p_fecRegistroApp, p_nomMaquinaIP, p_codEmpresa, p_numVeces);
			p_numVeces = ((System.Nullable<int>)(result.GetParameterValue(9)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Seguridad.omgc_pro_SIS_Auditoria")]
		public ISingleResult<omgc_pro_SIS_AuditoriaResult> omgc_pro_SIS_Auditoria([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_NumPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_TamPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string p_OrdenPor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string p_OrdenTipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string p_codSistema, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string p_codRol, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] string p_fecInicio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] string p_fecFinal)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_NumPagina, p_TamPagina, p_OrdenPor, p_OrdenTipo, p_codEmpresa, p_codSistema, p_codRol, p_codUsuario, p_fecInicio, p_fecFinal);
			return ((ISingleResult<omgc_pro_SIS_AuditoriaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Seguridad.omgc_pro_SIS_Usuario_DetectLoginPassword")]
		public ISingleResult<omgc_pro_SIS_Usuario_DetectLoginPasswordResult> omgc_pro_SIS_Usuario_DetectLoginPassword([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_LoginUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_LoginUsuario);
			return ((ISingleResult<omgc_pro_SIS_Usuario_DetectLoginPasswordResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Seguridad.omgc_pro_SIS_Usuario_LoginValidated")]
		public ISingleResult<omgc_pro_SIS_Usuario_LoginValidatedResult> omgc_pro_SIS_Usuario_LoginValidated([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_LoginUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_LoginUsuario);
			return ((ISingleResult<omgc_pro_SIS_Usuario_LoginValidatedResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Seguridad.omgc_pro_SIU_Usuario_fecBloqueoUpdate")]
		public ISingleResult<omgc_pro_SIU_Usuario_fecBloqueoUpdateResult> omgc_pro_SIU_Usuario_fecBloqueoUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> p_flagBloquea, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_segUsuarioEdita, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segMaquina)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codUsuario, p_flagBloquea, p_segUsuarioEdita, p_segMaquina);
			return ((ISingleResult<omgc_pro_SIU_Usuario_fecBloqueoUpdateResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Seguridad.omgc_pro_SIU_Usuario_indPasswordReset")]
		public ISingleResult<omgc_pro_SIU_Usuario_indPasswordResetResult> omgc_pro_SIU_Usuario_indPasswordReset([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string p_codUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string p_password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_segUsuarioEdita, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segMaquina)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codUsuario, p_password, p_segUsuarioEdita, p_segMaquina);
			return ((ISingleResult<omgc_pro_SIU_Usuario_indPasswordResetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Seguridad.omgc_pro_SIU_Usuario_PasswordExterno")]
		public ISingleResult<omgc_pro_SIU_Usuario_PasswordExternoResult> omgc_pro_SIU_Usuario_PasswordExterno([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_desLogin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string p_clvPassword, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_segUsuarioEdita, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] string p_segMaquina)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_desLogin, p_clvPassword, p_segUsuarioEdita, p_segMaquina);
			return ((ISingleResult<omgc_pro_SIU_Usuario_PasswordExternoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Seguridad.usp_sis_R_UsuarioObjeto")]
		public ISingleResult<usp_sis_R_UsuarioObjetoResult> usp_sis_R_UsuarioObjeto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> p_codEmpresa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string p_codSistema, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_desLogin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string p_tipObjeto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string p_nomAction)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_codEmpresa, p_codSistema, p_desLogin, p_tipObjeto, p_nomAction);
			return ((ISingleResult<usp_sis_R_UsuarioObjetoResult>)(result.ReturnValue));
		}
	}
	
	public partial class omgc_pro_SIS_AuditoriaResult
	{
		
		private int _codAuditoria;
		
		private System.Nullable<int> _codEmpresa;
		
		private string _codEmpresaNombre;
		
		private string _codSistema;
		
		private string _codSistemaNombre;
		
		private string _codRol;
		
		private string _codRolNombre;
		
		private string _codUsuario;
		
		private string _codUsuarioNombre;
		
		private string _desLogin;
		
		private string _desMensaje;
		
		private string _desTipo;
		
		private System.DateTime _fecRegistroApp;
		
		private string _nomMaquinaIP;
		
		private System.Nullable<int> _TOTALROWS;
		
		private System.Nullable<long> _ROWNUM;
		
		public omgc_pro_SIS_AuditoriaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codAuditoria", DbType="Int NOT NULL")]
		public int codAuditoria
		{
			get
			{
				return this._codAuditoria;
			}
			set
			{
				if ((this._codAuditoria != value))
				{
					this._codAuditoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpresa", DbType="Int")]
		public System.Nullable<int> codEmpresa
		{
			get
			{
				return this._codEmpresa;
			}
			set
			{
				if ((this._codEmpresa != value))
				{
					this._codEmpresa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpresaNombre", DbType="VarChar(150)")]
		public string codEmpresaNombre
		{
			get
			{
				return this._codEmpresaNombre;
			}
			set
			{
				if ((this._codEmpresaNombre != value))
				{
					this._codEmpresaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codSistema", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string codSistema
		{
			get
			{
				return this._codSistema;
			}
			set
			{
				if ((this._codSistema != value))
				{
					this._codSistema = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codSistemaNombre", DbType="VarChar(40)")]
		public string codSistemaNombre
		{
			get
			{
				return this._codSistemaNombre;
			}
			set
			{
				if ((this._codSistemaNombre != value))
				{
					this._codSistemaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRol", DbType="VarChar(4)")]
		public string codRol
		{
			get
			{
				return this._codRol;
			}
			set
			{
				if ((this._codRol != value))
				{
					this._codRol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRolNombre", DbType="VarChar(25)")]
		public string codRolNombre
		{
			get
			{
				return this._codRolNombre;
			}
			set
			{
				if ((this._codRolNombre != value))
				{
					this._codRolNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codUsuario", DbType="VarChar(10)")]
		public string codUsuario
		{
			get
			{
				return this._codUsuario;
			}
			set
			{
				if ((this._codUsuario != value))
				{
					this._codUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codUsuarioNombre", DbType="VarChar(82) NOT NULL", CanBeNull=false)]
		public string codUsuarioNombre
		{
			get
			{
				return this._codUsuarioNombre;
			}
			set
			{
				if ((this._codUsuarioNombre != value))
				{
					this._codUsuarioNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desLogin", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string desLogin
		{
			get
			{
				return this._desLogin;
			}
			set
			{
				if ((this._desLogin != value))
				{
					this._desLogin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desMensaje", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string desMensaje
		{
			get
			{
				return this._desMensaje;
			}
			set
			{
				if ((this._desMensaje != value))
				{
					this._desMensaje = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desTipo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string desTipo
		{
			get
			{
				return this._desTipo;
			}
			set
			{
				if ((this._desTipo != value))
				{
					this._desTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecRegistroApp", DbType="DateTime NOT NULL")]
		public System.DateTime fecRegistroApp
		{
			get
			{
				return this._fecRegistroApp;
			}
			set
			{
				if ((this._fecRegistroApp != value))
				{
					this._fecRegistroApp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomMaquinaIP", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nomMaquinaIP
		{
			get
			{
				return this._nomMaquinaIP;
			}
			set
			{
				if ((this._nomMaquinaIP != value))
				{
					this._nomMaquinaIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTALROWS", DbType="Int")]
		public System.Nullable<int> TOTALROWS
		{
			get
			{
				return this._TOTALROWS;
			}
			set
			{
				if ((this._TOTALROWS != value))
				{
					this._TOTALROWS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROWNUM", DbType="BigInt")]
		public System.Nullable<long> ROWNUM
		{
			get
			{
				return this._ROWNUM;
			}
			set
			{
				if ((this._ROWNUM != value))
				{
					this._ROWNUM = value;
				}
			}
		}
	}
	
	public partial class omgc_pro_SIS_Usuario_DetectLoginPasswordResult
	{
		
		private System.Nullable<int> _codError;
		
		private string _desMessage;
		
		private string _clvPassword;
		
		private System.Nullable<bool> _indPasswordReset;
		
		private System.Nullable<bool> _indBloqueoUpdate;
		
		private System.Nullable<System.DateTime> _fecBloqueoUpdate;
		
		public omgc_pro_SIS_Usuario_DetectLoginPasswordResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codError", DbType="Int")]
		public System.Nullable<int> codError
		{
			get
			{
				return this._codError;
			}
			set
			{
				if ((this._codError != value))
				{
					this._codError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desMessage", DbType="VarChar(34) NOT NULL", CanBeNull=false)]
		public string desMessage
		{
			get
			{
				return this._desMessage;
			}
			set
			{
				if ((this._desMessage != value))
				{
					this._desMessage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clvPassword", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string clvPassword
		{
			get
			{
				return this._clvPassword;
			}
			set
			{
				if ((this._clvPassword != value))
				{
					this._clvPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indPasswordReset", DbType="Bit")]
		public System.Nullable<bool> indPasswordReset
		{
			get
			{
				return this._indPasswordReset;
			}
			set
			{
				if ((this._indPasswordReset != value))
				{
					this._indPasswordReset = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indBloqueoUpdate", DbType="Bit")]
		public System.Nullable<bool> indBloqueoUpdate
		{
			get
			{
				return this._indBloqueoUpdate;
			}
			set
			{
				if ((this._indBloqueoUpdate != value))
				{
					this._indBloqueoUpdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecBloqueoUpdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecBloqueoUpdate
		{
			get
			{
				return this._fecBloqueoUpdate;
			}
			set
			{
				if ((this._fecBloqueoUpdate != value))
				{
					this._fecBloqueoUpdate = value;
				}
			}
		}
	}
	
	public partial class omgc_pro_SIS_Usuario_LoginValidatedResult
	{
		
		private string _codUsuario;
		
		private string _desLogin;
		
		private string _clvPassword;
		
		private string _desNombres;
		
		private string _desApellidos;
		
		private string _desPregunta;
		
		private string _desRespuesta;
		
		private string _desTelefono;
		
		private string _desCorreo;
		
		private bool _indRestricPorPais;
		
		private string _codEmpleado;
		
		private bool _indVendedor;
		
		private bool _indCambioPrecio;
		
		private bool _indAccesoGerencial;
		
		private bool _indCambiaDescuento;
		
		private bool _indCambiaCodPersona;
		
		private bool _indJefeCaja;
		
		private bool _indUsuarioSistema;
		
		private bool _indEstado;
		
		private string _segUsuarioCrea;
		
		private string _segUsuarioEdita;
		
		private System.DateTime _segFechaHoraCrea;
		
		private System.Nullable<System.DateTime> _segFechaHoraEdita;
		
		private string _segMaquinaOrigen;
		
		private string _codArguPais;
		
		private System.Nullable<System.DateTime> _segFechaEditaPWD;
		
		private bool _indPasswordReset;
		
		private System.Nullable<System.DateTime> _fecBloqueoUpdate;
		
		private string _urlPhotoUser;
		
		private string _indOrigenUser;
		
		private string _codGUID;
		
		private string _codSistemaNombre;
		
		private string _codRolNombre;
		
		private string _codEmpresaNombre;
		
		public omgc_pro_SIS_Usuario_LoginValidatedResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codUsuario", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string codUsuario
		{
			get
			{
				return this._codUsuario;
			}
			set
			{
				if ((this._codUsuario != value))
				{
					this._codUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desLogin", DbType="VarChar(50)")]
		public string desLogin
		{
			get
			{
				return this._desLogin;
			}
			set
			{
				if ((this._desLogin != value))
				{
					this._desLogin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clvPassword", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string clvPassword
		{
			get
			{
				return this._clvPassword;
			}
			set
			{
				if ((this._clvPassword != value))
				{
					this._clvPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desNombres", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string desNombres
		{
			get
			{
				return this._desNombres;
			}
			set
			{
				if ((this._desNombres != value))
				{
					this._desNombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desApellidos", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string desApellidos
		{
			get
			{
				return this._desApellidos;
			}
			set
			{
				if ((this._desApellidos != value))
				{
					this._desApellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desPregunta", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string desPregunta
		{
			get
			{
				return this._desPregunta;
			}
			set
			{
				if ((this._desPregunta != value))
				{
					this._desPregunta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desRespuesta", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string desRespuesta
		{
			get
			{
				return this._desRespuesta;
			}
			set
			{
				if ((this._desRespuesta != value))
				{
					this._desRespuesta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desTelefono", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string desTelefono
		{
			get
			{
				return this._desTelefono;
			}
			set
			{
				if ((this._desTelefono != value))
				{
					this._desTelefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desCorreo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string desCorreo
		{
			get
			{
				return this._desCorreo;
			}
			set
			{
				if ((this._desCorreo != value))
				{
					this._desCorreo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indRestricPorPais", DbType="Bit NOT NULL")]
		public bool indRestricPorPais
		{
			get
			{
				return this._indRestricPorPais;
			}
			set
			{
				if ((this._indRestricPorPais != value))
				{
					this._indRestricPorPais = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpleado", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string codEmpleado
		{
			get
			{
				return this._codEmpleado;
			}
			set
			{
				if ((this._codEmpleado != value))
				{
					this._codEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indVendedor", DbType="Bit NOT NULL")]
		public bool indVendedor
		{
			get
			{
				return this._indVendedor;
			}
			set
			{
				if ((this._indVendedor != value))
				{
					this._indVendedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indCambioPrecio", DbType="Bit NOT NULL")]
		public bool indCambioPrecio
		{
			get
			{
				return this._indCambioPrecio;
			}
			set
			{
				if ((this._indCambioPrecio != value))
				{
					this._indCambioPrecio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indAccesoGerencial", DbType="Bit NOT NULL")]
		public bool indAccesoGerencial
		{
			get
			{
				return this._indAccesoGerencial;
			}
			set
			{
				if ((this._indAccesoGerencial != value))
				{
					this._indAccesoGerencial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indCambiaDescuento", DbType="Bit NOT NULL")]
		public bool indCambiaDescuento
		{
			get
			{
				return this._indCambiaDescuento;
			}
			set
			{
				if ((this._indCambiaDescuento != value))
				{
					this._indCambiaDescuento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indCambiaCodPersona", DbType="Bit NOT NULL")]
		public bool indCambiaCodPersona
		{
			get
			{
				return this._indCambiaCodPersona;
			}
			set
			{
				if ((this._indCambiaCodPersona != value))
				{
					this._indCambiaCodPersona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indJefeCaja", DbType="Bit NOT NULL")]
		public bool indJefeCaja
		{
			get
			{
				return this._indJefeCaja;
			}
			set
			{
				if ((this._indJefeCaja != value))
				{
					this._indJefeCaja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indUsuarioSistema", DbType="Bit NOT NULL")]
		public bool indUsuarioSistema
		{
			get
			{
				return this._indUsuarioSistema;
			}
			set
			{
				if ((this._indUsuarioSistema != value))
				{
					this._indUsuarioSistema = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indEstado", DbType="Bit NOT NULL")]
		public bool indEstado
		{
			get
			{
				return this._indEstado;
			}
			set
			{
				if ((this._indEstado != value))
				{
					this._indEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioCrea", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string segUsuarioCrea
		{
			get
			{
				return this._segUsuarioCrea;
			}
			set
			{
				if ((this._segUsuarioCrea != value))
				{
					this._segUsuarioCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segUsuarioEdita", DbType="VarChar(50)")]
		public string segUsuarioEdita
		{
			get
			{
				return this._segUsuarioEdita;
			}
			set
			{
				if ((this._segUsuarioEdita != value))
				{
					this._segUsuarioEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaHoraCrea", DbType="DateTime NOT NULL")]
		public System.DateTime segFechaHoraCrea
		{
			get
			{
				return this._segFechaHoraCrea;
			}
			set
			{
				if ((this._segFechaHoraCrea != value))
				{
					this._segFechaHoraCrea = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaHoraEdita", DbType="DateTime")]
		public System.Nullable<System.DateTime> segFechaHoraEdita
		{
			get
			{
				return this._segFechaHoraEdita;
			}
			set
			{
				if ((this._segFechaHoraEdita != value))
				{
					this._segFechaHoraEdita = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segMaquinaOrigen", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string segMaquinaOrigen
		{
			get
			{
				return this._segMaquinaOrigen;
			}
			set
			{
				if ((this._segMaquinaOrigen != value))
				{
					this._segMaquinaOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codArguPais", DbType="VarChar(17) NOT NULL", CanBeNull=false)]
		public string codArguPais
		{
			get
			{
				return this._codArguPais;
			}
			set
			{
				if ((this._codArguPais != value))
				{
					this._codArguPais = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_segFechaEditaPWD", DbType="DateTime")]
		public System.Nullable<System.DateTime> segFechaEditaPWD
		{
			get
			{
				return this._segFechaEditaPWD;
			}
			set
			{
				if ((this._segFechaEditaPWD != value))
				{
					this._segFechaEditaPWD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indPasswordReset", DbType="Bit NOT NULL")]
		public bool indPasswordReset
		{
			get
			{
				return this._indPasswordReset;
			}
			set
			{
				if ((this._indPasswordReset != value))
				{
					this._indPasswordReset = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecBloqueoUpdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecBloqueoUpdate
		{
			get
			{
				return this._fecBloqueoUpdate;
			}
			set
			{
				if ((this._fecBloqueoUpdate != value))
				{
					this._fecBloqueoUpdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlPhotoUser", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string urlPhotoUser
		{
			get
			{
				return this._urlPhotoUser;
			}
			set
			{
				if ((this._urlPhotoUser != value))
				{
					this._urlPhotoUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indOrigenUser", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string indOrigenUser
		{
			get
			{
				return this._indOrigenUser;
			}
			set
			{
				if ((this._indOrigenUser != value))
				{
					this._indOrigenUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codGUID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string codGUID
		{
			get
			{
				return this._codGUID;
			}
			set
			{
				if ((this._codGUID != value))
				{
					this._codGUID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codSistemaNombre", DbType="NVarChar(MAX)")]
		public string codSistemaNombre
		{
			get
			{
				return this._codSistemaNombre;
			}
			set
			{
				if ((this._codSistemaNombre != value))
				{
					this._codSistemaNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codRolNombre", DbType="NVarChar(MAX)")]
		public string codRolNombre
		{
			get
			{
				return this._codRolNombre;
			}
			set
			{
				if ((this._codRolNombre != value))
				{
					this._codRolNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEmpresaNombre", DbType="NVarChar(MAX)")]
		public string codEmpresaNombre
		{
			get
			{
				return this._codEmpresaNombre;
			}
			set
			{
				if ((this._codEmpresaNombre != value))
				{
					this._codEmpresaNombre = value;
				}
			}
		}
	}
	
	public partial class omgc_pro_SIU_Usuario_fecBloqueoUpdateResult
	{
		
		private System.Nullable<int> _codError;
		
		private string _desMessage;
		
		public omgc_pro_SIU_Usuario_fecBloqueoUpdateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codError", DbType="Int")]
		public System.Nullable<int> codError
		{
			get
			{
				return this._codError;
			}
			set
			{
				if ((this._codError != value))
				{
					this._codError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desMessage", DbType="VarChar(28) NOT NULL", CanBeNull=false)]
		public string desMessage
		{
			get
			{
				return this._desMessage;
			}
			set
			{
				if ((this._desMessage != value))
				{
					this._desMessage = value;
				}
			}
		}
	}
	
	public partial class omgc_pro_SIU_Usuario_indPasswordResetResult
	{
		
		private System.Nullable<int> _codError;
		
		private string _desMessage;
		
		public omgc_pro_SIU_Usuario_indPasswordResetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codError", DbType="Int")]
		public System.Nullable<int> codError
		{
			get
			{
				return this._codError;
			}
			set
			{
				if ((this._codError != value))
				{
					this._codError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desMessage", DbType="VarChar(28) NOT NULL", CanBeNull=false)]
		public string desMessage
		{
			get
			{
				return this._desMessage;
			}
			set
			{
				if ((this._desMessage != value))
				{
					this._desMessage = value;
				}
			}
		}
	}
	
	public partial class omgc_pro_SIU_Usuario_PasswordExternoResult
	{
		
		private System.Nullable<int> _codError;
		
		private string _desMessage;
		
		public omgc_pro_SIU_Usuario_PasswordExternoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codError", DbType="Int")]
		public System.Nullable<int> codError
		{
			get
			{
				return this._codError;
			}
			set
			{
				if ((this._codError != value))
				{
					this._codError = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desMessage", DbType="VarChar(50)")]
		public string desMessage
		{
			get
			{
				return this._desMessage;
			}
			set
			{
				if ((this._desMessage != value))
				{
					this._desMessage = value;
				}
			}
		}
	}
	
	public partial class usp_sis_R_UsuarioObjetoResult
	{
		
		private int _ID;
		
		private string _codOpcion;
		
		private string _codOpcionPadre;
		
		private string _codOpcionNombre;
		
		private string _codOpcionDescripcion;
		
		private string _codOpcionPadreNombre;
		
		private string _desEnlaceURL;
		
		private string _desEnlaceWIN;
		
		private string _desEnlacePadre;
		
		private System.Nullable<bool> _indVer;
		
		private System.Nullable<bool> _indNuevo;
		
		private System.Nullable<bool> _indEditar;
		
		private System.Nullable<bool> _indEliminar;
		
		private System.Nullable<bool> _indImprime;
		
		private System.Nullable<bool> _indImporta;
		
		private System.Nullable<bool> _indExporta;
		
		private System.Nullable<bool> _indOtro;
		
		private string _nomIcono;
		
		private string _indTipoObjeto;
		
		private System.Nullable<int> _numOrden;
		
		private string _codElementoID;
		
		private System.Nullable<int> _numOrdenPadre;
		
		public usp_sis_R_UsuarioObjetoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codOpcion", DbType="VarChar(4)")]
		public string codOpcion
		{
			get
			{
				return this._codOpcion;
			}
			set
			{
				if ((this._codOpcion != value))
				{
					this._codOpcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codOpcionPadre", DbType="VarChar(4)")]
		public string codOpcionPadre
		{
			get
			{
				return this._codOpcionPadre;
			}
			set
			{
				if ((this._codOpcionPadre != value))
				{
					this._codOpcionPadre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codOpcionNombre", DbType="VarChar(50)")]
		public string codOpcionNombre
		{
			get
			{
				return this._codOpcionNombre;
			}
			set
			{
				if ((this._codOpcionNombre != value))
				{
					this._codOpcionNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codOpcionDescripcion", DbType="VarChar(50)")]
		public string codOpcionDescripcion
		{
			get
			{
				return this._codOpcionDescripcion;
			}
			set
			{
				if ((this._codOpcionDescripcion != value))
				{
					this._codOpcionDescripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codOpcionPadreNombre", DbType="VarChar(50)")]
		public string codOpcionPadreNombre
		{
			get
			{
				return this._codOpcionPadreNombre;
			}
			set
			{
				if ((this._codOpcionPadreNombre != value))
				{
					this._codOpcionPadreNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desEnlaceURL", DbType="VarChar(100)")]
		public string desEnlaceURL
		{
			get
			{
				return this._desEnlaceURL;
			}
			set
			{
				if ((this._desEnlaceURL != value))
				{
					this._desEnlaceURL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desEnlaceWIN", DbType="VarChar(100)")]
		public string desEnlaceWIN
		{
			get
			{
				return this._desEnlaceWIN;
			}
			set
			{
				if ((this._desEnlaceWIN != value))
				{
					this._desEnlaceWIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desEnlacePadre", DbType="VarChar(100)")]
		public string desEnlacePadre
		{
			get
			{
				return this._desEnlacePadre;
			}
			set
			{
				if ((this._desEnlacePadre != value))
				{
					this._desEnlacePadre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indVer", DbType="Bit")]
		public System.Nullable<bool> indVer
		{
			get
			{
				return this._indVer;
			}
			set
			{
				if ((this._indVer != value))
				{
					this._indVer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indNuevo", DbType="Bit")]
		public System.Nullable<bool> indNuevo
		{
			get
			{
				return this._indNuevo;
			}
			set
			{
				if ((this._indNuevo != value))
				{
					this._indNuevo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indEditar", DbType="Bit")]
		public System.Nullable<bool> indEditar
		{
			get
			{
				return this._indEditar;
			}
			set
			{
				if ((this._indEditar != value))
				{
					this._indEditar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indEliminar", DbType="Bit")]
		public System.Nullable<bool> indEliminar
		{
			get
			{
				return this._indEliminar;
			}
			set
			{
				if ((this._indEliminar != value))
				{
					this._indEliminar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indImprime", DbType="Bit")]
		public System.Nullable<bool> indImprime
		{
			get
			{
				return this._indImprime;
			}
			set
			{
				if ((this._indImprime != value))
				{
					this._indImprime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indImporta", DbType="Bit")]
		public System.Nullable<bool> indImporta
		{
			get
			{
				return this._indImporta;
			}
			set
			{
				if ((this._indImporta != value))
				{
					this._indImporta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indExporta", DbType="Bit")]
		public System.Nullable<bool> indExporta
		{
			get
			{
				return this._indExporta;
			}
			set
			{
				if ((this._indExporta != value))
				{
					this._indExporta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indOtro", DbType="Bit")]
		public System.Nullable<bool> indOtro
		{
			get
			{
				return this._indOtro;
			}
			set
			{
				if ((this._indOtro != value))
				{
					this._indOtro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomIcono", DbType="VarChar(50)")]
		public string nomIcono
		{
			get
			{
				return this._nomIcono;
			}
			set
			{
				if ((this._nomIcono != value))
				{
					this._nomIcono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indTipoObjeto", DbType="VarChar(50)")]
		public string indTipoObjeto
		{
			get
			{
				return this._indTipoObjeto;
			}
			set
			{
				if ((this._indTipoObjeto != value))
				{
					this._indTipoObjeto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numOrden", DbType="Int")]
		public System.Nullable<int> numOrden
		{
			get
			{
				return this._numOrden;
			}
			set
			{
				if ((this._numOrden != value))
				{
					this._numOrden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codElementoID", DbType="VarChar(70)")]
		public string codElementoID
		{
			get
			{
				return this._codElementoID;
			}
			set
			{
				if ((this._codElementoID != value))
				{
					this._codElementoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numOrdenPadre", DbType="Int")]
		public System.Nullable<int> numOrdenPadre
		{
			get
			{
				return this._numOrdenPadre;
			}
			set
			{
				if ((this._numOrdenPadre != value))
				{
					this._numOrdenPadre = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
